### PR TITLE
Shift around headings and tips

### PR DESCRIPTION
**Pull request by ahuang11**
### Summary

Shift headings and add tips about blocks

### Steps Taken to QA Changes

Ran the examples in a notebook

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- No tests or issue needed
- [ ] A short code fix
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. One-line fixes without tests will not be accepted unless it's related to the documentation only.
- [ ] A new feature implementation
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

### CODE REVIEW

**Comment by desertaxle** [comment]
AFAIK, these example are runnable in a Python environment where an event loop is not running (like a Python script). They don't work in a Jupyter notebook because there is an event loop running behind the scenes. Maybe we should include a callout that you'll need to add an `await` to `.save()` and `.load()` calls if running the examples in a notebook?

**Comment by ahuang11** [comment]
I wonder if we can detect "Jupyter notebook because there is an event loop running behind the scenes" and handle properly
https://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook

**Review by tpdorsey — APPROVED** [review]
LGTM from a docs perspective

**Comment by desertaxle** [comment]
> But regardless, I think we need to move loading block header up one paragraph.

I agree with that part. Can you revert the code changes for now while we try to sort out how to message sync compatibility?

**Comment by ahuang11** [comment]
Okay updated

**Review by tpdorsey — APPROVED** [review]

**Review by desertaxle — APPROVED** [review]

**Pull request merged**
