### PR TITLE
Fix `DockerContainer` log streaming crash due to "marked for removal"

### PR DESCRIPTION
**Pull request by madkinsz**
Fixes issues seen during a few test suite runs where `container.logs` throws an `APIError` error due to the container being marked for removal.

- We only call `container.logs` if `stream_output` is set
- We capture Docker `APIErrors` on `logs` calls and log a warning without crashing

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [x] This pull request includes a `fix`, `feature`, `enhancement`, `docs`, `collections`, or `maintenance` label categorizing the change.

### CODE REVIEW

**Comment by madkinsz** [comment]
There is no existing tests coverage for this. We should add test coverage for log streaming, especially with a mocked client throwing these errors.

**Comment by madkinsz** [comment]
@abrookins can you investigate finding someone interested in writing these tests?

**Comment by desertaxle** [comment]
@zzstoatzz and I can look into writing tests for log streaming next week.

**Review by desertaxle — APPROVED** [review]
LGTM!

**Pull request merged**
