### PR TITLE
Standardize work pool name as Process

### LINKED ISSUE #10842: Standardize process work pool type name in the UI and CLI (process vs. subprocess)
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Local Subprocess is the term when creating a work pool in the UI
Screenshot 2023-09-27 at 6 12 28 PM

After creation in the UI it is referred to as a Process work pool.
Screenshot 2023-09-27 at 6 13 11 PM

Screenshot 2023-09-27 at 6 13 34 PM

The CLI also refers to it as a process work pool.
Screenshot 2023-09-27 at 6 14 37 PM

### Describe the proposed behavior

Standardizing on process or subprocess would be good for users.

### Example Use

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by discdiver**
Closes #10842

Updates docs and server instance UI to refer to Process work pool instead of subprocess. 

Most places it already was Process (e.g. CLI, type in UI, most docs).

### Checklist

- [X] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] If this pull request adds new functionality, it includes unit tests that cover the changes
- [X] This pull request includes a label categorizing the change e.g. `maintenance`, `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [ ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed.

For new functions or classes in the Python SDK:

- [ ] This pull request includes helpful docstrings.
- [ ] If a new Python file was added, this pull request contains a stub page in the Python SDK docs and an entry in `mkdocs.yml` navigation.

### CODE REVIEW

**Review by billpalombi — COMMENTED** [review]
Why standardize on "Process" instead of "Local Subprocess"? The latter is more descriptive.

**Comment by serinamarie** [comment]
I think it may need to be updated here as well: https://github.com/PrefectHQ/prefect/blob/ae9351fa30a82ecbf06f5c9a8f43b4a5740f41e9/src/prefect/workers/process.py#L145

@desertaxle can you think of anywhere else we might need to update this?

**Comment by desertaxle** [comment]
> I think it may need to be updated here as well:
> 
> https://github.com/PrefectHQ/prefect/blob/ae9351fa30a82ecbf06f5c9a8f43b4a5740f41e9/src/prefect/workers/process.py#L145
> 
> @desertaxle can you think of anywhere else we might need to update this?

Yeah, the spot you linked is the source of truth that the metadata is derived from, so changing it there will propagate to the collection registry.

**Comment by discdiver** [comment]
> Why standardize on "Process" instead of "Local Subprocess"? The latter is more descriptive.

@billpalombi - I hear them referred to much more frequently as a Process worker and Process work pool, so trying to minimize disruption by keeping that naming. Most places it is already referred to as "Process" within Prefect (see screenshots in the issue) - e.g. the type of work pool is "Process", we just display it a few places as Subprocess.

Open to revisiting, but I think it would be felt as a bigger change by users to move to Subprocess.

**Comment by discdiver** [comment]
Thank you @serinamarie and @desertaxle - updated.

**Review by billpalombi — APPROVED** [review]
@discdiver I'm sold on standardizing on Process. Thanks for bearing with me.

**Pull request merged**
