### PR TITLE
Standardize terminal input and output 

### PR DESCRIPTION
**Pull request by discdiver**
Terminal input should now be directly copy/paste-able.

Terminal output should now not have a copy button and be single-colored.

Also updates some very old terminal output.

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [ ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed

### CODE REVIEW

**Review by cicdw — CHANGES_REQUESTED** [review]
I'm not a fan of the lack of distinction between terminal commands, terminal outputs, and python scripts - at a minimum I'd expect terminal displays to be black and white.  I get moving away from the animated displays, so could you try to do some CSS styling to make that distinction, maybe by targeting the `bash` language modifier?

**Comment by discdiver** [comment]
> lack of distinction between terminal commands, terminal outputs, and python scripts - at a minimum I'd expect terminal displays to be black and white

Hmm, distinction should be present. Here's what I'm seeing. Maybe I missed a spot or don't understand what you're saying.

Screenshot from deploy preview tutorial pages showing Python code with syntax highlighting and terminal output in black and white:

Screenshot 2023-10-24 at 11 57 56 AM

And terminal command showing syntax highlighting:

Screenshot 2023-10-24 at 11 58 31 AM

**Comment by cicdw** [comment]
@discdiver it looks like you might be in some sort of dark mode - the backgrounds are all grey for me:
image

**Comment by discdiver** [comment]
Closing as hooking in with CSS looks like it would require new HTML after evaluating with Brandon.

**Pull request closed without merging**
