### PR TITLE
Made Azure ACI infra names consistent regardless of flow name length

### LINKED ISSUE #13708: Invalid names being generated for Azure Container Instance runs
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

There's something wrong with the logic in container_instance.py for workers. I can use job_variables to override the name for the azure container instances container group that should be created in Azure, using the "name" variable, but only if the name of the flow itself is over a certain character length. If it's under that character length, the "name" variable is ignored and Prefect attempts to create the Azure resource using the flow name instead. This doesn't work, since the flow name, in my case, contains invalid characters such as spaces.

I have tried this with the following two flows:
Keyvault Notification (with the name in job_variables set to "keyvault-notification" - this works
Refresh PBI (with the name in job_variables set to "refresh-pbi" - this doesn't work

If I change the name of the Refresh PBI flow to Refresh PBIWorkerTest, which is the same character length as Keyvault Notification, everything works as expected. Everything also works as expected when using agents instead of workers.

### Reproduction

```python3
Don't have an MRE at the moment, sorry.
```

### Error

```python3
The provided deployment name 'prefect-Refresh PBI-77de0178-0dc6-4c17-a1fe-3c79cb0a7528' has these invalid characters: ' '
```

### Versions

```Text
2.19.2
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bjorhn**
This simple change makes the infra naming behavior when running deployments in Azure Container Instances consistent, regardless of the flow name length.

### Example
Let's look at the names of two of my flows:

```
Keyvault Notification
Refresh PBI
```

The logic for determining how the Azure resource should be named is dependent on the length of the flow name. **Keyvault Notification** is long enough that the slugify function is called to shorten the name. This also replaces invalid characters such as spaces. The resulting name of the Azure resource is **keyvault-notificati-84fb1a09-ad59-48b3-90fc-848a564a9c43**, which Azure can handle with no issues.

**Refresh PBI** is shorter, so the slugify function is never called. This results in Prefect attempting to create the Azure resource with the name **Refresh PBI-076d0a28-b8c8-401f-b9c1-38f6dac3dfd9**, which is invalid. Azure doesn't allow spaces in resource names.

This behavior is different from how things worked in the Azure ACI Agent, resulting in a few issues being created, mostly in the old prefect-azure repo but more recently #13708. Another difference between the worker implementation and the agent is that the **name** variable on the infra/worker no longer affects the resource name, which is contrary to what the documentation says. My PR makes no attempt at fixing that problem.

With this PR in place, the slugify function is always called, regardless of flow name length. I don't see any disadvantage with having a more consistent naming behavior, and it is less confusing for users when the length of the flow name no longer affects whether the resource can even be created in Azure (assuming the user has spaces in the flow name).

When running the deployments with my fix in place, the resources created in Azure end up with the below names:

```
keyvault-notificati-84fb1a09-ad59-48b3-90fc-848a564a9c43
refresh-pbi-076d0a28-b8c8-401f-b9c1-38f6dac3dfd9
```

Closes #13708

### Checklist

- [ ] This pull request includes a label categorizing the change e.g. `maintenance`, `fix`, `feature`, `enhancement`, `docs`.
- [x] This pull request references any related issue by including "closes `<link to issue>`"
  
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ ] If this pull request adds functions or classes, it includes helpful docstrings.

### CODE REVIEW

**Comment by desertaxle** [comment]
Thanks for the PR @bjorhn! Could you please add a test ensuring that we remove spaces from resource names? That will help prevent future regression!

**Comment by bjorhn** [comment]
I'm currently crunching before going on vacation and it always takes me a while to set up a local dev environment for a Python project. I also lack experience working with unit tests in Python.. If it's a requirement to get the PR merged I can try to look into it after the summer!

**Comment by zzstoatzz** [comment]
hi @bjorhn - i can take a look at adding a test here for this, since yes this is something we should probably have a sanity check unit test for

**Comment by zzstoatzz** [comment]
@desertaxle I added a test here

**Comment by bjorhn** [comment]
Looks good! I appreciate the assistance, thank you. 👍

**Review by desertaxle — APPROVED** [review]
LGTM!

**Pull request merged**
