### PR TITLE
Always validate RRule timezone to fix tests in `test_flows.py`

### PR DESCRIPTION
**Pull request by serinamarie**
On `main` we were validating RRule schedule timezones like:
```python
 @validator("timezone", always=True)
    def valid_timezone(cls, v):
        return validate_rrule_timezone(v)
```

but currently in `v2-schemas` we do:
```python
 @field_validator("timezone")
    def valid_timezone(cls, v):
        return validate_rrule_timezone(v)
```
which will not validate all of the time. It's important to always validate because we set a `timezone` value of `None` to "UTC", unless explicitly passed in as `None`. Our tests expect a "UTC" default.

But a solution where we set default to "UTC" like this:
```python
class RRuleSchedule(PrefectBaseModel):
    ...
    timezone: Optional[str] = Field(default="UTC", examples=["America/New_York"])
```
 and don't use `validate_default=True`, would end up not validating when we construct schedules like:
```python
def construct_schedule(
    ...
    RRuleSchedule(rrule=rrule, timezone=timezone)
``` 
where timezone gets explicitly passed in as `None`. While we could just go around the codebase and fix these instances, I have a feeling that it will come up again that an rrule timezone gets explicitly passed in as `None` by us, so I think it's best to just always validate the timezone right on the model even if `None`, like we have been, where `None` gets converted to `UTC`. That way burden any of us to have to implement logic around this.

### CODE REVIEW

**Review by chrisguidry — APPROVED** [review]
This looks good, but can we also move the contents of the `validate_rrule_timezone` into the class?  It's only used in the one class.  I think we should be working to eliminate as much of that file-jumping as we can here, since this isn't shared functionality

**Comment by serinamarie** [comment]
> I thought we had a Timezone type exactly for this reason though. If we replace Optional[str] with Optional[TimeZone] or whatever I suspect that'll fix it?

I don't think I follow? Currently `to_deployment` is constructing schedules with `None` as timezone rather than `UTC`.

**Comment by serinamarie** [comment]
> This looks good, but can we also move the contents of the `validate_rrule_timezone` into the class? It's only used in the one class. I think we should be working to eliminate as much of that file-jumping as we can here, since this isn't shared functionality

@chrisguidry Makes sense, I've applied the suggestion in [04c9be9](https://github.com/PrefectHQ/prefect/pull/13556/commits/04c9be95f95002d63771cadf99922459986d37c5)

**Review by chrisguidry — APPROVED** [review]
:fire: ~Let's see if Adam's suggestion to use the `Timezone` class fixes the other issue :crossed_fingers:~ (sorry just saw the other thread)

**Comment by serinamarie** [comment]
> So Optional[TimeZone] won't fix the UTC/None default problem, but it means we don't need to run the "str" through a separate validator again since the timezone checking is done at the field level

@aaazzam I see, let me try commenting out the validator, setting `validate_default=True` and field type to `Optional[TimeZone] and see what happens.

**Review by zzstoatzz — APPROVED** [review]

**Pull request merged**
