### PR TITLE
Update Azure Container Instance guide to reflect current Azure Portal interface and Prefect UI

### PR DESCRIPTION
**Pull request by serinamarie**
This PR clarifies some information around creating an ACI Push Work Pool.

Screenshot 2023-11-27 at 3 54 07 PM

Screenshot 2023-11-27 at 3 57 42 PM

### Checklist
- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [ ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed

### CODE REVIEW

**Comment by serinamarie** [comment]
Should be in a separate PR but I noticed that "Serverless Push Work Pools" appears under "Workers and Agents". If anything maybe it should be called "Work Pools and Workers"?

**Comment by discdiver** [comment]
Thank you, @serinamarie! We could change the heading for that section from "Workers and Agents" to "Work Pools" or "Workers & Work Pools".  Will probably change when agents are deprecated.

**Comment by serinamarie** [comment]
@discdiver "Work Pools" I think would be decent in the interim as it at least is applicable to all guides in that section!

**Comment by discdiver** [comment]
PR is up: #11258

**Pull request merged**
