### PR TITLE
Adds badges to readme

### PR DESCRIPTION
**Pull request by ahuang11**
### Summary

Adds badges like 
image

There's also a contributors badge, but not sure whether or not to add 
`[Contributors](https://github.com/prefecthq/prefect/graphs/contributors)`

https://img.shields.io/github/contributors/prefecthq/prefect

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- No tests or issue needed
- [ ] A short code fix
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. One-line fixes without tests will not be accepted unless it's related to the documentation only.
- [ ] A new feature implementation
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

### CODE REVIEW

**Review by madkinsz — APPROVED** [review]
LGTM

No strong feelings on the contributors badge. @cicdw should probably sign-off.

**Comment by tpdorsey** [comment]
I'd love to see this centered under the image.

**Comment by jlowin** [comment]
The Python versions badge feels superfluous to me - badges are most interesting when they tell you a count or metric or something that changes

**Comment by ahuang11** [comment]
Thanks for the feedback! Now it looks like:
image

**Comment by discdiver** [comment]
@jlowin Re: PyPI version and Python versions, I think there is value.  They are helpful for a new user who finds themselves at the repo with little idea what Prefect is. At a glance they learn it's a Python library and that it is kept up to date to work with the most recent Python versions.  There are some popular libraries that don't work well with 3.10 and I really wish they would put that on a badge. 🙂

The PyPI label is also lets users see the most recent version number right away. It's also available under Releases, but you have to go and look for it.

My vote is to keep the PyPI and Python version badges.

**Comment by jlowin** [comment]
I agree with the pypi label — it’s a rapidly changing metric that someone might revisit this page to learn (“what is the latest version of Prefect?”)

However on the Python versions, I don’t think that’s a piece of information that deserves a place in perhaps the most highly visible part of the readme. First, it’s extremely static (once you know it, it’s highly unlikely to change) and second, it’s useful to a very small number of people (who suspect we might not be up to date) at a very specific moment (the first time they install Prefect). It’s an important piece of information, but not one I’d elevate to the first line of our readme. The installation docs are much more correlated with the person who’s interested in that information. People who are visiting our GitHub to get a sense of what Prefect is, how active it is, etc. If I send github.com/prefecthq/prefect to someone, I want them to see that activity — seeing a bunch of Python versions they probably expect we support anyway only clouds that message.

**Comment by tpdorsey** [comment]
Both viewpoints are valid to me. 

Why don't we move the Python version tags down the page to just before the "Concepts" heading, with a new line something like "Prefect currently supports the following Python versions: [tags]".

We can also put both the Python versions and PyPi badge on the installation page: /docs/getting-started/installation.md. It's fine to mingle markdown and HTML in the doc sources.

**Comment by ahuang11** [comment]
image

**Comment by ahuang11** [comment]
image

**Review by tpdorsey — APPROVED** [review]

**Review by cicdw — APPROVED** [review]

**Comment by ahuang11** [comment]
Added discourse and slack badges too
image

**Review by tpdorsey — APPROVED** [review]

**Pull request merged**
