### PR TITLE
Update integration library install instructions to show Prefect 2 and Prefect 3

### PR DESCRIPTION
**Pull request by discdiver**
Updates libraries through prefect-dask. Pausing for feedback, if there is any.

Part of  #14131

### Checklist

- [ ] This pull request includes a label categorizing the change e.g. `maintenance`, `fix`, `feature`, `enhancement`, `docs`.
- [ ] This pull request references any related issue by including "closes `<link to issue>`"
  
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ ] If this pull request adds functions or classes, it includes helpful docstrings.

### CODE REVIEW

**Comment by discdiver** [comment]
Screenshot 2024-06-20 at 2 42 59 PM

**Comment by billpalombi** [comment]
Can we make the default tab "Prefect 3" in the 3.0rc version, and "Prefect 2" in earlier versions?

**Comment by discdiver** [comment]
> Can we make the default tab "Prefect 3" in the 3.0rc version, and "Prefect 2" in earlier versions?

The integrations pages aren't tied to the Prefect versions, so there's just a single version, so no, we can't. I was thinking I'd switch it so 3 was first once we hit GA.

**Review by billpalombi — APPROVED** [review]
Ah makes sense, thanks!

**Pull request merged**
