### PR TITLE
Ensure test DB is cleared at the end of run history tests

### LINKED ISSUE #9537: Flaky test `test_read_work_queues`
### First check

- [X] I am a contributor to the Prefect codebase

### Description

```
FAILED tests/server/api/test_work_queues.py::TestReadWorkQueues::test_read_work_queues - assert 6 == 4
 +  where 6 = len([{'concurrency_limit': None, 'created': '2023-05-11T18:15:22.075775+00:00', 'description': "The work pool's default queue.", 'filter': None, ...}, {'concurrency_limit': None, 'created': '2023-05-11T18:15:27.236309+00:00', 'description': "The work pool's default queue.", 'filter': None, ...}, {'concurrency_limit': None, 'created': '2023-05-11T18:15:22.092891+00:00', 'description': '', 'filter': None, ...}, {'concurrency_limit': None, 'created': '2023-05-11T18:15:27.245702+00:00', 'description': '', 'filter': None, ...}, {'concurrency_limit': None, 'created': '2023-05-11T18:15:27.255468+00:00', 'description': '', 'filter': None, ...}, {'concurrency_limit': None, 'created': '2023-05-11T18:15:27.265768+00:00', 'description': '', 'filter': None, ...}])
 +    where [{'concurrency_limit': None, 'created': '2023-05-11T18:15:22.075775+00:00', 'description': "The work pool's default queue.", 'filter': None, ...}, {'concurrency_limit': None, 'created': '2023-05-11T18:15:27.236309+00:00', 'description': "The work pool's default queue.", 'filter': None, ...}, {'concurrency_limit': None, 'created': '2023-05-11T18:15:22.092891+00:00', 'description': '', 'filter': None, ...}, {'concurrency_limit': None, 'created': '2023-05-11T18:15:27.245702+00:00', 'description': '', 'filter': None, ...}, {'concurrency_limit': None, 'created': '2023-05-11T18:15:27.255468+00:00', 'description': '', 'filter': None, ...}, {'concurrency_limit': None, 'created': '2023-05-11T18:15:27.265768+00:00', 'description': '', 'filter': None, ...}] = <bound method Response.json of <Response [200 OK]>>()
```

e.g. https://github.com/PrefectHQ/prefect/actions/runs/4951088452/jobs/8855600243?pr=9516

### Impact

_No response_

### Additional context

_No response_

### LINKED ISSUE #9538: Flaky test `test_read_work_pools`
### First check

- [X] I am a contributor to the Prefect codebase

### Description

```
FAILED tests/server/api/test_workers.py::TestReadWorkPools::test_read_work_pools - AssertionError: assert ['A', 'B', 'C', 'test-work-pool-run-history'] == ['A', 'B', 'C']
  Left contains one more item: 'test-work-pool-run-history'
  Full diff:
  - ['A', 'B', 'C']
  + ['A', 'B', 'C', 'test-work-pool-run-history']
```

e.g. https://github.com/PrefectHQ/prefect/actions/runs/4951248005/jobs/8855973814?pr=9503

### Impact

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by desertaxle**
The test_run_history module overrides the default `clear_db` fixture so that data hangs around for all tests in the module. The data isn't cleared, which can cause bleed over into other tests that work with work queues and work pools. This PR updates the custom `clear_db` fixture to clear data in the DB after all tests in the module are complete.

Closes #9538 
Closes #9537 

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.

### CODE REVIEW

**Comment by madkinsz** [comment]
Why don't we just seed the data at the start of each test? Too slow?

**Comment by desertaxle** [comment]
> Why don't we just seed the data at the start of each test? Too slow?

Yeah, populating the data before test results in these tests taking between two and three times longer.

**Comment by desertaxle** [comment]
> Why don't we just seed the data at the start of each test? Too slow?

Yeah, populating the data before test results in these tests taking between two and three times longer.

**Review by madkinsz — APPROVED** [review]
You can test with `pytest --flake-finder` if you want too 🤷‍♀️

**Pull request merged**
