### PR TITLE
Add support for flatten() when processing results that contain no flattenable value

### PR DESCRIPTION
**Pull request by gebing**
## Summary

Add support for flatten() when processing results that contain no flattenable value.

## Checklist

This PR:

- [x] adds new tests (if appropriate)
- [x] adds a change file in the `changes/` directory (if appropriate)
- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Comment by madkinsz** [comment]
Hey @gebing, thanks for contributing! Is there an existing issue this is closing? I can follow the implementation here, but I'm not sure I fully understand the test case. Could you share a couple more cases demonstrating how this changes the behavior of `flatten`?

**Comment by gebing** [comment]
it fixed for Issue #4084, #3631, #5299, #4455, #4566, #4277.

**Comment by madkinsz** [comment]
Thanks for linking those! I see they're in the commit message too now :)

I'd appreciate if we added some more test coverage:
- The simplest flow that demonstrates the changed behavior
- Handling of non-signal exceptions

**Comment by gebing** [comment]
i already made a test case for demonstrate the behavior for flow with flatten() to process the results that contain no flattenable value in function `test_flatmap_one_unflattenable_input()` of `tests/core/test_task_map.py`, which would throw an exception before. Can you give me more specific information for what kind of test cases do you need me to add?

**Comment by bphillips-exos** [comment]
+1 on getting this merged, I ran into this issue while trying to use a mapped task as an upstream task.

**Review by cicdw — APPROVED** [review]
LGTM

**Comment by madkinsz** [comment]
I've updated this to have test coverage for:
- Tasks that raise exceptions
- Tasks that return non-iterable values that are not exceptions

I've added a warning for the second case since this would previously have resulted in a `TypeError` .

**Pull request merged**
