### PR TITLE
Fix sync_compatible typing

### LINKED ISSUE #13856: Improve DevX when serving a sync flow
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

3.x

### Describe the current behavior

When you create a sync and then add a main guard to serve that flow mypy / pylance will call out that you're not `await`ing the function. Serving the flow works just fine, but getting typing errors about async is confusing.

### Describe the proposed behavior

Users writing a sync flow and serving it shouldn't be met by async complaints.

### PR DESCRIPTION
**Pull request by abrookins**
Fix type hinting of `sync_compatible` decorated functions. Fixes #13856.

### Checklist

- [ ] This pull request includes a label categorizing the change e.g. `maintenance`, `fix`, `feature`, `enhancement`, `docs`.
- [ ] This pull request references any related issue by including "closes `<link to issue>`"
  
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ ] If this pull request adds functions or classes, it includes helpful docstrings.

### CODE REVIEW

**Comment by abrookins** [comment]
How does this look @bunchesofdonald?

**Review by bunchesofdonald — APPROVED** [review]
The squiggles are gone! You're my hero.

Screenshot 2024-06-21 at 1 25 21 PM

**Comment by abrookins** [comment]
Yeah! I'm seeing if I can improve the inferred type of return values too...

**Comment by abrookins** [comment]
I managed to fix type hinting when `sync_compatible` functions are called synchronously, at the cost of breaking hinting if the same functions are called with `await`. But because more people use sync Python than async, I'm ok with this.

It's worth noting that between PyCharm, VS Code, and mypy, only VS Code seems to have trouble with `sync_compatible` (or else my PyCharm project is broken). I couldn't find a reasonable way to change type hinting based on how a function is called. 🤷

**Pull request merged**
