### PR TITLE
Fix readme typos

### PR DESCRIPTION
**Pull request by seanpwlms**
Fix minor readme typos
### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.

### CODE REVIEW

**Review by serinamarie — APPROVED** [review]
Thanks so much!

**Review by billpalombi — APPROVED** [review]
Thank you!

**Comment by swilliams-graniterock** [comment]
@serinamarie I don't think I do, but I can request it if you prefer that.

**Comment by serinamarie** [comment]
@swilliams-graniterock, All good, it was merged!

**Pull request merged**
