### PR TITLE
allow creating autonomous task runs via `__call__`

### LINKED ISSUE #12155: Support calling autonomous tasks
In addition to calling `Task.submit` from outside of a flow, you should be able to call the task directly, the same as you can from within a flow.

### PR DESCRIPTION
**Pull request by zzstoatzz**
closes #12155

allows calling tasks outside of a flow run using `__call__`, which does not engage with the `TaskServer` or server-side websocket endpoint, rather it blocks and returns the result (or the `state` if you pass `return_state=True`)

### CODE REVIEW

**Comment by desertaxle** [comment]
Can you get the result of a task when it's called this way? I'd expect to be able to since it's like you're just calling a function.

**Comment by zzstoatzz** [comment]
> Can you get the result of a task when it's called this way? I'd expect to be able to since it's like you're just calling a function.

this is a very good point - I am thinking we should just use our minimum viable flow run context to run this in a blocking way here and return the result so that its consistent with using `__call__`, and leave `.submit` to return the future-like object

@abrookins how does this sound? i.e. `__call__` blocks and circumvents the `TaskServer` situation, `.submit` does not and gets sent up to the server to be pushed down to a subscribed `TaskServer`

**Comment by abrookins** [comment]
@zzstoatzz Yes, I agree with Alex: this should work the same way it does if you call a task from a flow, which is to block and run the function, behaving the same as a normal function call.

**Review by chrisguidry — APPROVED** [review]
I read the test first and I love it

**Pull request merged**
