### PR TITLE
Enable PREFECT_PROFILES_PATH in source files

### PR DESCRIPTION
**Pull request by GalLadislav**
This PR proposes enhancement that enables defining PREFECT_PROFILES_PATH in source files, which is going to be used for loading profiles.

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ ] If this pull request adds functions or classes, it includes helpful docstrings.

### CODE REVIEW

**Comment by GalLadislav** [comment]
First of all, GREAT JOB on the new settings! These features allowed more flexibility in Prefect configuration.

Since env files are supported now, enabling profiles path to be set in it could prove to be very useful. 

If i missed something why this is a bad idea or i should add more thorough test, please let me know.

**Comment by desertaxle** [comment]
Thanks for the PR @GalLadislav! This LGTM, but would you be willing to add reading the profiles path from `prefect.toml` and `pyproject.toml` files too? Those files could also be valid places to set the profiles path. If you have the time to add that, awesome! If not, no worries, I can merge this PR as is and add support for those files in another PR.

**Comment by GalLadislav** [comment]
@desertaxle 👍 i will gladly add those as well.

**Comment by GalLadislav** [comment]
@desertaxle ready for review

**Review by desertaxle — APPROVED** [review]
LGTM!

**Pull request merged**
