### PR TITLE
Update cloudpickle requirement

### PR DESCRIPTION
**Pull request by zdhughes**
**Thanks for contributing to Prefect!**

Please describe your work and make sure your PR:

- [x] adds new tests (if appropriate)
- [x] updates `CHANGELOG.md` (if appropriate)
- [x] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

Note that your PR will not be reviewed unless all three boxes are checked.

## What does this PR change?

This PR binds the cloudpickle version at <0.7, preventing package mismatch issues.

## Why is this PR important?

Certain items were breaking with the old range.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
I'm curious what was breaking? 

Since the test suite passed with the relaxed pinning it would be good to have a test which failed with `1.2` so we can know if/when the problem is fixed.

**Comment by cicdw** [comment]
@dhirschfeld we have some tests in other repos which track some state using the following pattern:
```python
FOO = {}

def foo_add(x): 
    FOO["x"] = x 
```
Functions like this are attached to tasks as state handlers so we can make asserts on their state transitions, etc.  However, in newer versions of `cloudpickle`, passing these sorts of functions (which reference global objects) through the serialize -> deserialize process somehow breaks the link to the global dictionary:
```python
import cloudpickle                                                                                                                                                       
func = cloudpickle.loads(cloudpickle.dumps(foo_add))                                                                                                                     

print(FOO) # {}

func(66)                                                                                                                                                                 
print(FOO) # {}

foo_add(66)                                                                                                                                                              
print(FOO) # {'x': 66}
```

**Comment by cicdw** [comment]
On second thought, we might bound `cloudpickle` in the affected repos instead of in Core so as not to affect Core's portability.  We'll try to do that real quick and close this PR if it works as expected.

**Comment by zdhughes** [comment]
Can confirm that the fix in the other affected repo works. Closing this PR now-- thanks!

**Comment by dhirschfeld** [comment]
Got a link to the other repos? If this is a regression I'd be interested in opening an issue on the [`cloudpickle`](https://github.com/cloudpipe/cloudpickle) repo so that we're not forever stuck on version `0.7` which is already 5 versions behind the latest release.

**Comment by cicdw** [comment]
The other repos are private, but I opened an issue here: https://github.com/cloudpipe/cloudpickle/issues/275 and we capped the version of `cloudpickle` in the affected repos.

We didn't merge this PR so you should be good to use any version of `cloudpickle` with prefect now 👍 

Thanks for prompting this whole revisit of our dependencies!

**Comment by dhirschfeld** [comment]
Thanks for the info! I've subscribed to the `cloudpickle` issue as I'm curious about their response...

**Pull request closed without merging**
