### PR TITLE
Block validation on deployments

### LINKED ISSUE #6487: `prefect deployment build` silently accepts wrong block types
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Deployment build silently completes but `flow-script-storage` is not an infrastructure block:

```sh
❯ prefect deployment build ./project/flow.py:my -n someflow -ib s3/flow-script-storage
Found flow 'my'
Deployment YAML created at '/Users/.../project/my-deployment.yaml'.
```

... so when the deployment's flow runs are submitted

we get an `AttributeError` in agent logs, 

`S3 object has no attribute env`

### Reproduction

```python
# create an s3 storage block `flow-script-storage`
# create a minimal flow `my`

prefect deployment build ./project/flow.py:my -n someflow -ib s3/flow-script-storage
```

### Error

not applicable, the issue is that there is no error

### Versions

```

Version:             2.1.1
API version:         0.8.0
Python version:      3.10.5
Git commit:          dc2ba222
Built:               Thu, Aug 18, 2022 10:18 AM
OS/Arch:             darwin/x86_64
Profile:             myplace
Server type:         hosted
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cicdw**
### Summary

This PR introduces block capability validation onto the client-side `Deployment` object to capture errors earlier; in doing so, this PR also refactors filesystem blocks into more granular capabilities at both the path and directory level.  This should be sufficient to support both read-only storage options as well as result configuration needs at the individual file level.

Closes #6487 

### Steps Taken to QA Changes

Wrote targeted tests.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- No tests or issue needed
- [x] A short code fix
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. One-line fixes without tests will not be accepted unless it's related to the documentation only.
- [ ] A new feature implementation
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

### CODE REVIEW

**Review by anna-geller — APPROVED** [review]
Looks great!

image

**Review by desertaxle — COMMENTED** [review]
The validators look good. I think we could bikeshed on the naming and organization of the ABCs for while, so I'll share my opinion with the caveat that it is loosely held. I think we gain flexibility by defining simple interfaces and then composing them. Kinda like this:
```python
class CanPutDirectory(Block, abc.ABC):
    _block_schema_capabilities = ["get-directory"]

    @abc.abstractmethod
    async def get_directory(
        self, from_path: str = None, local_path: str = None
    ) -> None:
        pass

class CanPutDirectory(Block, abc.ABC):
    _block_schema_capabilities = ["put-directory"]

    @abc.abstractmethod
    async def put_directory(
        self, local_path: str = None, to_path: str = None, ignore_file: str = None
    ) -> None:
        pass

class DeploymentStorage(CanPutDirectory, CanGetDirectory):
       pass
```
This arrives at the same result as the implementation in this PR, so it comes down to a matter of preference, but I thought I'd share in case it resonated.

**Review by bunchesofdonald — APPROVED** [review]

**Comment by bunchesofdonald** [comment]
> The validators look good. I think we could bikeshed on the naming and organization of the ABCs for while, so I'll share my opinion with the caveat that it is loosely held. I think we gain flexibility by defining simple interfaces and then composing them. Kinda like this:
> ...

I like this general approach, but doing a check on `_block_schema_capabilities` would be difficult, at least the way blocks are currently setup. The check would need to walk up the inheritance chain or there would have to be a metaclass or something that would collect the capabilities from the inheritance chain when initializing the class.

**Comment by desertaxle** [comment]
> I like this general approach, but doing a check on `_block_schema_capabilities` would be difficult, at least the way blocks are currently setup. The check would need to walk up the inheritance chain or there would have to be a metaclass or something that would collect the capabilities from the inheritance chain when initializing the class.

The [`Block.get_capabilities`](https://github.com/PrefectHQ/prefect/blob/74b49c72657da5e18fc00c4b1da3012b575210cd/src/prefect/blocks/core.py#L210) method gathers all the unique capabilities from the inheritance chain, so my proposed interface structure _should_ work without any changes to the current implementation of the validators in this PR, but we'd need to verify that.

**Pull request merged**
