### PR TITLE
Add sync compatibility to `run` for all infrastructure types

### PR DESCRIPTION
**Pull request by madkinsz**
This is particularly helpful for testing infrastructure, but is also relevant for the many cases in which a user may want to run commands in infrastructure from sync flows or tasks.

### Example

Previously the following would not run the process as it returned a coroutine

```python
from prefect import flow
from prefect.infrastructure import Process

@flow
def foo():
    process = Process(command=["echo", "hello!"])
    process.run()

foo()
```

### Checklist

- ~[ ] This pull request references any related issue by including "closes `<link to issue>`"~
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a `fix`, `feature`, `enhancement`, `docs`, or `maintenance` label categorizing the change.

### CODE REVIEW

**Comment by madkinsz** [comment]
It is unclear to me if this is worth adding explicit test coverage for at this time

**Review by desertaxle — APPROVED** [review]
LGTM

Having sync-compatible methods on blocks seems to be a reoccuring theme. Do you think that sync-compatibility is worth implementing automatically or enforcing for all blocks?

**Review by bunchesofdonald — APPROVED** [review]
In general, I _personally_ feel like if it's worth adding, it's worth testing. But agree that sometimes, with changes like this, it feels a little silly.

**Comment by madkinsz** [comment]
> Having sync-compatible methods on blocks seems to be a reoccuring theme. Do you think that sync-compatibility is worth implementing automatically or enforcing for all blocks?

Yeah, I think so. I considered finding some way to do that here, but decided it was out of scope.

> In general, I personally feel like if it's worth adding, it's worth testing. But agree that sometimes, with changes like this, it feels a little silly.

I think that I'd rather have an explicit check that all methods on a block are sync compatible defined in some generic block tests. Let me see if I can add some implicit coverage here though.

**Pull request merged**
