### PR TITLE
Refactor block documents queries for speed ⚡️

### PR DESCRIPTION
**Pull request by jlowin**
Closes https://github.com/PrefectHQ/nebula/issues/1492

@zangell44 noticed that block document queries are starting to take longer and longer in Prefect Cloud, even when querying for a nonexistent block document ID (see attached issue for detail, internal repo so re-summarizing here). Query complexity exploded into the hundreds of thousands, the culprit being an odd `seq scan` of the block document table, even though a block document ID was being provided.

When we looked closely, we identified that the blame lies with [this join condition](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/orion/models/block_documents.py#L148-L153):
```python
            sa.or_(
                db.BlockDocument.id == block_document_id,
                recursive_block_document_references_cte.c.parent_block_document_id.is_not(
                    None
                ),
            )
```
(note: this shows up as a where clause but is implicitly the join condition of an outer join specified immediately before)

The reason this is problematic is not the predicates, but the `OR`. In fact, both predicates should actually be instantaneous. However, many query planners opt for seq scans when evaluating `OR` conditions over multiple tables, and Postgres is no exception. This is why it was doing a seq scan even when a single, nonexistent ID was provided. 

In cases like this one, this resolution is straightforward: replace the `OR` condition with a `UNION` (or in our case, a `UNION ALL`). This lets the query planner take advantage of indexed lookups for each predicate, then trivially stitch the result together.

This change appears to work well and bring query times from hundreds of milliseconds down to the expected fraction of a millisecond. However, in implementing it I noticed that we form this query three different places: `read_block_document_by_id`, `read_block_document_by_name`, and `read_block_documents`. Therefore, I took the opportunity to refactor this code in the following ways:
- `read_block_document_by_id` and `read_block_document_by_name` are now just passthroughs to `read_block_documents`
- `read_block_documents` gains additional filter options to support those passthroughs: `block_type.slug`, `block_document.name`, and `block_document.id`.
- `read_block_documents` was making an additional DB query to load the ID's of block documents that met its filter criteria, then forming the "full" query from those materialized IDs; I refactored this so only a single DB query gets made.

Reviewed changes with @desertaxle and @zangell44 

Edit: see https://github.com/PrefectHQ/prefect/pull/6645#issuecomment-1234223411 for notes on implementation and a weird situation that prevented SQLite from being *quite* as efficient as we want (still makes two DB calls) but no longer suffers from the seq scan, so overall a big win.
### Checklist

- [x] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a `fix`, `feature`, `enhancement`, `docs`, or `maintenance` label categorizing the change.

### CODE REVIEW

**Review by madkinsz — APPROVED** [review]
Sweet!

**Review by desertaxle — APPROVED** [review]
This is fire.

Not sure why the order of block documents is different than what the tests expect. A comment says that the block documents are sorted by block type name and block document name, but I don't think that was true before these changes.

**Comment by jlowin** [comment]
:/ looking into the test failures - I'm not seeing them locally so I think they might have some phantom state from running the whole suite? I'll figure it out.

**Comment by jlowin** [comment]
@desertaxle 
> A comment says that the block documents are sorted by block type name and block document name, but I don't think that was true before these changes.

The `order by` was being applied prior to a final select which is why they were showing up in the wrong order (fixed now) -- I've also removed that comment which is no longer true (and wasn't prior to these changes)

**Review by desertaxle — APPROVED** [review]

**Pull request merged**
