### PR TITLE
Add assertion for single notification and expand notification test suite

### PR DESCRIPTION
**Pull request by madkinsz**
Guarding against behavior where notifications are dropped silently, see https://prefect-community.slack.com/archives/CL09KU1K7/p1668119051343889

### CODE REVIEW

**Comment by madkinsz** [comment]
Note for debugging of the linked user issue, this extended test suite was tested with Prefect 2.6.4 / Postgres 14.2 / Postgres 14.6 as well and passes.

**Comment by madkinsz** [comment]
@zangell44 Is there any more useful information we could dump on this failure?

**Comment by zangell44** [comment]
Nothing jumps to mind, would it be helpful for me to take a closer look at the issue?

**Comment by madkinsz** [comment]
@zangell44 let's get this merged

**Review by serinamarie — APPROVED** [review]

**Review by jakekaplan — APPROVED** [review]

**Comment by carlo-catalyst** [comment]
Hi team, anything holding up merging this?

**Pull request merged**
