### PR TITLE
Remove redundant `None` default

### PR DESCRIPTION
**Pull request by HarshCasper**
## Summary

This pull request fixes the redundant `None` default present in `src/prefect/cli/agent.py`

## Changes

- Removes redundant `None` default

## Importance

I ran a DeepSource Analysis on my fork of this repository. You can see all the issues raised by DeepSource [here](https://deepsource.io/gh/HarshCasper/prefect/).

There are plenty of other issues in relation to Bug Discovery, Performance and Anti-Patterns which you would be interested to take a look at.

If you do not want to use DeepSource to continuously analyze this repo, I'll remove the `.deepsource.toml` from this PR and you can merge the rest of the fixes. If you want to setup DeepSource for Continuous Analysis, I can help you set that up.

## Checklist

This PR:

- [X] adds new tests (if appropriate)
- [X] adds a change file in the `changes/` directory (if appropriate)
- [X] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Comment by joshmeek** [comment]
@HarshCasper I'm fine with the removal of the redundant `None` but I do not want to commit to running "DeepSource". We currently run standards such as black, mypy, and flake8 over the repo.

**Comment by HarshCasper** [comment]
@joshmeek I will remove the DeepSource Configuration then and you can merge it. Would that work ?

**Comment by joshmeek** [comment]
@HarshCasper yep 👍

**Comment by HarshCasper** [comment]
@joshmeek I have removed the DeepSource Configuration. I guess it is fit to merge this Pull Request :)

**Review by joshmeek — APPROVED** [review]

**Comment by HarshCasper** [comment]
Thanks for the first Commit @joshmeek

**Pull request merged**
