### PR TITLE
Add comments support for deployment.yaml

### PR DESCRIPTION
**Pull request by jlowin**
### Summary

Opening this as a separate PR for @cicdw evaluation. Essentially allows `deployment.yaml` to have inline help in the form of comments, that are provided as `Field(..., yaml_comment="my comment")`. For example (see work queue name):

image

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- No tests or issue needed
- [x] A short code fix
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. One-line fixes without tests will not be accepted unless it's related to the documentation only.
- [ ] A new feature implementation
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

### CODE REVIEW

**Review by cicdw — COMMENTED** [review]
I like this!!  I would really like us to move to smaller PRs so if you'd like to open this as an isolated PR I'd review 👍

**Comment by jlowin** [comment]
@cicdw this is now standalone against `main`

**Review by madkinsz — APPROVED** [review]
Test coverage for `yaml_comment` would be nice

**Comment by jlowin** [comment]
If #6343 is merged, I'll add `yaml_comment` for the work queue name field (as in the screenshot at the top of this PR) and use that as a non-contrived test

**Comment by madkinsz** [comment]
This one seems simpler to move forward, we can add the test over there?

**Comment by jlowin** [comment]
Sure

**Comment by jlowin** [comment]
For posterity: test added here [`042de3c` (#6343)](https://github.com/PrefectHQ/prefect/pull/6343/commits/042de3c430c002a5baa186cdc2378268c891b9bc)

**Pull request merged**
