### PR TITLE
Make `server database downgrade` default revision less destructive

### PR DESCRIPTION
**Pull request by collincchoy**
Running `prefect server database downgrade` without an explicit target revision defaults to "base" which basically drops the database. While there is a confirmation step here, it'd be nice if the default were less destructive in general as dropping a database is a pretty unfortunate booboo. 

Aside from safety, this new default behavior should be familiar to folks from the flask ecosystem working with tooling like flask-migrate. This default is also just a little more convenient when developing with in-flight migrations. 

### Example
```sh
# this will now downgrade to the current revision - 1. running 0-1 migrations at a time
prefect server database downgrade

# to use the previous default behavior
prefect server database downgrade -r base
```

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `maintenance`, `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [ ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed.

For new functions or classes in the Python SDK:

- [ ] This pull request includes helpful docstrings.
- [ ] If a new Python file was added, this pull request contains a stub page in the Python SDK docs and an entry in `mkdocs.yml` navigation.

### CODE REVIEW

**Review by serinamarie — COMMENTED** [review]
Somewhere out there is probably one user for whom this is a breaking change. I personally think the pros from this far outweigh the cons here.

Do you mind updating the [migration docs](https://docs.prefect.io/latest/guides/host/?h=downgrade#migrations) for this?

**Comment by serinamarie** [comment]
I'd argue this should have an `enhancement` label (or `fix`) as the `maintenance` tag is just for non-user facing changes I believe.

**Comment by abrookins** [comment]
For real. This is what I remember Django migrations feeling like, too.

**Comment by collincchoy** [comment]
> Somewhere out there is probably one user for whom this is a breaking change. I personally think the pros from this far outweigh the cons here.

Yeah I could see maybe someone has some automation script or testing setup that this might break. wrt releasing, happy to follow along w/e folks think is best here 🤷

**Comment by serinamarie** [comment]
> @serinamarie - Sure - I can add a blurb in on the defaults and how to downgrade down to 0? but before I do, I did consider updating this doc page but I felt that the docs as they read are still accurate and sufficiently succinct to get you going w/ migrations. The CLI help prompts have also been updated in this PR to reflect the new behavior. I worry that it might add unnecessary noise to the hosting docs page but I don't feel strongly about it. lmk what you think 😄
> 
> -- I do however think that as-is w/o this change, the docs _should_ have an extra cautionary blurb since it tells you to `downgrade -y`

I think it doesn't hurt to be more explicit now, even though we weren't before, especially when it includes a change. I don't think it would add a bunch of unnecessary noise when it's just mentioning functionality explicitly in this case. But it's ultimate up to you!

**Comment by serinamarie** [comment]
> > Somewhere out there is probably one user for whom this is a breaking change. I personally think the pros from this far outweigh the cons here.
> 
> Yeah I could see maybe someone has some automation script or testing setup that this might break. wrt releasing, happy to follow along w/e folks think is best here 🤷

One is not that many, mostly just mentioning for posterity.

**Review by serinamarie — APPROVED** [review]

**Comment by serinamarie** [comment]
That failing test should be removed on main if you want to pull from the `main` branch.

**Review by billpalombi — APPROVED** [review]
Approving docs changes

**Pull request merged**
