### PR TITLE
Add init to apollo/graphql deployment to reap healthcheck zombies

### PR DESCRIPTION
**Pull request by madkinsz**
## Summary

Reaps the zombies introduced by #4041 

Alternative to https://github.com/PrefectHQ/server/pull/191 which installs tini into the server images.

Per the [tini docs](https://github.com/krallin/tini#using-tini)
> NOTE: If you are using Docker 1.13 or greater, Tini is included in Docker itself. This includes all versions of Docker CE. To enable Tini, just pass the --init flag to docker run.

Simply adding the `init` flag should solve this without modifying `Server` images.

## Changes

- Adds `init: true` to apollo/graphql images

## Importance

Fixes https://github.com/PrefectHQ/prefect/issues/4114

## Checklist

This PR:

- ~[ ] adds new tests (if appropriate)~
- [x] adds a change file in the `changes/` directory (if appropriate)
- ~[ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)~

### CODE REVIEW

**Comment by jcrist** [comment]
This will work for docker-compose, but not those deploying on docker swarm or other platforms. We really should be running our containers with an init process everywhere, relying on an external tini install feels less reliable to me than just packaging it as part of our images.

**Comment by TylerWanner** [comment]
yea along @jcrist's point, I think we should include tini in the image itself, which will also provide a better k8s runtime experience, rather than doing this at the docker-compose layer

**Comment by madkinsz** [comment]
> This will work for local docker-compose, but not those deploying on docker swarm or other platforms. We really should be running our containers with an init process everywhere, relying on an external tini install feels less reliable to me than just packaging it as part of our images.

This is just such a minimal change compared to the weird github install we're forced to do on our apollo image and doesn't require a Server release to patch bug. I'm also not excited that the apollo image is broken on my development machine with the Server fix. I'm okay with either solution though, I agree having it installed in the images makes the most sense in the long run.

**Comment by madkinsz** [comment]
Closing in favor of the PR in Server -- this is a functional solution for anyone who needs a quick patch though.

**Pull request closed without merging**
