### PR TITLE
Move docker storage env declaration up

### PR DESCRIPTION
**Pull request by madkinsz**
## Summary

Moves docker storage environment variables up in the generated Dockerfile so they can be used downstream

## Importance

Allows the environment variables to be used in the commands
Closes https://github.com/PrefectHQ/prefect/issues/3640

## Checklist

This PR:

- ~[ ] adds new tests (if appropriate)~
- [x] adds a change file in the `changes/` directory (if appropriate)
- ~[ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)~

### CODE REVIEW

**Comment by madkinsz** [comment]
This is kind of blocked while I wait for a way to test this effectively although we could merge it without automated testing.

**Comment by joshmeek** [comment]
@madkinsz Also worth noting that your branch needs to be updated with master, the CI pip loop is happening which we fixed the other day 👍

**Comment by madkinsz** [comment]
@jcrist I don't think there's a great way to test this before we can actually run docker tests in CI. Thoughts?

**Comment by jcrist** [comment]
I think that's fine. The code puts the env vars in the file before the commands by inspection, any test now would be just testing the string output. You could add a test that the generated env strings are before the generated cmd strings, but I'm not sure that's necessary (and those kind of tests are generally brittle). Happy to merge with or without a string-munging test - up to you.

**Review by jcrist — APPROVED** [review]

**Pull request merged**
