### PR TITLE
Add codespell config and add to pre-commit 

### PR DESCRIPTION
**Pull request by yarikoptic**
This is pretty much a continuation of https://github.com/PrefectHQ/prefect/pull/10813#issuecomment-1732676130 to ensure that no new typo sneaks in.

### CODE REVIEW

**Comment by yarikoptic** [comment]
well -- it needs blessing (merge) or a curse (close)

**Comment by serinamarie** [comment]
Hi @yarikoptic, thanks for contributing! I don't think this will pass our pre-commit check with the misspellings in https://github.com/PrefectHQ/prefect/actions/runs/6725390065/job/18279665245?pr=10893#step:5:30.

You may also need to add `Dependant` to the list of ignored words.

**Comment by yarikoptic** [comment]
done @serinamarie -- should be all green now. But if wait is long enough, new typos would sneak in again ;)

**Comment by serinamarie** [comment]
> done @serinamarie -- should be all green now. But if wait is long enough, new typos would sneak in again ;)

Running the workflows again :) Although I think it might need to be added to our `requirements-dev.txt`?

**Comment by yarikoptic** [comment]
ah dang, forgot to report etc. Now did https://github.com/codespell-project/codespell/issues/3196 and "fixed for it" here.

**Comment by yarikoptic** [comment]
and added to requirements-devel.txt

**Comment by yarikoptic** [comment]
I also was told how to test hidden folders, so added that setting and fixed 1 more typo

**Review by serinamarie — APPROVED** [review]
Thanks @yarikoptic for your contribution :)

**Pull request merged**
