### PR TITLE
LocalFileSystem check for empty paths

### PR DESCRIPTION
**Pull request by kielnino**
This PR adds check for the paths in LocalFileSystem. So instead of checking only for `None` checks for empty strings are added.

Edit by @peytonrunyan - closes https://github.com/PrefectHQ/prefect/issues/7317
### Checklist

- [x] This pull request references any related issue by including "closes" 
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

### CODE REVIEW

**Comment by madkinsz** [comment]
@kielnino thank you! Would you mind adding a test that covers this? Let us know if you need help with that.

**Comment by kielnino** [comment]
@madkinsz Unfortunately I'm not very experienced in writing test. Can you please tell me what you have in mind? 
Do I only need to check the values of the `from_path` etc. variables, or should I test the complete copy operation like [here](https://github.com/PrefectHQ/prefect/blob/9074c1587cb0d7c2ad6dc38cece2de1b209166ca/tests/test_filesystems.py#L292)?

**Comment by james-tisato** [comment]
Is this the right fix for the problem? I thought the issue was that `from_path` and `to_path` were not being resolved relative to the `basepath`. I have done this locally and it seems to be working:

```
    async def get_directory(
        self, from_path: str = None, local_path: str = None
    ) -> None:
        ...
        if from_path is None:
            from_path = Path(self.basepath).expanduser().resolve()
        else:
            from_path = self._resolve_path(from_path)
```

and

```
    async def put_directory(
        self, local_path: str = None, to_path: str = None, ignore_file: str = None
    ) -> None:
        ...
        if to_path is None:
            to_path = Path(self.basepath).expanduser().resolve()
        else:
            to_path = self._resolve_path(to_path)
```

**Comment by madkinsz** [comment]
@james-tisato great question! I think @peytonrunyan is working on some changes like that.

I think either way we'll accept these changes / add test coverage for this case since an empty string doesn't make much sense.

**Comment by madkinsz** [comment]
@kielnino I'll try to get back to you on some testing recommendations soon!

**Comment by kielnino** [comment]
@james-tisato You are right, your fix is much more suitable.

**Comment by madkinsz** [comment]
So here is an example test added to `tests/test_filesystems.py`:

```python
    @pytest.mark.parametrize("value", {None, ""})
    async def test_get_directory_empty_local_path_uses_cwd(self, tmp_path: Path, value):
        # Construct the `from` directory
        from_path = tmp_path / "from"
        from_path.mkdir()
        (from_path / "test").touch()

        # Construct a clean working directory
        working_path = tmp_path / "working"
        working_path.mkdir()

        fs = LocalFileSystem()
        with tmpchdir(working_path):
            await fs.get_directory(from_path=str(from_path), local_path=value)

        assert (working_path / "test").exists()
```

This is _parameterized_ to cover both `None` and `""`. We'll want similar tests for
- `get_directory` with empty `from_path`
- `put_directory` with empty `to_path`
- `put_directory` with empty `local_path`

**Review by peytonrunyan — APPROVED** [review]
This looks good to me!

@kielnino I'm going to go ahead and get this merged and do a follow on PR to add tests.

Here are a couple of my favorite resources for getting comfortable with tests

ZOMBIES is a great way of conceptualizing what it is that you need to test: https://www.agilealliance.org/resources/sessions/test-driven-development-guided-by-zombies/

This playlist is a pretty good intro to pytest: https://youtube.com/playlist?list=PLL34mf651faNqwhZEM91zU3c-dcc4dLF0

**Comment by kielnino** [comment]
@peytonrunyan Sure, go ahead. Thanks for the resources, I will have a look.

**Pull request merged**
