### PR TITLE
feat(deploy/recipe): define `blob_storage` extra as requirement for Azure recipes

### LINKED ISSUE #12261: Update prefect.yaml formatter schema
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Current schema is out of date

### Describe the proposed behavior

Update @serinamarie's schema for recent prefect.yaml deployment changes at https://raw.githubusercontent.com/serinamarie/schemastore/add-prefect-dep-schema/src/schemas/json/prefect-deploy.json

### Example Use

Steps to use

1. Install a yaml extension  - I recommend [RedHat’s YAML extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) (Hit the install button on the linked page or search for it in the Extensions tab of left nav in VS Code)
2. Copy the [schema Serina made](https://raw.githubusercontent.com/serinamarie/schemastore/add-prefect-dep-schema/src/schemas/json/prefect-deploy.json) into a file with a JSON extension (I’m putting mine into prefect-deploy.json in my hidden .vscode folder )
3. Update your settings.json in VSCode with the path to the file like this:
"yaml.schemas": {
        "file:///Users/jeffhale/.vscode/prefect-deploy.json": "prefect.yaml",
You can open your settings.json from VSCode with cmd + p and type settings.json.
4. Restart VS Code

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hainenber**
Define `blob_storage` extra as requirement for Azure recipes

### Checklist

- [x] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `maintenance`, `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [ ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed.

For new functions or classes in the Python SDK:

- [ ] This pull request includes helpful docstrings.
- [ ] If a new Python file was added, this pull request contains a stub page in the Python SDK docs and an entry in `mkdocs.yml` navigation.

### CODE REVIEW

**Comment by serinamarie** [comment]
@hainenber, thanks for creating a PR! this doesn't actually resolve the linked issue, which has to do with a `prefect.yaml` formatter. I'm going to unlink that.

@desertaxle do you think you could take a look at this?

**Comment by hainenber** [comment]
I've updated the Example section to show how the formatter issue got fixed after my changes. The reproduction steps come from the issue itself

Doesnt this fix the issue at hands here, or I'm missing something?

**Comment by desertaxle** [comment]
Hey @hainenber, unfortunately, this PR doesn't resolve the linked issue. To resolve the issue, we would need to change the underlying schema. We also want to keep these recipes the same because some of the fields in recipes are filled in with user-provided values when using the recipe.

The change to use the `blob_storage` extra for the Azure recipes is a good change, and I'd accept this PR if the issue was unlinked and other modifications were removed from this PR.

**Review by desertaxle — APPROVED** [review]
Thanks!

**Pull request merged**
