### PR TITLE
Safer handling of class-based type hints with `from __future__ import annotations`

### LINKED ISSUE #11605: Making a `Flow` with parameter type hints guarded by `if TYPE_CHECKING:` fails
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

As a follow-up to #11578, when a type-hint is guarded behind an `if TYPE_CHECKING:` block, Prefect can't construct the `Flow`. It's obvious _why_ this occurs, but maybe there's something we should do here. Honestly, I can't think of any practical solution though.

### Reproduction

```python
from __future__ import annotations
from prefect import flow
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    class Test:
        pass

@flow
def foo(x: Test):
    return

assert foo
```

The above fails with a `NameError: name 'Test' is not defined`. However, do the following and it works:

```python
from __future__ import annotations
from prefect import flow

class Test:
    pass

@flow
def foo(x: Test):
    return

assert foo
```

### Error

```python
File /mnt/c/Users/asros/github/prefect/src/prefect/flows.py:1380, in flow(__fn, name, version, flow_run_name, retries, retry_delay_seconds, task_runner, description, timeout_seconds, validate_parameters, persist_result, result_storage, result_serializer, cache_result_in_memory, log_prints, on_completion, on_failure, on_cancellation, on_crashed)
   1278 """
   1279 Decorator to designate a function as a Prefect workflow.
   1280
   (...)
   1375     >>>     pass
   1376 """
   1377 if __fn:
   1378     return cast(
   1379         Flow[P, R],
-> 1380         Flow(
   1381             fn=__fn,
   1382             name=name,
   1383             version=version,
   1384             flow_run_name=flow_run_name,
   1385             task_runner=task_runner,
   1386             description=description,
   1387             timeout_seconds=timeout_seconds,
   1388             validate_parameters=validate_parameters,
   1389             retries=retries,
   1390             retry_delay_seconds=retry_delay_seconds,
   1391             persist_result=persist_result,
   1392             result_storage=result_storage,
   1393             result_serializer=result_serializer,
   1394             cache_result_in_memory=cache_result_in_memory,
   1395             log_prints=log_prints,
   1396             on_completion=on_completion,
   1397             on_failure=on_failure,
   1398             on_cancellation=on_cancellation,
   1399             on_crashed=on_crashed,
   1400         ),
   1401     )
   1402 else:
   1403     return cast(
   1404         Callable[[Callable[P, R]], Flow[P, R]],
   1405         partial(
   (...)
   1425         ),
   1426     )

File /mnt/c/Users/asros/github/prefect/src/prefect/context.py:185, in PrefectObjectRegistry.register_instances.<locals>.__register_init__(__self__, *args, **kwargs)
    183 registry = cls.get()
    184 try:
--> 185     __init__(__self__, *args, **kwargs)
    186 except Exception as exc:
    187     if not registry or not registry.capture_failures:

File /mnt/c/Users/asros/github/prefect/src/prefect/flows.py:307, in Flow.__init__(self, fn, name, version, flow_run_name, retries, retry_delay_seconds, task_runner, description, timeout_seconds, validate_parameters, persist_result, result_storage, result_serializer, cache_result_in_memory, log_prints, on_completion, on_failure, on_cancellation, on_crashed)
    297 self.retries = (
    298     retries if retries is not None else PREFECT_FLOW_DEFAULT_RETRIES.value()
    299 )
    301 self.retry_delay_seconds = (
    302     retry_delay_seconds
    303     if retry_delay_seconds is not None
    304     else PREFECT_FLOW_DEFAULT_RETRY_DELAY_SECONDS.value()
    305 )
--> 307 self.parameters = parameter_schema(self.fn)
    308 self.should_validate_parameters = validate_parameters
    310 if self.should_validate_parameters:
    311     # Try to create the validated function now so that incompatibility can be
    312     # raised at declaration time rather than at runtime
    313     # We cannot, however, store the validated function on the flow because it
    314     # is not picklable in some environments

File /mnt/c/Users/asros/github/prefect/src/prefect/utilities/callables.py:316, in parameter_schema(fn)
    301 """Given a function, generates an OpenAPI-compatible description
    302 of the function's arguments, including:
    303     - name
   (...)
    313     ParameterSchema: the argument schema
    314 """
    315 if (3, 10) <= sys.version_info < (3, 13):
--> 316     signature = inspect.signature(fn, eval_str=True)
    317 else:
    318     signature = inspect.signature(fn)

File ~/software/miniconda/envs/prefect/lib/python3.10/inspect.py:3254, in signature(obj, follow_wrapped, globals, locals, eval_str)
   3252 def signature(obj, *, follow_wrapped=True, globals=None, locals=None, eval_str=False):
   3253     """Get a signature object for the passed callable."""
-> 3254     return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
   3255                                    globals=globals, locals=locals, eval_str=eval_str)

File ~/software/miniconda/envs/prefect/lib/python3.10/inspect.py:3002, in Signature.from_callable(cls, obj, follow_wrapped, globals, locals, eval_str)
   2998 @classmethod
   2999 def from_callable(cls, obj, *,
   3000                   follow_wrapped=True, globals=None, locals=None, eval_str=False):
   3001     """Constructs Signature for the given callable object."""
-> 3002     return _signature_from_callable(obj, sigcls=cls,
   3003                                     follow_wrapper_chains=follow_wrapped,
   3004                                     globals=globals, locals=locals, eval_str=eval_str)

File ~/software/miniconda/envs/prefect/lib/python3.10/inspect.py:2463, in _signature_from_callable(obj, follow_wrapper_chains, skip_bound_arg, globals, locals, eval_str, sigcls)
   2458             return sig.replace(parameters=new_params)
   2460 if isfunction(obj) or _signature_is_functionlike(obj):
   2461     # If it's a pure Python function, or an object that is duck type
   2462     # of a Python function (Cython functions, for instance), then:
-> 2463     return _signature_from_function(sigcls, obj,
   2464                                     skip_bound_arg=skip_bound_arg,
   2465                                     globals=globals, locals=locals, eval_str=eval_str)
   2467 if _signature_is_builtin(obj):
   2468     return _signature_from_builtin(sigcls, obj,
   2469                                    skip_bound_arg=skip_bound_arg)

File ~/software/miniconda/envs/prefect/lib/python3.10/inspect.py:2307, in _signature_from_function(cls, func, skip_bound_arg, globals, locals, eval_str)
   2305 keyword_only_count = func_code.co_kwonlyargcount
   2306 keyword_only = arg_names[pos_count:pos_count + keyword_only_count]
-> 2307 annotations = get_annotations(func, globals=globals, locals=locals, eval_str=eval_str)
   2308 defaults = func.__defaults__
   2309 kwdefaults = func.__kwdefaults__

File ~/software/miniconda/envs/prefect/lib/python3.10/inspect.py:175, in get_annotations(obj, globals, locals, eval_str)
    172 if locals is None:
    173     locals = obj_locals
--> 175 return_value = {key:
    176     value if not isinstance(value, str) else eval(value, globals, locals)
    177     for key, value in ann.items() }
    178 return return_value

File ~/software/miniconda/envs/prefect/lib/python3.10/inspect.py:176, in <dictcomp>(.0)
    172 if locals is None:
    173     locals = obj_locals
    175 return_value = {key:
--> 176     value if not isinstance(value, str) else eval(value, globals, locals)
    177     for key, value in ann.items() }
    178 return return_value

File <string>:1

NameError: name 'Test' is not defined
```

### Versions

Version:             2.14.13+22.g8c71e5653b.dirty
API version:         0.8.4
Python version:      3.10.13
Git commit:          8c71e565
Built:               Wed, Jan 10, 2024 3:36 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud

### PR DESCRIPTION
**Pull request by Andrew-S-Rosen**
This is a direct follow-up to PR #11578, which closed issue #7502. This PR closes #11605. CC @chrisguidry.

When a class is behind an `if TYPE_CHECKING` block, as noted in #7502, the string cannot be evaluated, and the `Flow` can no longer be instantiated.

```python
from __future__ import annotations
from prefect import flow
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    class Test2:
        pass

@flow
def foo(x: Test2):
    return

assert foo
```

This is because there is no way for `inspection.signature(fn, eval_str=True)` to evaluate the parameter in such a case because `TYPE_CHECKING` is `False` in most real-world cases.

In hindsight, I realized it is probably just simpler to catch the exception and have the parameter be `Any`. Prefect can't find it, and Prefect won't care (at least until Python 3.13 prevents this issue altogether). I argue that this is the more sane option. 

This PR allows the above to work, provided `validate_parameters=False` is in the `@flow` decorator.

### Checklist

- [X] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [X] This pull request includes tests or only affects documentation.
- [X] This pull request includes a label categorizing the change e.g. `maintenance`, `fix`, `feature`, `enhancement`, `docs`.

For documentation changes:

- [ ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed.

For new functions or classes in the Python SDK:

- [ ] This pull request includes helpful docstrings.
- [ ] If a new Python file was added, this pull request contains a stub page in the Python SDK docs and an entry in `mkdocs.yml` navigation.

### CODE REVIEW

**Review by chrisguidry — APPROVED** [review]
Ah, great call, and I think I'm understanding this better now!

**Comment by Andrew-S-Rosen** [comment]
@chrisguidry: Great! To walk you through my logic step by step (in case it helps), I have a description below. I also ran this PR on my library of Prefect flows and everything worked beautifully. However, it's possible it's stalling again in pytest. I have it working in a Jupyter Notebook.

```python
try:
    signature = inspect.signature(fn, eval_str=True)
except (NameError, TypeError):
    signature = inspect.signature(fn)
 ```

1. If Python 3.9 is used, `eval_str` doesn't exist as a keyword argument and so a `TypeError` is raised. We then just get the regular function signature, and any classes are strings. This will be handled below.

2. If Python 3.10+ is used and the class is behind an `if TYPE_CHECKING` block, a `NameError` will be raised because `inspect` can't find the class. Like above, we get the regular function signature with the class as a string, and it will be handled below.

3. If all goes well, then hooray. We have a true class as a signature and it can be validated.

```python
try:
     create_schema(
        "CheckParameter", model_cfg=ModelConfig, **{name: (type_, field)}
        )
except (ValueError, TypeError):
    type_ = Any
````

1. If a `ValueError` is raised, things went wrong and `Any` is assigned. That was already in the codebase.

2. If a `TypeError` is raised, that means the model couldn't be created. This happens when the class is a string because the aforementioned `inspection.signature(fn, eval_str=True)` failed and so we only have the stringified function signature.

With the type as `Any`, we can happily proceed. But of course, Prefect can't actually validate the type in Case 2, so we have to set `validate_parameters=False` in the second case.

**Comment by Andrew-S-Rosen** [comment]
@chrisguidry Thanks for approving the run! Any idea about the failing test? That one is a bit cryptic to me...

**Comment by Andrew-S-Rosen** [comment]
The remaining failed test is marked flaky and indeed was flaky.

**Review by chrisguidry — APPROVED** [review]
I believe the two issues were a flaky test and then a Python 3.12 test hang that we addressed earlier today, I've rebased your change on `main` and will be monitoring.  I don't see a reason this won't make the release today.  Thanks again!

**Pull request merged**
