### PR TITLE
Parameter default value's allowed types

### PR DESCRIPTION
**Pull request by raphael-riel**
## Summary
Parameter default value must be JSON-Serializable.
I tried to pass a `Decimal` object and it failed at registration.
Type hint had mislead me 😄 

## Changes
- Strict Type hints for the default value.
- Test for Failures (Non-JSON-Serializable values) and Success (Native values)
- Adapted doc for the Arg.

## Importance
Helping developers avoid errors is crucial for adoption!
(Yet, this PR is not that important 😝  )

## Checklist

This PR:

- [x] adds new tests (if appropriate)
- [x] adds a change file in the `changes/` directory (if appropriate)
- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Comment by jcrist** [comment]
Hi @raphael-riel, thanks for the PR. The type signature update you've made looks good, but I don't think we need a test that unserializable types fail. This behavior is due to how things are implemented, but may change in the future - tests for implicit may confuse future developers IMO (is this test checking something that's important? or just incidental to an older implementation?). Would you mind reverting the test changes? Thanks!

**Comment by jcrist** [comment]
Sorry, I meant all the test changes. Proper serialization is already tested elsewhere, so these tests aren't necessary.

**Comment by raphael-riel** [comment]
@jcrist Done!

**Review by jcrist — APPROVED** [review]
Thanks!

**Comment by jcrist** [comment]
CircleCI is currently having issues, closed and reopened to hopefully retrigger.

**Comment by jcrist** [comment]
Looks like you're failing formatting checks, can you run `black` on your branch and update?

**Comment by raphael-riel** [comment]
@jcrist Done!

**Review by jcrist — APPROVED** [review]

**Pull request merged**
