### PR TITLE
Add logs for dask worker events

### PR DESCRIPTION
**Pull request by jcrist**
The `DaskExecutor` now logs worker add and remove events at the DEBUG
log level. This can be useful for debugging issues with a flow.

This PR:

- [x] adds new tests (if appropriate)
- [x] adds a change file in the `changes/` directory (if appropriate)
- [x] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Comment by jcrist** [comment]
cc @joshmeek

**Comment by joshmeek** [comment]
Love it! The tests are going to fail with black errors due to the most recent release :(

**Comment by jcrist** [comment]
> Love it! The tests are going to fail with black errors due to the most recent release :(

I'm putting up a PR to address this now

**Comment by jcrist** [comment]
I'm unable to reproduce the test failures locally. This may take a bit to debug :/.

**Comment by jcrist** [comment]
Ok, all tests are finally passing. I had to bump the distributed version to 2.15.0, but since our dask requirement is already there these really should be kept in sync anyway.

**Pull request merged**
