### PR TITLE
Fix deployment UI link

### PR DESCRIPTION
**Pull request by anticorrelator**
Fixes a broken link

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

### CODE REVIEW

**Comment by abrookins** [comment]
Hmmm -- there is something about this that I don't understand. The new URL works on Cloud, but doesn't work in the OSS UI. I.e., locally,`http://localhost:4200/deployments/deployment/b63d7e2b-260e-43df-a8f1-f59781220987` is a 404, but `http://localhost:4200/deployment/b63d7e2b-260e-43df-a8f1-f59781220987` works. We may need some advice from @zhen0.

**Comment by madkinsz** [comment]
Yeah I'm super confused about the divergence of URLs for Cloud/Orion — ideally we would not have to implement client logic to split between the two. It'd be great if we had an overview of the stable UI URLs we are supposed to use somewhere.

**Comment by khuyentran1401** [comment]
I created a PR #7236 that is related to this and encountered the same issue

**Comment by anticorrelator** [comment]
@abrookins @madkinsz @khuyentran1401 There is active work by @zhen0 to unify routes. I can branch this behavior to work for both cloud and self-hosted due to the route divergence but it'd likely require another fix to undo later. If we unify the routes by changing, won't that be a breaking API change?

**Comment by zhen0** [comment]
Pr to handle both routes is here: https://github.com/PrefectHQ/prefect/pull/7391

As @anticorrelator notes - this is only for UI links.  We discussed adding a redirect but since all routes are being updated here I think it's easier to update all together.

**Comment by anticorrelator** [comment]
@abrookins with https://github.com/PrefectHQ/prefect/pull/7391 this change should be now consistent across both cloud and the OSS UI, mind if I get a re-review?

**Review by abrookins — APPROVED** [review]
LGTM! 👍 Thanks for jumping on it!

**Pull request merged**
