### PR TITLE
Remove types in blocks docstring attributes to avoid annotation parsing error

### PR DESCRIPTION
**Pull request by john-jam**
When upgrading to prefect 2.4.1, this error is spawned multiple times when running a flow:
```
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
```
This is somehow due to the types of some attributes in blocks classes docstring. Maybe a dependency update caused this ?

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

### CODE REVIEW

**Comment by jmg-duarte** [comment]
I too hit this. Reproducible with a minimal docker image:
```docker
FROM prefecthq/prefect:2.4.1-python3.8
CMD ["prefect", "orion", "start", "--host", "0.0.0.0"]
```

**Comment by madkinsz** [comment]
@desertaxle is this from the griffe upgrade?

**Review by madkinsz — APPROVED** [review]
Thanks for contributing the fix!

**Comment by desertaxle** [comment]
> @desertaxle is this from the griffe upgrade?

It must be. I thought our warning suppression would have stopped this, but that's not the case.

**Pull request merged**
