### PR TITLE
remove stray file creation from tests

### PR DESCRIPTION
**Pull request by jakekaplan**
Remove a lot of stray files that are created during test running including `.prefectignore`, `.py` flow files and deployment `.yaml`s

### CODE REVIEW

**Review by zzstoatzz — APPROVED** [review]
💥

**Comment by abrookins** [comment]
THANK YOU! 🙏

**Review by bunchesofdonald — APPROVED** [review]
🎉

**Review by chrisguidry — APPROVED** [review]
this is the way

**Pull request merged**
