### PR TITLE
Update type of `DockerContainer.image_registry` to allow custom registry types

### PR DESCRIPTION
**Pull request by madkinsz**
### Summary

Required for https://github.com/PrefectHQ/prefect-aws/pull/68

### Steps Taken to QA Changes

Tested with ECR registry

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- No tests or issue needed
- [x] A short code fix
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. One-line fixes without tests will not be accepted unless it's related to the documentation only.
- [ ] A new feature implementation
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

### CODE REVIEW

**Comment by desertaxle** [comment]
This isn't going to work because we don't register `BaseDockerLogin` as block. This is the error that happens when you try and start Orion:
`prefect.orion.models.block_schemas.MissingBlockTypeException: Cannot create block schema because block type 'basedockerlogin' was not found.Did you forget to register the block type?`

In order to have multiple block type options for a composed block, the current supported method is to declare a union of the corresponding blocks. That may not work well since this is in the core library and `ElasticContainerRegistry` is in `prefect-aws`

**Comment by madkinsz** [comment]
Oh geez... Uh yeah a union of types definitely isn't going to work either... We should have a way to say that a block with a capability is required without enumerating all actual types.

**Review by anna-geller — APPROVED** [review]

**Comment by anna-geller** [comment]
@madkinsz code makes sense but I don't know how to run things to QA this. I can't start Orion because this block is missing server-side, but I can't register it unless I can start the Orion server. Something is missing

image

**Comment by madkinsz** [comment]
Yeah this is known to not work. This needs to be addressed as a fundamental blocks feature.

**Pull request closed without merging**
