### PR TITLE
Update assets and gitignore for SDK docs builds

### PR DESCRIPTION
**Pull request by discdiver**
Keeps stylesheets, index page, and logo around for SDK docs builds with mkdocs for v3 (temporary until Mintlify creates SDK build integration).

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ ] If this pull request adds functions or classes, it includes helpful docstrings.

### CODE REVIEW

**Comment by zzstoatzz** [comment]
@discdiver 
> Keeps stylesheets, index page, and logo around for SDK docs builds with mkdocs for v3 (temporary until Mintlify creates SDK build integration).

sorry, can you clarify why we need the `mkdocs` stuff at this point?

**Comment by discdiver** [comment]
> sorry, can you clarify why we need the `mkdocs` stuff at this point?

No problem. We need it to build the SDK docs. Until Mintly has an integration for SDK doc building, we are building the docs with Mkdocs and hosting the SDK docs on Netlify.

**Comment by zzstoatzz** [comment]
> We need it to build the SDK docs

by SDK docs do you mean like the API reference that looks at function / class signatures and docstrings ie ` mkdocstrings`? was just confused at first, bc the docs have been building recently without mkdocs 🙂

**Comment by discdiver** [comment]
Yeah, everything [here](https://prefect-python-sdk-docs.netlify.app/). This all gets built manually whenever I do it, outside of Mintlfiy.

**Review by zzstoatzz — APPROVED** [review]

**Pull request merged**
