### PR TITLE
Update Dockerfile - Decrease number of layers

### PR DESCRIPTION
**Pull request by mohitsaxenaknoldus**
As a best practice, we should have less number of layers to decrease the final image size. Commands like `RUN`, `ADD`, and `COPY` creates layers.

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

### CODE REVIEW

**Comment by madkinsz** [comment]
I worry this reduces readability — can you share the concrete advantage of reducing the layers here?

**Comment by mohitsaxenaknoldus** [comment]
> Thanks for contributing! Welcome to Prefect :)
> 
> I worry this reduces readability — can you share the concrete advantage of reducing the layers here?

This will result in a lighter final image.

**Comment by madkinsz** [comment]
Can you share some numbers for the change in image size?

**Comment by jawnsy** [comment]
Hey @mohitsaxenaknoldus, thanks so much for taking the time to make these changes and offer this pull request!

While I understand the recommendation ([Minimize the number of layers](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers) in the Dockerfile best practices document), we would prefer to explore different approaches to address these issues instead, such as squashing layers in our release builds.

Merging the build instructions as you've done here is a viable way to reduce layers, but also reduces the effectiveness of the build cache, which makes local development slower. As @madkinsz mentioned, there are also tradeoffs with respect to readability and ease of maintenance for others.

For these reasons, I do not think we will accept this pull request. Let us know if you have questions!

**Comment by mohitsaxenaknoldus** [comment]
> Hey @mohitsaxenaknoldus, thanks so much for taking the time to make these changes and offer this pull request!
> 
> While I understand the recommendation ([Minimize the number of layers](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers) in the Dockerfile best practices document), we would prefer to explore different approaches to address these issues instead, such as squashing layers in our release builds.
> 
> Merging the build instructions as you've done here is a viable way to reduce layers, but also reduces the effectiveness of the build cache, which makes local development slower. As @madkinsz mentioned, there are also tradeoffs with respect to readability and ease of maintenance for others.
> 
> For these reasons, I do not think we will accept this pull request. Let us know if you have questions!

Thanks for those points! I'll close this now. I can work with anything DevOps related like Docker, CICD, etc so let me know if there is something I can work on :)

**Pull request closed without merging**
