### PR TITLE
update docs to recommend using conda 

### PR DESCRIPTION
**Pull request by discdiver**
### Summary

Users have had difficulties upgrading with venv and pipenv in recent days. 
conda also installs the necessary sqlite version in windows environemnts.
This recommendation should reduce user difficulties.

### Checklist

This pull request is:

- [ x] A documentation / typographical error fix
	- No tests or issue needed
- [ ] A short code fix
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. One-line fixes without tests will not be accepted unless it's related to the documentation only.
- [ ] A new feature implementation
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

### CODE REVIEW

**Review by madkinsz — CHANGES_REQUESTED** [review]
I don't think we should suggest using conda quite like this. If conda is our preferred installation method, we should encourage use of the conda-forge version of Prefect rather than mixing in `pip`. Mixing dependency management tools can lead to a lot of problems.

Instead, I'd prefer to highlight using conda on Windows or specifically to resolve SQLite version issues.

Which venv and pipenv upgrade issues are you referring to? We should resolve those. We should have a rock-solid installation story on popular environment tools.

**Comment by madkinsz** [comment]
Thanks for cleaning this up. @tpdorsey / @anna-geller / @discdiver it'd still be great if ya'll could coordinate on adding a section that covers SQLite version errors and our suggested path to resolving it (basically only use conda right now).

**Comment by discdiver** [comment]
Agree @madkinsz . 

Still strange that conda won't install with conda-forge channel with miniforge on m1 (osx-arm64) - I've tried with Python 3.9 and 3.10. Verbose output not helpful. Prefect from conda-forge installs fine on an intel chip mac with miniconda.

- venv appears to still be creating issues with agents sometimes
- pipenv appears to have an issue but outside our control

Conda environment with pip appears to work on all architectures. I think we should recommend users take that route.

**Comment by madkinsz** [comment]
I've installed Prefect from conda-forge on my M1 without any issues. I haven't tested `miniforge` though, is there an issue for that?

We need to reproduce and fix the venv issue. It's the standard library environment tool.

**Pull request closed without merging**
