### PR TITLE
Adding option to return bigquery query as dataframe

### PR DESCRIPTION
**Pull request by nathaniel-md**
This commit adds support to return bigquery query results as a dataframe as well as the
default list of bigquery.table.Row results. This is sometimes useful when working with
data in bigquery in more complex ELT pipelines where python data processing is blended
with pure SQL processing.

**Thanks for contributing to Prefect!**

Please describe your work and make sure your PR:

- [ ] adds new tests (if appropriate)
- [ ] add a changelog entry in the `changes/` directory (if appropriate)
- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

Note that your PR will not be reviewed unless all three boxes are checked.

## What does this PR change?

Adds a flag to allow users to choose whether they want to return BigQuery query results as a dataframe or as the default list of `bigquery.table.Row` results.

## Why is this PR important?

Often this is useful if more processing of data is important in python which cant be accomplished in SQL.

### CODE REVIEW

**Comment by nathaniel-md** [comment]
Related to #2756

**Comment by joshmeek** [comment]
Hey @nathaniel-md this looks great! I can take a stab at the tests if you want me to, feel free to take this out of draft 🙂

**Comment by nathaniel-md** [comment]
Okay! I didn't update the `changelog` either. I would be willing to figure out how to do the testing if you give me some direction. It gave me a couple of errors and I didn't know whether I should have added a test for testing that the result actually is a dataframe. 

Thanks!

**Comment by joshmeek** [comment]
@nathaniel-md Added a couple minimal unit tests for testing the kwarg is set properly. Nothing more than that due to lack of integration tests in the task library. Also added changelog entry. Should be good to go now, will merge on passing tests 👍 thanks for the contribution!

**Pull request merged**
