### PR TITLE
Sort task run ids before returning output of cli inspect concurrency limit

### LINKED ISSUE #8754: Sort task run IDs before output, from `prefect concurrency-limit inspect ...`
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

`prefect concurrency-limit inspect [limit name]` will output a list of "Active Task Run IDs" for tasks which are currently using any of the "concurrency slots". These are UUIDs.

The list currently appears in a random order. This makes it hard to identify whether or not the list of task IDs is changing, and whether any tasks might be in a hung state.

### Describe the proposed behavior

Sort the list of task IDs alphabetically before outputting them.

### Example Use

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rito-sixt**
…urrency limit

### Checklist

- [x] This pull request references any related issue by including "closes #8754"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.

### CODE REVIEW

**Comment by rito-sixt** [comment]
This closes #8754

**Comment by madkinsz** [comment]
Hi thanks for contributing!

You've got to put that "closes ..." note in the pull request body (the first comment) or it won't link to the issue

**Comment by rito-sixt** [comment]
> Hi thanks for contributing!
> 
> You've got to put that "closes ..." note in the pull request body (the first comment) or it won't link to the issue. Please also include a before/after of the command output in the "Example" section

Hi @madkinsz! Thanks a ton for the pointers! I linked the PR to the issue.

Could you help out with a easy way to test out the CLI command? I created the concurrency-limit, but putting active task ids seems a bit trickier.
image

**Comment by rito-sixt** [comment]
I see an integration test failing, but it seems unlikely to be because of this PR! 🤔

**Comment by chrisguidry** [comment]
Thanks for your contribution, @rito-sixt!

**Comment by rito-sixt** [comment]
> Thanks for your contribution, @rito-sixt!

Thanks for the merge @chrisguidry ! Will pick up a few other issues now. 😄

**Pull request merged**
