### PR TITLE
Issue 5046 futures implementation for threading

### PR DESCRIPTION
**Pull request by jacques-**
## Summary

This is a PR that implements a futures based implementation for threading `LocalDaskExectutor` as discussed in #5046

## Changes

Swap out `multiprocessing.pool.ThreadPool` for `concurrent.futures.ThreadPoolExecutor`

## Importance

In python>=3.8 ThreadPool uses a /dev/shm ramdisk that isn't available in AWS Lambda, this fixes that.

## Checklist

This PR:

- [X] adds new tests (if appropriate)
- [X] adds a change file in the `changes/` directory (if appropriate)
- [X] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Comment by jacques-** [comment]
Looking at what's failing, it seems the biggest issue is that this futures approach doesn't work with python 3.6. I'm happy to work on a version that uses the existing multiprocessing for 3.6, and only uses the new bits for >3.6 if that is something you'd consider?

**Comment by madkinsz** [comment]
I think it may be simplest to implement it in the 3.7+ compatible way and change the base branch to the `1.0.0-rc1`, we can drop 3.6 support in the 1.0 release.

**Comment by madkinsz** [comment]
I wonder if we can take this opportunity to use a `ProcessPoolExecutor` as well to reduce the complexity of two separate pool abstractions.

**Comment by jacques-** [comment]
> I wonder if we can take this opportunity to use a `ProcessPoolExecutor` as well to reduce the complexity of two separate pool abstractions.

Haha, yes just after the PR I thought you might ask that - it does seem the sensible thing to do.

Out of curiosity, do you have a sense of when you guys are looking at a 1.0 release?

**Comment by jacques-** [comment]
Seemed easier to just make a new PR to change the base branch: https://github.com/PrefectHQ/prefect/pull/5134

**Comment by madkinsz** [comment]
> > I wonder if we can take this opportunity to use a `ProcessPoolExecutor` as well to reduce the complexity of two separate pool abstractions.
> 
> Haha, yes just after the PR I thought you might ask that - it does seem the sensible thing to do.
> 
> Out of curiosity, do you have a sense of when you guys are looking at a 1.0 release?

@jacques- I can't really commit to a timeframe :) the release candidate should be ready this month though!

**Comment by jacques-** [comment]
> > > I wonder if we can take this opportunity to use a `ProcessPoolExecutor` as well to reduce the complexity of two separate pool abstractions.
> > 
> > 
> > Haha, yes just after the PR I thought you might ask that - it does seem the sensible thing to do.
> > Out of curiosity, do you have a sense of when you guys are looking at a 1.0 release?
> 
> @jacques- I can't really commit to a timeframe :) the release candidate should be ready this month though!

oooh, ok nice - will prob need to start looking at what a migration to 1.0 looks like soon then!

**Pull request closed without merging**
