### PR TITLE
Deprecate slack webhook

### PR DESCRIPTION
**Pull request by ahuang11**
### Summary

Deprecate SlackWebhook in favor of https://github.com/PrefectHQ/prefect-slack/blob/main/prefect_slack/credentials.py#L39

### Steps Taken to QA Changes

image
```
from prefect.blocks.notifications import SlackWebhook
await SlackWebhook(url=url).notify("testing...")
```

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- No tests or issue needed
- [x] A short code fix
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. One-line fixes without tests will not be accepted unless it's related to the documentation only.
- [ ] A new feature implementation
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

### CODE REVIEW

**Comment by desertaxle** [comment]
Let's make sure we have a plan to replace `SlackWebhook` in the core library with a different default notification block. `SlackWebhook` is currently critical for the notifications feature is OSS and Cloud. A generic notification block that uses [`apprise`](https://github.com/caronc/apprise) is a promising candidate.

**Comment by ahuang11** [comment]
Cool, that reminds me of prefect-sqlalchemy, so maybe a `prefect-apprise` collection with `prefect.blocks.notification` doing `from prefect_apprise import AppriseSlackWebhook`?

**Comment by desertaxle** [comment]
> Cool, that reminds me of prefect-sqlalchemy, so maybe a `prefect-apprise` collection with `prefect.blocks.notification` doing `from prefect_apprise import AppriseSlackWebhook`?

We discussed this earlier, but posting here for visibility. I think that the `AppriseNotificaitonBlock` (or whatever we decide to call it) would live in the core library and be an analog to the `RemoteFileSystem` block where it is extremely flexible, but requires a higher level of knowledge to configure compared to the specific use case blocks that live in collections.

**Comment by desertaxle** [comment]
Closing this for now since we're still working on a plan to replace this in the core library. Will reopen when the time is right.

**Pull request closed without merging**
