### PR TITLE
Correct Flow import in schedule tutorial

### PR DESCRIPTION
**Pull request by mjpieters**
`prefect.flow()` is a function, `prefect.Flow` is a class with a `from_source` class method. The tutorial uses the latter, not the former.

### CODE REVIEW

**Comment by zzstoatzz** [comment]
hi @mjpieters - thank you for the PR!

while technically using the `Flow` class here is fine (it works), you're right that we should be using `flow` here since that's the public interface

the markdown tests are failing because of an [SSL deprecation](https://github.com/encode/httpx/releases/tag/0.28.0) unrelated to this PR - we'll take a look at that and fix asap to unblock this PR!

**Comment by mjpieters** [comment]
> while technically using the `Flow` class here is fine (it works), you're right that we should be using `flow` here since that's the public interface

You *can't* use `flow`, it doesn't have the `from_source` method. It's the public interface to create a Flow instance, yes, but it's a function and not a module or a class. There is no `prefect.flow.from_source()` and the example fails.

**Comment by mjpieters** [comment]
Hrm. Rather, type checkers don't see it that way; the `flow` type definition doesn't have a `from_source()` attribute according to pyright.

I now see that you do copy `Flow.from_source` across onto the `flow.from_source` attribute but function attributes don't make it into the type.

You'd have to add a `if TYPE_CHECKING:` version of `flow` that uses a `typing.Protocol` class to make that possible. I'll see if I can't wrangle that today.

**Comment by mjpieters** [comment]
On second thought: I would first have to determine how serious prefect is about maintaining quality type annotations. I'm not sure that the project does at this point:

- I can't find any tests that check the type annotations.
- The SDK doesn't pass a type completeness check; specifically, there is a lot of places where generic types are being used without providing arguments.

E.g. `pyright --verifytypes prefect` ends with:

```
Symbols exported by "prefect": 13211
  With known type: 7939
  With ambiguous type: 293
  With unknown type: 4979

Other symbols referenced but not exported by "prefect": 11307
  With known type: 8370
  With ambiguous type: 708
  With unknown type: 2229

Symbols without documentation:
  Functions without docstring: 3262
  Functions without default param: 53
  Classes without docstring: 788

Type completeness score: 60.1%
```

Fixing `flow.from_source()` feels like the tip of a veritable iceberg at this point.

**Pull request closed without merging**
