### PR TITLE
Remove deprecated ability to run `prefect deploy` with `deployment.yaml` file

### PR DESCRIPTION
**Pull request by serinamarie**
Use of `deployment.yaml` in `prefect deploy` for flow deployment was deprecated in June 2023. This PR removes that functionality and the corresponding tests.

### CODE REVIEW

**Review by bunchesofdonald — APPROVED** [review]
Nothing I love more than a red PR!

**Review by zzstoatzz — APPROVED** [review]

**Comment by digitalghost-dev** [comment]
I’ve gotten so used to using the `deploy` command! I’ll have unlearn it.

**Comment by serinamarie** [comment]
@digitalghost-dev the `deploy` command isn't deprecated, it's just using the `deployment.yaml` that is removed in favor of `prefect.yaml`

**Comment by digitalghost-dev** [comment]
Oh okay, thanks for clarifying. I'll have to read up on the docs for these changes.

**Comment by serinamarie** [comment]
@digitalghost-dev if you use a `prefect.yaml` already there shouldn't be any changes. If you're using the `deployment.yaml`, you should have been receiving a deprecation message since last June when running `prefect deploy`, which will convert it for you.
Screenshot 2024-04-18 at 5 33 54 PM

**Pull request merged**
