### PR TITLE
Docs: Move detailed installation instructions into `Tutorial` section

### PR DESCRIPTION
**Pull request by serinamarie**
Tutorial section of the docs begins with writing a flow without mentioning installation:
https://docs.prefect.io/latest/tutorial/first-steps/

This PR moves the `Installation` page into the `Tutorial` section. It isn't needed prior to `Cloud Quickstart` page as that shows how to install Prefect and links to detailed installation instructions.

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.

### CODE REVIEW

**Review by discdiver — CHANGES_REQUESTED** [review]
I think there should be a redirect in netlify.toml, too - as external sites likely point to the install instructions.

**Review by discdiver — DISMISSED** [review]
lgtm

**Comment by billpalombi** [comment]
I'm curious, what's the motivation for moving installation into the tutorial? The [tutorial overview](https://docs.prefect.io/latest/tutorial/) includes:

> Before you start, install Prefect

Installation is in the getting started section of:
- pandas
- awscli
- requests "quickstart"

**Review by discdiver — COMMENTED** [review]
Thinking more about @billpalombi's question/comment below makes me think keeping the install section in getting started is probably a convention worth continuing to follow.

**Comment by serinamarie** [comment]
> I'm curious, what's the motivation for moving installation into the tutorial? The [tutorial overview](https://docs.prefect.io/latest/tutorial/) includes:

I think I see what is confusing now. I didn't even see the Tutorial overview page. I've made a 20 second video to demonstrate, and included in the summary some issues I see.

https://www.loom.com/share/881bb09f63e745799ab41b0c6178a916

**Comment by billpalombi** [comment]
1. You're right, I've created [an issue](https://github.com/PrefectHQ/prefect/issues/9725)
2. We should also make "Getting Started" link to that page. I've created [another issue](https://github.com/PrefectHQ/prefect/issues/9727)

@discdiver, I'm not sure how to update those links. Do you know how to do that?

**Comment by discdiver** [comment]
Apologies. I believe problems 1 and 2 above were caused by an mkdocs bug. We were pinning to the buggy version to avoid another bug that wouldn't let the docs build. The original bug has been resolved and the pin has been removed in #9501. 

I've closed both of the issues.

We could make the tutorial overview explicit. I have some ideas there. Let's discuss elsewhere and make a new issue if warranted.

**Comment by billpalombi** [comment]
Thank you Jeff!

**Comment by serinamarie** [comment]
> Apologies. I believe problems 1 and 2 above were caused by an mkdocs bug. We were pinning to the buggy version to avoid another bug that wouldn't let the docs build. The original bug has been resolved and the pin has been removed in #9501.
> 
> I've closed both of the issues.
> 
> We could make the tutorial overview explicit. I have some ideas there. Let's discuss elsewhere and make a new issue if warranted.

Ah, yes, I see your thread! I'll close this. Thanks so much @billpalombi an @discdiver

**Pull request closed without merging**
