### PR TITLE
Add `prefect-openai` to Collections catalog

### PR DESCRIPTION
**Pull request by ahuang11**
### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

### CODE REVIEW

**Review by desertaxle — APPROVED** [review]
LGTM!

**Comment by tpdorsey** [comment]
Did we check the logo in dark mode?

**Review by tpdorsey — APPROVED** [review]
Dark mode looks okay! Thanks

**Comment by ahuang11** [comment]
image

**Pull request merged**
