### PR TITLE
Fix handling of Dask DataFrame and other Awaitables passed to `run_coro_as_sync`

### PR DESCRIPTION
**Pull request by kzvezdarov**
Call sites of [`run_coro_as_sync`](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/utilities/asyncutils.py#L182-L248) test objects for being `Awaitable` rather than `Coroutine`, before calling the function.  This raises an error in cases that the object passed is just an `Awaitable` because [asyncio.Task](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task) specifically requires a `Coroutine`. For example, see: https://github.com/PrefectHQ/prefect/issues/15665. - `dask.dataframe.DataFrame` is an `Awaitable` but not `Coroutine`, which breaks `prefect_dask` flows.

This PR changes all pre-`run_coro_as_sync` tests to use `asyncio.iscoroutine` rather than `inspect.isawaitable` in order
to match the expectations of the `asyncio.Task` constructor here: https://github.com/python/cpython/blob/3.13/Lib/asyncio/tasks.py#L104

The `inspect` module also has an `iscoroutine` function which is implemented slightly differently from `asyncio.iscoroutine`. Both seem to function identically in this case, but in order to match the expectations of `asyncio.Task` I've picked the `asyncio` version and changed all existing invocations of `inspect.iscoroutine` to `asyncio.iscoroutine` for consistency. 

Closes https://github.com/PrefectHQ/prefect/issues/15665 and https://github.com/PrefectHQ/prefect/issues/15633

### Checklist

- [x] This pull request references any related issue by including "closes `<link to issue>`"
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ ] If this pull request adds functions or classes, it includes helpful docstrings.

### CODE REVIEW

**Comment by desertaxle** [comment]
Thanks for the PR @kzvezdarov! I think changes in the internal concurrency module are causing failures. Could you try reverting those changes and see if that fixes the test failures?

**Comment by kzvezdarov** [comment]
> Thanks for the PR @kzvezdarov! I think changes in the internal concurrency module are causing failures. Could you try reverting those changes and see if that fixes the test failures?

Yup, I had misunderstood the calls from `_run_sync` to `_run_async`, sorry about that; I've also reverted other instances where the conditional was guarding simply `await` points, keeping the `iscoroutine` check only for sites that were already doing that and for `run_coro_as_sync` calls.

**Comment by kzvezdarov** [comment]
@desertaxle The tests seem to finally be fixed. I've added a new test case for `prefect-dask` which uses dataframes; this required plugging in `dask[dataframe]` as a dev dependency - hope that's ok.

**Review by desertaxle — APPROVED** [review]
Thank you!

**Pull request merged**
