### PR TITLE
Add script to generate release notes with simple processing

### PR DESCRIPTION
**Pull request by madkinsz**
First-pass at generating release notes via GitHub's API with common updates automated. See https://docs.github.com/en/rest/releases/releases#generate-release-notes-content-for-a-release

This is particularly useful for previewing changes _before_ a release without drafting it in the GitHub UI.

This action requires a GitHub PAT which I currently pull from the `gh` CLI tool or the `GITHUB_TOKEN` environment variable.

### Example

```
$ ./scripts/generate-release-notes.py "2.3.0"
```

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [x] This pull request includes a `fix`, `feature`, `enhancement`, `docs`, or `maintenance` label categorizing the change.

### CODE REVIEW

**Comment by madkinsz** [comment]
I do not think it's worth writing tests that mock the Github API since this is for internal manual use.

**Comment by madkinsz** [comment]
In the future, if we wanted, we could fully automate this process and auto-generate the notes in CI and create a GH Release when a tag is pushed.

**Review by bunchesofdonald — APPROVED** [review]
This looks awesome!

**Comment by madkinsz** [comment]
Thanks!

**Pull request merged**
