### PR TITLE
Refactor lazy imports to avoid accidental eager imports

### PR DESCRIPTION
**Pull request by abrookins**
This work is part of our effort to speed up CLI commands. The `lazy_import` function inadvertently imported _more things_ when you called it, particularly a bunch of Docker and Kubernetes packages. The problem was the function's call to `inspect.stack()`, which was only necessary to produce a detailed error message. I tightened the error message to remove the need to call `inspect.stack()`.

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] If this pull request adds new functionality, it includes unit tests that cover the changes
- [x] This pull request includes a label categorizing the change e.g. `maintenance`, `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [ ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed.

For new functions or classes in the Python SDK:

- [ ] This pull request includes helpful docstrings.
- [ ] If a new Python file was added, this pull request contains a stub page in the Python SDK docs and an entry in `mkdocs.yml` navigation.

### CODE REVIEW

**Comment by abrookins** [comment]
Tests are currently failing due to an upstream change in the apprise library that we're working to fix.

**Review by chrisguidry — APPROVED** [review]
Super interesting, what mechanism caused the additional imports to happen?

**Comment by abrookins** [comment]
@chrisguidry I haven't had time to dig into this yet, but it was `inspect.stack()[1]`.

**Comment by abrookins** [comment]
The problem is that using `inspect` would evaluate imports at the frame above the current frame, which would end up eagerly importing kubernetes.

**Pull request merged**
