### PR TITLE
bubble up hydration placeholders

### PR DESCRIPTION
**Pull request by jakekaplan**
Awhile ago we added support for nested hydration of `__prefect_kind` objects as parameters. 

In some cases (like in actions) we'll hydrate without actually rending everything since we don't yet have the full context. Any `Placeholder`s we generate should count as "valid" values and just continue to bubble up the chain.

This should enable us to do things like convert an event body into an object instead of passing it as a string:
e.x.
```
# `d` resolves as a string, since jinja can only return strings
trigger = DeploymentEventTrigger(  # type: ignore
    expect={"whatever.happened"},
    parameters={
        "d":  "{{ event.payload.body }}"
   }
)

# `d` resolves as an object
trigger = DeploymentEventTrigger(  # type: ignore
    expect={"whatever.happened"},
    parameters={
        "d": {
            "__prefect_kind": "json",
            "value": {
                "__prefect_kind": "jinja",
                "template": "{{ event.payload.body | tojson }}",
            },
        }
    },
)
```

This UX is maybe not ideal for passing information through to be converted into objects, however this should work today and gives us a basis to build further on it.

### CODE REVIEW

**Review by zzstoatzz — APPROVED** [review]
🫧 

related to #14875

**Review by cicdw — APPROVED** [review]
yup agree this should eventually evolve into a user facing interface, but LGTM as the foundation

**Comment by DataOps7** [comment]
This was a major time consumer for us when setting up a deployment automation,
We need to have a better developer facing interface for templating JSON parameters!

**Comment by DataOps7** [comment]
On it!

**Comment by KnightArthurRen** [comment]
Hi lads sorry to dig up an old pr. Do you guys think we can put @jakekaplan's example above in the automation doc page? (I'd happy to submit a pr for that) . Or should we wait for a more ui friendly implementation first? Reasoning is I spent days trying to pass a complex object from automation and I just stumbled in this pr by luck. Since prefect have such a powerful feature now should we publicize it?

**Comment by jakekaplan** [comment]
@KnightArthurRen sorry to hear that! Glad at least this solution is what you were looking for. If you're willing to submit a PR to add this to the docs it'd be much appreciated. Definitely can make it more easily findable info as there still isn't a more friendly dev ex atm.

**Comment by KnightArthurRen** [comment]
@jakekaplan thank you for implementing this! I'll make a PR to update the doc

**Pull request merged**
