### PR TITLE
Support for Docker volumes and list filtering

### PR DESCRIPTION
**Pull request by sk4la**
## What does this PR change?

At the moment, only a subset of the Docker API is supported by Prefect's [Docker tasks](https://github.com/PrefectHQ/prefect/tree/master/src/prefect/tasks/docker).

Nothing too fancy, I simply added some code to the current tasks (respectively `CreateContainer`, `ListContainers` and `ListImages`) in order to allow the following optional arguments when calling the `run` method:

* `volumes` ;
* `filters`.

I invite you to refer to the [documentation](https://docker-py.readthedocs.io/en/stable/index.html) in case you're not familiar with Docker-related concepts.

## Why is this PR important?

I plan to use Prefect at my workplace to manage Docker-based ETL jobs (heavily relying on disk I/O), but the lack of support for Docker volumes and list filtering is sadly a no-go.

### CODE REVIEW

**Comment by joshmeek** [comment]
Thanks for the PR @sk4la! Couple things:
- Could you move the changelog update to the task library section and add yourself to the contributors section?
- Looks like there is one failing test:

```
____________ ERROR collecting tests/tasks/docker/test_containers.py ____________
/usr/local/lib/python3.7/site-packages/_pytest/python.py:513: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/local/lib/python3.7/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:967: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:677: in _load_unlocked
    ???
/usr/local/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:143: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
/usr/local/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:328: in _rewrite_test
    tree = ast.parse(source, filename=fn)
/usr/local/lib/python3.7/ast.py:35: in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
E     File "/root/project/tests/tasks/docker/test_containers.py", line 71
E       name="test",
E          ^
E   SyntaxError: invalid syntax
```

**Comment by sk4la** [comment]
Hi @joshmeek, sorry for this, should be fixed now.

**Comment by joshmeek** [comment]
@sk4la not a problem! Looks like one more thing is failing due to formatting, try running `black .` in the root prefect directory to auto format the files 😄

**Comment by sk4la** [comment]
There you go!

**Pull request merged**
