### PR TITLE
Multi output docker

### PR DESCRIPTION
**Pull request by cjmartian**
## Changes

Converts docker build from circleci to GHA
Makes the Dockerfile multi-output

## Importance

Requested in https://github.com/PrefectHQ/prefect/issues/5388

## Checklist

This PR:

- [X] adds new tests (if appropriate)
- [x] adds a change file in the `changes/` directory (if appropriate)
- [X] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Comment by cjmartian** [comment]
@madkinsz  Circle would need to be cleaned up, didn't do that just yet as I'm not sure everyone would be happy migrating to GHA.

**Comment by madkinsz** [comment]
Hey! Just want to respond since I hadn't gotten to this yet.

We're interested in supporting multi-output docker builds, but it'll involve a bit of work on our end. If switching to GH Actions, we'll need to take the time to ensure all the previous tags are created each builds, transfer secrets, and do security audits. We're using GH Actions for Orion, so this is a reasonable approach, but it'll be a bit before we can prioritize it. Thanks for taking the time to contribute though, this implementation will be helpful!

**Comment by cjmartian** [comment]
Hey @madkinsz 

Sorry I just saw this. That's good to hear. There's no rush on my end to get this one in. I just wanted to open a PR just to see if the approach was something you all might be interested in and it sounds like it is. 🎊 

If I can do anything on my end with this PR, just let me know. I'd be happy to help as much as I can. 

Cheers

**Comment by ddelange** [comment]
> Converts docker build from circleci to GHA

Should image building (or only pushing) be disabled on circleci?

**Comment by madkinsz** [comment]
I'm going to close this as it's on our roadmap and will be implemented by our engineering team. We are very likely to follow the GHA approach and reuse our CI setup from v2.

Appreciate your understanding cjmartian!

**Comment by cjmartian** [comment]
@madkinsz Anytime! Happy to help out however I can. Thanks for the update

**Pull request closed without merging**
