### PR TITLE
Add extra entrypoints setting for user module injection

### PR DESCRIPTION
**Pull request by madkinsz**
A potential fix for https://github.com/PrefectHQ/prefect/issues/7177

Uses a mechanism similar to our collections loading to allow users to define a list of modules to load on Prefect import via a setting.

### Example

Specifying a module that cannot be loaded
```
❯ PREFECT_EXTRA_ENTRYPOINTS=foo python -c "import prefect"
Warning! Failed to load extra entrypoint 'foo': ModuleNotFoundError: No module named 'foo'
```

Define `foo.py`
```python
print("Hi from foo!")

def test():
   print("Hi from a method in foo!")
```

Specifying a module loads it
```
❯ PREFECT_EXTRA_ENTRYPOINTS=foo python -c "import prefect"
Hi from foo!
```

Specifying a callable for contained side-effects
```
❯ PREFECT_EXTRA_ENTRYPOINTS=foo:test python -c "import prefect"
Hi from foo!
Hi from a method in foo!
```

### Checklist

- [x] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

### CODE REVIEW

**Comment by cicdw** [comment]
@madkinsz your issue link links back to this PR

**Comment by madkinsz** [comment]
@cicdw Thanks! Updated to https://github.com/PrefectHQ/prefect/issues/7177 :)

**Review by chrisguidry — COMMENTED** [review]
I like it!  And yes, this will be "fun" to test :D

**Comment by madkinsz** [comment]
@chrisguidry not so bad!

**Review by chrisguidry — APPROVED** [review]
Nice!!

**Pull request merged**
