### PR TITLE
Update benchmarks.yaml fix security vulnerability

### PR DESCRIPTION
**Pull request by h2oa**
See the details of this vulnerability at https://huntr.com/bounties/58ef02f2-31cc-488d-a55f-84ab309aa2b2 (private link)

### CODE REVIEW

**Comment by zzstoatzz** [comment]
hi @h2oa - thanks for the PR!

can you share a public link to the details of this vulnerability?

**Comment by h2oa** [comment]
Hi @zzstoatzz , I think your program is registered to run bug bounty at huntr.com. Because I am not the admin in this platform, I am a researcher, so I can not add people to the report. 

image

You should ask the person who directly manages reports sent through the huntr.com platform.

**Review by bunchesofdonald — APPROVED** [review]
Thank you so much @h2oa!

**Comment by h2oa** [comment]
Hi @bunchesofdonald , can you connect admin of platform huntr.com and triaged my report at https://huntr.com/bounties/58ef02f2-31cc-488d-a55f-84ab309aa2b2? This will make my report valid and I will also receive a reward for my efforts to find the vulnerability. Thank you!

**Pull request merged**
