### PR TITLE
typo fix propogate -> propagate

### PR DESCRIPTION
**Pull request by bmizhen**
propogate -> propagate

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Review by tpdorsey — APPROVED** [review]
Thank you!

**Comment by bmizhen** [comment]
Hey @tpdorsey I am not sure why but "Merging is blocked" and "1 workflow awaiting approval
First-time contributors need a maintainer to approve running workflows" 
Who should I ask?
Thanks!

**Comment by tpdorsey** [comment]
I've approved, but it needs to be merged by a maintainer. Nothing to do for now, it just needs to bubble up the queue. Thanks for the contribution!

**Review by madkinsz — APPROVED** [review]
Thanks!

**Pull request merged**
