### PR TITLE
Feature sendgrid notification

### PR DESCRIPTION
**Pull request by Ishankoradia**
This PR adds a new notification block. It integrates with the sendgrid email API. 

### Example

Create notifications will now have a new block called `Sendgrid email`. User will be able to add their sendgrid api key, sender email and recipients to trigger email on selected/all flow run statuses and tags.

### Checklist

- [x] This pull request references any related issue by including "[closes]  (https://github.com/PrefectHQ/prefect/issues/10119)"
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [ ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed

### CODE REVIEW

**Review by desertaxle — DISMISSED** [review]
Thanks for the PR @Ishankoradia! For notification blocks we lean on `apprise` to avoid introducing new dependencies. You can see an example of adding a `NotificationBlock` in [this PR](https://github.com/PrefectHQ/prefect/pull/8341). We will also need some tests covering this new functionality which you can also see an example of in the PR I linked.

**Comment by Ishankoradia** [comment]
@desertaxle understood. I will make the required changes. Will also add test cases. Thank you for the help.

**Comment by Ishankoradia** [comment]
@desertaxle i have made the changes you asked and also added test cases. Please let me know if there are any more changes.

**Review by bunchesofdonald — APPROVED** [review]
This looks great to me. Thanks for updating the code and the tests!

**Review by bunchesofdonald — CHANGES_REQUESTED** [review]
Hey @Ishankoradia, could you look at the test failures here and fix them up?

**Comment by Ishankoradia** [comment]
> Hey @Ishankoradia, could you look at the test failures here and fix them up?

Yes sure. On it.

**Comment by Ishankoradia** [comment]
Thanks for the quick response. @bunchesofdonald 

The checks ask for  a `_logo_url`. Do i need to need to host this logo image somewhere ?

**Comment by bunchesofdonald** [comment]
You can use https://images.ctfassets.net/gm98wzqotmnx/3PcxFuO9XUqs7wU9MiUBMg/af6affa646899cc1712d14b7fc4c0f1f/email__1_.png?h=250

**Comment by Ishankoradia** [comment]
> You can use https://images.ctfassets.net/gm98wzqotmnx/3PcxFuO9XUqs7wU9MiUBMg/af6affa646899cc1712d14b7fc4c0f1f/email__1_.png?h=250

Thank you. I have added the logo url. Can you run the CI here one last time ? @bunchesofdonald

**Review by bunchesofdonald — APPROVED** [review]
This looks great, thanks for sticking through the multiple rounds of review @Ishankoradia!

**Comment by Ishankoradia** [comment]
> This looks great, thanks for sticking through the multiple rounds of review @Ishankoradia!

Thanks for the review and speeding it up. Really appreciate it.

**Comment by bunchesofdonald** [comment]
@Ishankoradia Yep, we do a release every Thursday, so this should be included in the release that happens on July 13th.

**Pull request merged**
