### PR TITLE
Revert back to using relative paths in generated Dockerfile on Windows

### PR DESCRIPTION
**Pull request by pravindahal**
- [x] adds new tests (if appropriate)
- [x] add a changelog entry in the `changes/` directory (if appropriate)
- [x] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

## What does this PR change?
https://github.com/PrefectHQ/prefect/pull/2390 introduced a change so that on Windows, Dockerfile contained absolute paths which prevents docker build from working when using wsl backend or ssh (see https://github.com/PrefectHQ/prefect/issues/3023).

The fix here is to use relative paths in Dockerfile (i.e. revert to behavior before https://github.com/PrefectHQ/prefect/pull/2390) but pass absolute path of Dockerfile to `client.build`.

For previous attempt at addressing this problem, see the discussion here: https://github.com/PrefectHQ/prefect/pull/3035

### CODE REVIEW

**Comment by joshmeek** [comment]
Thanks for the PR @pravindahal! While the code _appears_ fine I don't have a windows environment to give this a test just yet so maybe someone can verify?

**Comment by lauralorenz** [comment]
Hi @pravindahal @joshmeek for what it's worth, I just tried out the test case back from https://github.com/PrefectHQ/prefect/issues/2332 but using this branch on regular Windows 10 AND MacOS and had no issues, so since @pravindahal can confirm it works for wsl/ssh I think we are good.

**Comment by lauralorenz** [comment]
also cc'ing @thomasfrederikhoeck in case they want to check

**Comment by thomasfrederikhoeck** [comment]
@lauralorenz I will check it within a couple of hours

**Comment by thomasfrederikhoeck** [comment]
LGTM 👍

**Pull request merged**
