### PR TITLE
[Feature] --tail option added the prefect flow-run logs CLI #7999

### PR DESCRIPTION
**Pull request by Shubhamparashar**
Closes https://github.com/PrefectHQ/prefect/issues/7999

Added an option to see the last N logs for a flow run 

### Example

prefect flow-run logs <flow_run_id> --tail 20

it will show last 20 logs for flow_run_id

### Checklist

- [x] This pull request references any related issue by including closes
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.

### CODE REVIEW

**Review by madkinsz — COMMENTED** [review]
Thanks for contributing and welcome to the community!

I'm curious about this implementation. I was imagining just getting the last N logs using the sort-order we use for `--reverse` then displaying them in the right order to the user. What do you think about that? It's one less API call but it won't support pagination well.

We'll need to make sure we can add the `logs/count` route to Prefect Cloud in a performant way before we can accept the current implementation.

**Comment by Shubhamparashar** [comment]
Hi @madkinsz ,

Yes, That was my first approach but I thought that if we are fetching a large number of logs first we are sorting it in DB then we will be reversing them and also the pagination, and compare to that counting logs seems cheaper to me. But I don't know the actual indexing.

And it's my first open-source contribution, so if you have any other feedback or advice, they are most welcome.

**Comment by madkinsz** [comment]
@Shubhamparashar that makes sense to me! If you're interested in poking around at the database layer, all of the migrations are in this repository and we can add an index for SQLite / Postgres to improve the efficiency of the count query if it is not sufficient. We'll also have one of our engineers that works on Cloud take a look at the performance implications.

**Comment by Shubhamparashar** [comment]
@madkinsz sure I will check out the migration to get more insight on this and add the tests for the CLI changes.

**Comment by zangell44** [comment]
Thanks for contributing @Shubhamparashar!

> Yes, That was my first approach but I thought that if we are fetching a large number of logs first we are sorting it in DB then we will be reversing them and also the pagination, and compare to that counting logs seems cheaper to me. But I don't know the actual indexing.

Love that you're thinking about performance in detail!
As it turns out, our logs table is indexed to make querying the last N logs by timestamp a fast query. (And if heavy use reveals I'm wrong, we can always add the appropriate index!)
For cases where many logs match the filter criteria, counting all logs first will definitely be more expensive to do.

For this PR, I would use the reverse sort order instead of adding a new `/count` route.

--
For even faster performance when using Cloud in the future, we could use the `events` websocket endpoint. I would recommend doing that in a subsequent PR.

**Comment by Shubhamparashar** [comment]
@zangell44 sure I will do it using the reverse sort on timestamp

**Comment by Shubhamparashar** [comment]
@zangell44 @madkinsz I created a new PR for tail functionality added using reverse and offset
here is the link for the same - https://github.com/PrefectHQ/prefect/pull/9028

**Pull request closed without merging**
