### PR TITLE
SecretDict is not JSONSerializable in Deployment

### PR DESCRIPTION
**Pull request by ahuang11**
User reports that: `prefect deployment build sky-pipe/flows/test_flow.py:test_flow -n testaroo -q sky-pipe --skip-upload -a -ib "cloud-run-job/test"` does not work in prefect_gcp==0.2.2, a version that introduces `SecretDict` inside `GcpCredentials`.

However, during my testing, I found this works, with plain blocks.
```
from prefect_gcp import GcpCredentials
from prefect_gcp.cloud_run import CloudRunJob
job = CloudRunJob(image="myimage", region="region", credentials=GcpCredentials.load("gcp-credentials"))
job.json()
```

The reason it works with blocks is because `Block` class has special handling; it does not work in a `Deployment` because `Deployment` inherits from `BaseModel` and not `Block`,  
```
    class Config:
        extra = "allow"

        json_encoders = {SecretDict: lambda v: v.dict()}
```
So this PR copies over the Config to Deployment to make it work.

Closes https://github.com/PrefectHQ/prefect-gcp/issues/102

### Example

```python
from prefect.blocks.fields import SecretDict
from prefect_gcp.cloud_run import CloudRunJob, GcpCredentials
from prefect.deployments import Deployment

creds = GcpCredentials.load("gcp-credentials")  # must set service_account_info
crj = CloudRunJob(credentials=creds, image="abc", region="abc")
Deployment(name="abc", infrastructure=crj).to_yaml("my.yaml")
```

### Checklist

- [x] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

### CODE REVIEW

**Comment by madkinsz** [comment]
I'm confused — Pydantic does not use nested encoder settings when serializing objects?

**Comment by ahuang11** [comment]
> I'm confused — Pydantic does not use nested encoder settings when serializing objects?

Yes that seems to be the case :/

**Comment by madkinsz** [comment]
Can you write a little MRE demonstrating that and look into opening a bug upstream? That seems like less than ideal behavior. I'm okay with patching in this way in the meantime.

**Comment by ahuang11** [comment]
> Can you write a little MRE demonstrating that and look into opening a bug upstream? That seems like less than ideal behavior. I'm okay with patching in this way in the meantime.

Seems like it's a known issue that will be fixed in v2 (no plans on adding to v1).
https://github.com/pydantic/pydantic/issues/2277

But here's a MRE:
```
from typing import Dict, Any
from pydantic import BaseModel, SecretField
from pydantic.json import timedelta_isoformat

class SecretDict(SecretField):
    def __init__(self, value: Dict[str, Any]):
        self._secret_value = value
    
    def get_secret_value(self) -> Any:
        return self._secret_value


class Credentials(BaseModel):

    secret_dict: SecretDict

    class Config:
        arbitrary_types_allowed = True
        json_encoders = {
            SecretDict: lambda v: v.get_secret_value(),
        }

class Job(BaseModel):

    credentials: Credentials

credentials = Credentials(secret_dict=SecretDict({"key": "val"}))
job = Job(credentials=credentials)

print(credentials.json())

print(job.json())
```

**Review by anna-geller — APPROVED** [review]
great work! QA passes

image


thanks so much for fixing it so quickly

**Review by desertaxle — APPROVED** [review]

**Pull request merged**
