### PR TITLE
Add additional filters for flow and task end_time in get_flow_runs

### PR DESCRIPTION
**Pull request by rito-sixt**
### Example

This closes https://github.com/PrefectHQ/prefect/issues/9698

### Checklist

- [x] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.

### CODE REVIEW

**Comment by rito-sixt** [comment]
I am having troubles putting in a unit test for this change. 

In this [pytest fixture](https://github.com/PrefectHQ/prefect/blob/e1ac3d0fc622a580d9ec7e727fdea01eaacf62fa/tests/server/api/test_flow_runs.py#L289), where we create the dummy flow runs, I can't find an easy way to put in an `end_time` so that we can test the filter. Couldn't find a related test for the `start_time` either.

Not very fond of the idea of putting in a PR without tests, so would be grateful for any pointers here. I can add tests for both `start_time` and `end_time` together! 🙌

**Comment by desertaxle** [comment]
Thanks for contributing @rito-sixt! Most of our tests for filters are in [this test file](https://github.com/PrefectHQ/prefect/blob/main/tests/server/models/test_filters.py), so that would be the ideal place to add tests for these new filters. Let me know if you have any questions about the structure of those tests!

**Comment by rito-sixt** [comment]
Thanks a ton for the pointer @desertaxle ! Added the tests for the `end_time` filter now!

**Comment by rito-sixt** [comment]
@desertaxle Any further changes required here?

**Comment by serinamarie** [comment]
Hi @rito-sixt, sorry we didn't get a chance to finish reviewing this. I'm reopening the PR :)

**Comment by rito-sixt** [comment]
> Hi @rito-sixt, sorry we didn't get a chance to finish reviewing this. I'm reopening the PR :)

Thanks for taking a look @serinamarie!

**Comment by serinamarie** [comment]
@jakekaplan Do you think you could look over this one since Alex is out?

**Pull request closed without merging**
