### PR TITLE
Enhancement: Add task run names to the `/graph` route

### PR DESCRIPTION
**Pull request by znicholasbrown**
Adds task run names to the `/graph` route for use by the UI in visualizations.  

### Checklist

- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

### CODE REVIEW

**Comment by madkinsz** [comment]
@znicholasbrown looks like you just need to add it to the model a few lines above the route: [DependencyResult](https://github.com/PrefectHQ/prefect/blob/023a2e695737de6ca6b38590746828d0a4b32254/src/prefect/orion/models/flow_runs.py#L261)

**Comment by znicholasbrown** [comment]
Thanks @madkinsz, nice catch 👍🏻

**Review by madkinsz — APPROVED** [review]

**Comment by madkinsz** [comment]
Can you make sure there's test coverage? A follow-up is okay if this is blocking work.

**Comment by brandonreid** [comment]
@znicholasbrown If I can get this into my [orion-design PR](https://github.com/PrefectHQ/orion-design/pull/934), I can make my nebula PR, and I'm sippen vegan eggnog in the everglades for the rest of the week.

**Comment by znicholasbrown** [comment]
Will add additional test coverage in a follow up 👍🏻

**Pull request merged**
