### PR TITLE
fix: set shlex.split posix argument to False if on Windows

### PR DESCRIPTION
**Pull request by NikoRaisanen**
Closes https://github.com/PrefectHQ/prefect/issues/10705

### Checklist

- [x] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [ ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed

### CODE REVIEW

**Comment by NikoRaisanen** [comment]
Hello! This change fixes the issue outlined in the ticket, but I'm struggling with the unit tests.

It seems that the `run_shell_script` method will always error out when running unit tests on Windows.
My basic test to see if I can call run_shell_script without an error while mocking a Windows system:

```
async def test_run_shell_script_split_on_windows(self, monkeypatch):
        monkeypatch.setattr("sys.platform", "win32")
        result = await run_shell_script("echo Hello World")
        assert result["stdout"] == "Hello World"
        assert result["stderr"] == ""
```

The above throws this error when running the unit test:
```
@asynccontextmanager
    async def open_process(command: List[str], **kwargs):
        """
        Like `anyio.open_process` but with:
        - Support for Windows command joining
        - Termination of the process on exception during yield
        - Forced cleanup of process resources during cancellation
        """
        # Passing a string to open_process is equivalent to shell=True which is
        # generally necessary for Unix-like commands on Windows but otherwise should
        # be avoided
        if not isinstance(command, list):
            raise TypeError(
                "The command passed to open process must be a list. You passed the command"
                f"'{command}', which is type '{type(command)}'."
            )
    
        if sys.platform == "win32":
            command = " ".join(command)
>           process = await _open_anyio_process(command, **kwargs)
E           NameError: name '_open_anyio_process' is not defined

src/prefect/utilities/processutils.py:200: NameError
=========================== short test summary info ============================
FAILED tests/deployment/test_steps.py::TestRunShellScript::test_run_shell_script_split_on_windows - NameError: name '_open_anyio_process' is not defined
======================== 1 failed, 48 passed in 25.13s =========================
```

If I remove the monkeypatch that sets sys.platform to win32, then the tests run without errors. Do we think that this change needs an associated test? And if so, I'm open to suggestions!

**Comment by urimandujano** [comment]
Hey @NikoRaisanen, thanks for all the effort here! 

I took a look and it looks like what's happening is that [we're conditionally defining](https://github.com/PrefectHQ/prefect/blob/9f92b6475586997206aba2282a3eb5060eb29ab4/src/prefect/utilities/processutils.py#L30) the  `_open_anyio_process` function depending on if we've detected that we're running on a Windows system or not. That conditional is evaluated at import time (whenever we do `from prefect.deployments.steps import run_shell_script` -- meaning that by the time we get to your test we've already decided to define the function or not!

What I would recommend is using a `pytest.mark` to skip the test if its run on non-windows. [You can see how that works on these lines](https://github.com/PrefectHQ/prefect/blob/9f92b6475586997206aba2282a3eb5060eb29ab4/tests/utilities/test_processutils.py#L72-L75C6). If you add the label `arch:windows` to the PR then I believe we'll run the CI on a Windows machine and be able to verify your change works as expected.

**Comment by NikoRaisanen** [comment]
Hey @urimandujano thanks for the feedback! I just pushed up the test and marked it as windows only.
I don't have permissions to add that `arch:windows` label

**Comment by urimandujano** [comment]
I just found out that our Windows CI workflow isn't working as expected by now. I'll have to test this manually and get back to you -- so sorry for the delay!

**Comment by urimandujano** [comment]
It looks like that test is still failing, can you look into it? Here's what the output was:

```
    @asynccontextmanager
    async def open_process(command: List[str], **kwargs):
        """
        Like `anyio.open_process` but with:
        - Support for Windows command joining
        - Termination of the process on exception during yield
        - Forced cleanup of process resources during cancellation
        """
        # Passing a string to open_process is equivalent to shell=True which is
        # generally necessary for Unix-like commands on Windows but otherwise should
        # be avoided
        if not isinstance(command, list):
>           raise TypeError(
                "The command passed to open process must be a list. You passed the command"
                f"'{command}', which is type '{type(command)}'."
            )
E           TypeError: The command passed to open process must be a list. You passed the command'<MagicMock name='mock()' id='2937046418624'>', which is type '<class 'unittest.mock.MagicMock'>'.

src\prefect\utilities\processutils.py:193: TypeError
```

**Comment by NikoRaisanen** [comment]
Hey @urimandujano! I fixed the test and confirmed that it worked for me locally. Despite mocking the return_value, this test will confirm that shlex.split was called with the `posix=False` argument

**Review by urimandujano — APPROVED** [review]
Thanks a lot @NikoRaisanen!

**Pull request merged**
