### PR TITLE
fix: SettingContext.settings missing profile settings

### LINKED ISSUE #16101: Can't use ephemeral server after running "prefect server start"
### Bug summary

In a from scratch helloworld type example, once I ran `prefect server start` once, I can no longer get the flow to run with the ephemeral server. The only fix is to delete `~/.prefect/prfiles.toml`.

### Version info

```Text
Version:             3.1.4
API version:         0.8.4
Python version:      3.12.4
Git commit:          78ee41cb
Built:               Wed, Nov 20, 2024 7:37 PM
OS/Arch:             darwin/arm64
Profile:             ephemeral
Server type:         unconfigured
Pydantic version:    2.10.1
Integrations:
  prefect-dask:      0.3.2
```

### Additional context

Steps to reproduce:
1. Delete `~/.prefect`
2. Run `prefect config view` to verify that `PREFECT_API_URL` is not set.
3. From a new venv, run a flow with the ephemeral server and verify that it succeeded. 
4. Run `touch ~/.prefect/profiles.toml`
5. Run the flow again, now it will fail with `ValueError: No Prefect API URL provided. Please set PREFECT_API_URL to the address of a running Prefect server.`

### PR DESCRIPTION
**Pull request by Wh1isper**
closes #16101 

### Checklist

- [x] This pull request references any related issue by including "closes `<link to issue>`"
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.

~~- [ ] If this pull request adds new functionality, it includes unit tests that cover the changes~~
~~- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.~~
~~- [ ]  If this pull request adds functions or classes, it includes helpful docstrings.~~

### CODE REVIEW

**Comment by zzstoatzz** [comment]
hi @Wh1isper, thank you for the PR!

this does appear to solve #16101, but I'm not quite sure if this is the fix we want yet. the reason why I hesitate is that the `Settings` class itself has a [ProfileSettingSource](https://github.com/prefecthq/prefect/blob/main/src/prefect/settings/sources.py#L107-L199) that I would expect correctly populates settings from the active profile. Will do some digging and come back here

**Comment by Wh1isper** [comment]
@zzstoatzz Thanks for reviewing the PR! I understand your hesitation, and I appreciate you taking the time to look into it further.

**Comment by zzstoatzz** [comment]
hi @Wh1isper - I want to say that I appreciate your effort looking into this! your exploration helped us figure this out more quickly - thank you 🙂 

I am now going to close this PR as https://github.com/PrefectHQ/prefect/pull/16119 solves this by updating the `ProfileSettingSource` like I mentioned earlier

**Comment by Wh1isper** [comment]
@zzstoatzz Thank you for the quick response and fix! #16119 looks great!

**Pull request closed without merging**
