### PR TITLE
Add another improvement to `prefect deploy` message

### PR DESCRIPTION
**Pull request by serinamarie**
### Overview
We should remove the dead end from this error message by providing the workaround documented in this Discourse article.

https://discourse.prefect.io/t/after-changing-the-location-of-my-flow-file-i-get-an-error-when-trying-to-run-prefect-deploy-conflicting-entry-found-for-flow-with-name/3188

### Example
Screenshot 2023-07-07 at 1 59 58 PM

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [ ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed

### CODE REVIEW

**Comment by discdiver** [comment]
This is great! Thank you! The example in the screenshot might be a little confusing. Maybe it's best to just to ask them to remove the line?

**Comment by serinamarie** [comment]
Yeah, thanks for weighing in. I was trying to safeguard for users who might not be as familiar with JSON and might delete the entire contents of the file (curly brackets included) or remove only part of the entry.

**Review by billpalombi — APPROVED** [review]
Thanks again

**Review by discdiver — APPROVED** [review]
lgtm

**Pull request merged**
