### PR TITLE
Add interactive sandbox

### PR DESCRIPTION
**Pull request by ahuang11**
I think it'd be cool if users get to click run on example code!

image

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

### CODE REVIEW

**Comment by madkinsz** [comment]
I'm a little against this — a big part of our value add is you can run flows then see them in a UI but that won't work here.

**Comment by ahuang11** [comment]
I think it's cool that users can edit the code and see new output.

I was also exploring replit as well and was able to start Orion and have results show up in UI.
image

**Comment by tpdorsey** [comment]
If it works and we can run Orion or, say, link to a Cloud account, I'd like to see this as part of a more holistic first run experience. My suggestion is to continue exploring what is possible here, and engage Reuter and team for input on making this robust and well aligned with a good first/early experience. A tutorial around this would be great.

**Comment by ahuang11** [comment]
Ok will close this for now.

**Pull request closed without merging**
