### PR TITLE
Fix `apprise 1.8.0` imports

### PR DESCRIPTION
**Pull request by serinamarie**
Fixes `apprise` [tests](https://github.com/PrefectHQ/prefect/actions/runs/9063969160/job/24901105992) failing after release of [apprise 1.8.0](https://github.com/caronc/apprise/releases/tag/v1.8.0).

### CODE REVIEW

**Review by abrookins — APPROVED** [review]
LGTM! 👍

**Comment by bayersglassey-zesty** [comment]
Thanks for the fix, we noticed the issue and found your commit almost right away! :)

**Comment by serinamarie** [comment]
Hi @nikhiljain12, we plan to release this today!

cc @bayersglassey-zesty

**Comment by serinamarie** [comment]
Released!

**Pull request merged**
