### PR TITLE
WIP: in-repo conda recipe with subpackages

### PR DESCRIPTION
**Pull request by mcg1969**
**Thanks for contributing to Prefect!**

Please describe your work and make sure your PR:

- [ ] adds new tests (if appropriate)
- [ ] add a changelog entry in the `changes/` directory (if appropriate)
- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

Note that your PR will not be reviewed unless all three boxes are checked.

## What does this PR change?

This adds a conda recipe to the repository, which might be nice in its own right, but the real benefit is to demonstrate the feasibility of using conda subpackages in the recipe to mimic pip options.

## Why is this PR important?

It provides a parallel approach to installing Prefect's optional dependencies to the pip "option" approach implemented in setup.py and documented here:

https://docs.prefect.io/core/getting_started/installation.html#optional-dependencies

### CODE REVIEW

**Comment by mcg1969** [comment]
It sure would be nice if we could more easily unify the information inside setup.py with this conda recipe—that is, pull the dependencies for each optional requirement from that file. To be honest, we might:
https://github.com/holoviz/hvplot/blob/master/conda.recipe/meta.yaml

**Comment by jcrist** [comment]
Thanks @mcg1969! If we did this, I *think* we'd want to move this to the conda-forge feedstock. Having two versions of the conda recipe doesn't really make sense IMO. Other than that, this seems fairly straightforward to me.

**Comment by mcg1969** [comment]
I certainly respect your choice here. I personally prefer to include in-repo recipes to better facilitate testing. I leverage conda-build's testing cycle to ensure the sufficiency of test environments. Regardless, feel free to lift this pattern into conda-forge and close the PR altogether.

**Comment by madkinsz** [comment]
There's now an open PR for this in the feedstock repo although it looks like it will need some additional polish before it can be merged. https://github.com/conda-forge/prefect-feedstock/pull/72

**Comment by jcrist** [comment]
Closing in favor of work in the feedstock repo.

**Pull request closed without merging**
