### PR TITLE
fix broken link to Great Expectations docs

### PR DESCRIPTION
**Pull request by discdiver**
## Summary

fix broken link to Great Expectations docs

## Changes

The link

## Importance

Broken links are suboptimal.

## Checklist

This PR:

- [n/a ] adds new tests (if appropriate)
- [n/a] adds a change file in the `changes/` directory (if appropriate)
- [n/a] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Review by madkinsz — APPROVED** [review]

**Comment by madkinsz** [comment]
Thanks!

**Review by madkinsz — CHANGES_REQUESTED** [review]
Ah actually my bad -- this is updating the auto-generated documentation for 0.13.19. This should also touch the docstring at `src/prefect/tasks/great_expectations/checkpoints.py` so it is correct in the latest version as well

**Comment by discdiver** [comment]
Thanks for the quick look @madkinsz ! Updated in __init.py__

**Review by madkinsz — APPROVED** [review]
Thanks again for contributing!

**Pull request merged**
