### PR TITLE
Add map index to task logs for mapped task runs.

### PR DESCRIPTION
**Pull request by Fraznist**
**Thanks for contributing to Prefect!**

Please describe your work and make sure your PR:

- [x] adds new tests (if appropriate)
- [x] updates `CHANGELOG.md` (if appropriate)
- [x] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (not appropriate)

Note that your PR will not be reviewed unless all three boxes are checked.

## What does this PR change?
Task runs that are mapped now logs their map index alongside their task name, similar to TaskRunners '{name}[{index}]: Starting rask run' logs.
## Why is this PR important?
Enables easy identification of which task log belongs to which task, in parallelized flow runs.

### CODE REVIEW

**Comment by joshmeek** [comment]
Hey @Fraznist I'm running this branch and I don't actually notice a difference in the logs 🤔 

image

On the left is a log from your branch and on the right is with the current master build. The master build appears to already have the mapped index in the logs as this PR expects.

**Comment by Fraznist** [comment]
Hey @joshmeek . You are right, TaskRunners already include the map index in their name. I have added map indexes to logs emitted from within task.run() implementations. In your case you can't spot a difference because I believe none of your tasks log anything to the logger within their run() implementation.
image
On the left is my branch, the right side is the current master branch. 
I am sorry if I wasn't clear enough in the PR message.

**Comment by joshmeek** [comment]
Ah okay I misread @Fraznist! Looks great!

**Comment by Fraznist** [comment]
🎉

**Pull request merged**
