### PR TITLE
Add Fugue integration (WIP)

### PR DESCRIPTION
**Pull request by goodwanghan**
## Summary

Add Fugue tasks to Prefect

## Changes

It adds `transform`, `fsql` and the Fugue resource manager to Prefect

## Importance

It enables users write SQL and simple functions that can be easily tested locally and productionized distributedly.

## Checklist

This PR:

- [x] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [x] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Comment by goodwanghan** [comment]
@tpdorsey @desertaxle @madkinsz PTAL, thank you!

**Review by desertaxle — COMMENTED** [review]
Thanks for the contribution @goodwanghan! I'm noticing that the structure of these tasks is different from other tasks in the Prefect 1.0 task library. You can see the recommended structure of tasks library tasks in the [Prefect 1.0 docs](https://docs-v1.prefect.io/core/task_library/contributing.html#task-structure). This structure helps to ensure that all arguments to customize a task are still available to users when using tasks from the task library. If you'd like to keep these tasks in there current form, let me know the reason, and we'll see how we can work within those constraints!

**Comment by madkinsz** [comment]
Hi! @goodwanghan is this still in progress? I'm closing stale pull requests and this hasn't had activity for quite some time.

**Comment by goodwanghan** [comment]
Hi sorry about the delay. Please close. We already released the integration on Prefect 2. So we will no longer support 1.

**Comment by jawnsy** [comment]
Closing as requested. Thank you for your contribution!

**Pull request closed without merging**
