### PR TITLE
Add pipe support for EdgeAnnotation.

### LINKED ISSUE #5665: Support `.pipe` for `EdgeAnnotation`
## Current behavior

`EdgeAnnotation` doesn't support the newly introduced `.pipe`

## Proposed behavior
```python
mapped = task.map([1,2,3,4]).pipe(flatten).pipe(task2)
```

### PR DESCRIPTION
**Pull request by tirkarthi**
## Summary

Add pipe support for EdgeAnnotation.

## Changes

Handle `EdgeAnnotation` in `pipe` to return `Task` instead of `EdgeAnnotation` for subsequent chaining.

## Importance

Fixes #5665

## Checklist

This PR:

- [x] adds new tests (if appropriate)
- [x] adds a change file in the `changes/` directory (if appropriate)
- [x] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Comment by tirkarthi** [comment]
Regarding mypy error it seems upgrading mypy fixes the issue.

```
(.env) ➜  prefect git:(pipe-edge-annotation) ✗ pip install 'mypy<0.900'
Collecting mypy<0.900
  Using cached mypy-0.812-cp38-cp38-manylinux2010_x86_64.whl (22.5 MB)
Requirement already satisfied: typed-ast<1.5.0,>=1.4.0 in ./.env/lib/python3.8/site-packages (from mypy<0.900) (1.4.3)
Requirement already satisfied: mypy-extensions<0.5.0,>=0.4.3 in ./.env/lib/python3.8/site-packages (from mypy<0.900) (0.4.3)
Requirement already satisfied: typing-extensions>=3.7.4 in ./.env/lib/python3.8/site-packages (from mypy<0.900) (4.1.1)
Installing collected packages: mypy
  Attempting uninstall: mypy
    Found existing installation: mypy 0.942
    Uninstalling mypy-0.942:
      Successfully uninstalled mypy-0.942
Successfully installed mypy-0.812
(.env) ➜  prefect git:(pipe-edge-annotation) ✗ mypy src/prefect/core/task.py                     
src/prefect/core/task.py:958: error: Argument 1 to "issubclass" has incompatible type "Union[Type[EdgeAnnotation], Task]"; expected "type"
src/prefect/core/task.py:959: error: Too many arguments for "EdgeAnnotation"
src/prefect/core/task.py:963: error: Too many arguments for "EdgeAnnotation"
Found 3 errors in 1 file (checked 1 source file)
(.env) ➜  prefect git:(pipe-edge-annotation) ✗ pip install -U mypy          
Requirement already satisfied: mypy in ./.env/lib/python3.8/site-packages (0.812)
Collecting mypy
  Using cached mypy-0.942-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (16.8 MB)
Requirement already satisfied: tomli>=1.1.0 in ./.env/lib/python3.8/site-packages (from mypy) (2.0.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in ./.env/lib/python3.8/site-packages (from mypy) (0.4.3)
Requirement already satisfied: typing-extensions>=3.10 in ./.env/lib/python3.8/site-packages (from mypy) (4.1.1)
Installing collected packages: mypy
  Attempting uninstall: mypy
    Found existing installation: mypy 0.812
    Uninstalling mypy-0.812:
      Successfully uninstalled mypy-0.812
Successfully installed mypy-0.942
(.env) ➜  prefect git:(pipe-edge-annotation) ✗ mypy src/prefect/core/task.py
Success: no issues found in 1 source file
```

**Comment by madkinsz** [comment]
Thanks for the PR!

We cannot upgrade mypy as we'd have to add a bunch of typeshed package dependencies. 

Since this also requires an explicit cast since mypy can't infer the type narrowing, I'm okay with just ignoring the type checker in this small section.

**Comment by tirkarthi** [comment]
@madkinsz Thanks for the review. I have added ignore type check with a comment.

**Review by madkinsz — APPROVED** [review]
Thanks!

**Comment by tirkarthi** [comment]
@madkinsz Thanks for the review and merge.

**Pull request merged**
