### PR TITLE
testing pydantic v1.10.0a2

### PR DESCRIPTION
**Pull request by samuelcolvin**
### TO NOT MERGE

This is pull request is just to test pydantic v1.10, see https://github.com/pydantic/pydantic/discussions/4359

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Hi, please can you kick off tests so I can check if v1.10 will break anything.

**Comment by madkinsz** [comment]
Welcome! Please let us know if there's anything we can do to help. Feel free to ping me here our in your tracking issue.

Some brief notes:
- The Python 3.7 tests run with the lowest version pin. Looks like the script doesn't support alpha labels so it failed on install.
- We test with SQLite and Postgres as backing databases
- Our `--only-services` tests run integration tests with things like Docker that are slow to test against

**Comment by samuelcolvin** [comment]
So from what I can tell, except this issue with lowest version pinning on 3.7, pydantic v1.10 seems to be compatible with prefect. Is that correct?

**Comment by madkinsz** [comment]
Here's a fix for that issue https://github.com/PrefectHQ/prefect/pull/6543 if you're worried specifically about 3.7 compatibility. I imagine that's not a concern though.

Looks like we're compatible yes :)

**Comment by samuelcolvin** [comment]
hopefully I've copied the important part of that commit.

Please could you kick off tests, by the way [you should consider changing the "awaiting approval" settings](https://twitter.com/samuel_colvin/status/1562374350287867904).

**Comment by samuelcolvin** [comment]
okay, hopefully final time :crossed_fingers:.

**Comment by madkinsz** [comment]
🎉

**Comment by samuelcolvin** [comment]
great, thanks so much.

**Pull request closed without merging**
