### PR TITLE
UI block creation link

### PR DESCRIPTION
**Pull request by anticorrelator**
### Summary
Experiment with adding a block creation link to `prefect block type ls`

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- No tests or issue needed
- [ ] A short code fix
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. One-line fixes without tests will not be accepted unless it's related to the documentation only.
- [x] A new feature implementation
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

### CODE REVIEW

**Comment by desertaxle** [comment]
I tried this out and it's pretty slick. It only worked in iTerm2 for me. Is there a way to determine if linking is supported by the user's terminal?

**Comment by abrookins** [comment]
I tried this in Iterm, and it worked if I didn't use tmux, but tmux either doesn't support it or the support needs specific configuration that I don't have. When it didn't work, I saw the text of the link but not the URL.

Given the limitations, I'd probably opt for showing the URL somewhere else that makes more sense.

Another idea I had was that we could run our own URL shortener service and use it to shorten arbitrary URLs for CLI output like this. The service would unpack an arbitrarily compressed (Prefect) URL and redirect to a destination target. Anyway, an idea.

**Comment by desertaxle** [comment]
I think printing the link to the block document creation page for a block type with `prefect block create <block-type-slug>` works well. Some terminals allow you to click on a link and will open up a browser, but otherwise it's easy enough to copy and paste. I think that we can remove the "Generate creation link" column from the `block type ls` table since the `create` command is discoverable via `prefect blocks --help`.

**Comment by anticorrelator** [comment]
> I think printing the link to the block document creation page for a block type with `prefect block create <block-type-slug>` works well. Some terminals allow you to click on a link and will open up a browser, but otherwise it's easy enough to copy and paste. I think that we can remove the "Generate creation link" column from the `block type ls` table since the `create` command is discoverable via `prefect blocks --help`.

Hey @desertaxle, it seems that on balance people are preferring the explicit linking to Block creation in the table, the process of discovering how to create a block is a bit smoother that way. Would you be okay with keeping it?

**Comment by anticorrelator** [comment]
@billpalombi @anna-geller as discussed with ya'll I added the UI-linking pattern to both Deployment creation and on `prefect deployment run`

**Review by anna-geller — APPROVED** [review]
Works great! 

image

image

**Pull request merged**
