### PR TITLE
Added print_func for run_namespaced_job

### PR DESCRIPTION
**Pull request by netanel246**
closes https://github.com/PrefectHQ/prefect/issues/12993

### Checklist

- [ ] This pull request includes a label categorizing the change e.g. `maintenance`, `fix`, `feature`, `enhancement`, `docs`.
- [x] This pull request references any related issue by including "closes `<link to issue>`"
  
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [x] If this pull request adds functions or classes, it includes helpful docstrings.

### CODE REVIEW

**Review by zzstoatzz — APPROVED** [review]
thank you!

**Review by zzstoatzz — CHANGES_REQUESTED** [review]
hmm - looks like we're actually failing a couple tests.

**Comment by netanel246** [comment]
Yep. Committed a fix

**Review by desertaxle — APPROVED** [review]

**Review by zzstoatzz — APPROVED** [review]
lgtm!

**Pull request merged**
