### PR TITLE
Fix JSON logging formatter

### PR DESCRIPTION
**Pull request by mousetree**
### Example

Currently the "json" logger outputs a str() representation of a Python object. This is not strict JSON and as such may not be parsed correctly by downstream log collectors (i.e. Datadog).

This PR uses `json.dumps` to convert the dictionary into valid JSON.

**Before:**
```
{'name': 'prefect.flow_runs', 'msg': "Finished in state Completed('All states completed.')", 'args': [], 'levelname': 'INFO', 'levelno': 20, 'pathname': '/Users/adam/Library/Caches/pypoetry/virtualenvs/sett-prefect-vThVQ5x2-py3.9/lib/python3.9/site-packages/prefect/engine.py', 'filename': 'engine.py', 'module': 'engine', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 366, 'funcName': 'begin_flow_run', 'created': 1667049056.934597, 'msecs': 934.5970153808594, 'relativeCreated': 4141.36004447937, 'thread': 4377200000, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 99513, 'flow_run_name': 'magenta-porpoise', 'flow_run_id': 'ee770a88-9a37-4ce3-b97b-5a3240cc6fab', 'flow_name': 'healthcheck', 'send_to_orion': False}
```

**After:**
```
{"name": "prefect.flow_runs", "msg": "Finished in state Completed('All states completed.')", "args": [], "levelname": "INFO", "levelno": 20, "pathname": "/Users/adam/Library/Caches/pypoetry/virtualenvs/sett-prefect-vThVQ5x2-py3.9/lib/python3.9/site-packages/prefect/engine.py", "filename": "engine.py", "module": "engine", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 366, "funcName": "begin_flow_run", "created": 1667048352.241838, "msecs": 241.8379783630371, "relativeCreated": 3872.573137283325, "thread": 4338468224, "threadName": "MainThread", "processName": "MainProcess", "process": 99058, "flow_run_name": "impressive-hyrax", "flow_run_id": "2cd95e62-b09e-4339-928d-ba55b968aeb5", "flow_name": "healthcheck", "send_to_orion": false}
```

Note the double quotes instead of single quotes and the boolean types (`False` vs `false`)

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

### CODE REVIEW

**Comment by madkinsz** [comment]
@mousetree I'm not sure this is what we want. We are calling `str` on the dictionary after it has gone through a `jsonable_encoder`. I don't remember why we did this instead of dumping directly to JSON, but I think this has different implications.

@chrisguidry are we using this JSON formatter internally w/ DataDog?

**Comment by chrisguidry** [comment]
@madkinsz We are not using this formatter for Prefect Cloud.

**Comment by mousetree** [comment]
Hey @madkinsz - any ideas to move this forward? We're trying to get nicely formatted JSON so that Datadog will understand our logs.

**Comment by madkinsz** [comment]
@mousetree let's use `prefect.serializer.JSONSerializer` and drop use of the `jsonable_encoder`. We can initialize this in the formatter's `__init__`. For `"pretty"` formatting let's print the content after a JSON roundtrip `dumps/loads`.

Note you can also just configure logging to use a formatter defined in your library if you need to.

**Comment by madkinsz** [comment]
Superseded by https://github.com/PrefectHQ/prefect/pull/7567

**Pull request closed without merging**
