### PR TITLE
Add `check_if_running` utility to exit runs that should not be running

### PR DESCRIPTION
**Pull request by madkinsz**
A while back, we discussed adding a utility that users could call from within their task or flow that would check for cancellation. It can be challenging to interrupt runs externally, and this would allow users to opt-in to period checks. Their run would then exit if it was not in a running state according to the API.

### Example

```python
import asyncio
import time

from prefect import check_if_running, flow, get_client, task
from prefect.states import Cancelled


@task
def looper():
    for _ in range(10):
        time.sleep(1)
        check_if_running()
        print("Happy checkpoint :)")


@flow
async def test_flow():
    future = looper.submit()
    # Let the task be happy for a little :)
    await asyncio.sleep(3)

    async with get_client() as client:
        await client.set_task_run_state(
            future.task_run.id, state=Cancelled(message="Get cancelled!")
        )

    print("Task finished in state:", future.wait())
    return True


asyncio.run(test_flow())
```

```
15:36:17.252 | INFO    | prefect.engine - Created flow run 'amazing-adder' for flow 'test-flow'
15:36:17.418 | INFO    | Flow run 'amazing-adder' - Created task run 'looper-ba8747e8-0' for task 'looper'
15:36:17.419 | INFO    | Flow run 'amazing-adder' - Submitted task run 'looper-ba8747e8-0' for execution.
Happy checkpoint :)
Happy checkpoint :)
/Users/mz/dev/prefect/src/prefect/utilities/asyncutils.py:258: UserWarning: `sync` called from an asynchronous context; you should `await` the async function directly instead.
  warnings.warn(
15:36:20.559 | ERROR   | Task run 'looper-ba8747e8-0' - Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/mz/dev/prefect/src/prefect/engine.py", line 1489, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/Users/mz/dev/prefect/src/prefect/utilities/asyncutils.py", line 156, in run_sync_in_interruptible_worker_thread
    tg.start_soon(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-38/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-38/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-38/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-38/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/mz/dev/prefect/src/prefect/utilities/asyncutils.py", line 135, in capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
  File "example.py", line 12, in looper
    checkpoint()
  File "/Users/mz/dev/prefect/src/prefect/utilities/asyncutils.py", line 226, in coroutine_wrapper
    return run_async_from_worker_thread(async_fn, *args, **kwargs)
  File "/Users/mz/dev/prefect/src/prefect/utilities/asyncutils.py", line 177, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-38/lib/python3.8/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-38/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-38/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-38/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/mz/dev/prefect/src/prefect/engine.py", line 1981, in checkpoint
    await raise_state_exception(task_run.state)
  File "/Users/mz/dev/prefect/src/prefect/states.py", line 370, in raise_state_exception
    raise await get_state_exception(state)
prefect.exceptions.CancelledRun: Get cancelled!
15:36:20.581 | INFO    | Task run 'looper-ba8747e8-0' - Task run '6110e28c-e820-4d47-9dfe-8b247850546c' already finished.
Task finished in state: Cancelled('Get cancelled!')
15:36:20.594 | INFO    | Flow run 'amazing-adder' - Finished in state Completed()
```

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

### CODE REVIEW

**Comment by peytonrunyan** [comment]
This seems very handy! Why do we return the state? Is it just for the sake of `if checkpoint(): do_stuff()` logic?

**Comment by cicdw** [comment]
Interesting idea - if we move forward with this I think we should consider a different name, as `checkpoint` implies some persistence, but otherwise seems useful.

**Comment by madkinsz** [comment]
@peytonrunyan it'd just be to make it useful as a utility to get the current state.

@cicdw fair, maybe a more verbose name would make sense. This name is based on [`checkpoint`](https://anyio.readthedocs.io/en/stable/api.html#anyio.lowlevel.checkpoint) from AnyIO/Trio

**Comment by madkinsz** [comment]
I've updated this with `main` and changed the name of the utility.

I see this as an alternative to us implementing heartbeats, allowing users to opt into some reasonable pattern of internal cancellation checks.

@billpalombi your feedback would be appreciated before I add tests and documentation.

**Comment by billpalombi** [comment]
Thanks for tagging me in. This is a great idea! I think `check_if_running` is straightforward without being too verbose.

**Comment by madkinsz** [comment]
Any suggestions for where this should be documented?

**Comment by billpalombi** [comment]
I don't see an obvious place for it. I assume that you don't either @madkinsz. The fact that we don't see one suggests that we might need a new section of our docs (perhaps something like "utilities"?

In the mean time, perhaps the least bad place is the "States" concept page?

**Comment by madkinsz** [comment]
@billpalombi seems like we could use a top-level document for "Cancellation" ?

**Comment by billpalombi** [comment]
A page on Cancellation would definitely be useful. If we had such a page, I think it might fit into our "Tutorials" section, depending on how it was written.

**Pull request closed without merging**
