### PR TITLE
Chore: Fix AKS docs JSON section

### PR DESCRIPTION
**Pull request by iotmani**
Currently, the indentation shows the ` ```json ... ` part of formatting as text.
https://docs.prefect.io/latest/guides/deployment/kubernetes/

### Checklist

- [x] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [ ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed

### CODE REVIEW

**Review by serinamarie — APPROVED** [review]
LGTM! The "Advanced Settings" admonition is not rendering correctly though, not even in the preview, but I'm not sure why.

**Review by discdiver — APPROVED** [review]
lgtm

**Review by billpalombi — APPROVED** [review]
👍

**Comment by iotmani** [comment]
> LGTM! The "Advanced Settings" admonition is not rendering correctly though, not even in the preview, but I'm not sure why.

I opened https://github.com/PrefectHQ/prefect/pull/10667 for this, thanks!

**Pull request merged**
