### PR TITLE
Guard against orchestration race conditions

### PR DESCRIPTION
**Pull request by zangell44**
Closes https://github.com/PrefectHQ/prefect/issues/7640

When multiple processes call /flow_runs/{id}/set_state around the same time, it is possible for both API calls to succeed. This can result in issues like two agents trying to run the same flow run.

### Checklist

- [x] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

### CODE REVIEW

**Review by abrookins — COMMENTED** [review]
@anticorrelator Pointed out that we probably can't do this after all due to the agent query also using a lock. Let's discuss tomorrow -- feel free to talk it through without me if that's easier, due to timezones!

**Comment by madkinsz** [comment]
@anticorrelator  / @zangell44 what's the status of this?

**Comment by anticorrelator** [comment]
@madkinsz I think we should close this, I don't remember the exact details but we greatly reduced the errors seen here in other ways

cc @zangell44

**Comment by madkinsz** [comment]
👍 let me know if that changes

**Pull request closed without merging**
