### PR TITLE
Updates references to flow_name property in deployments

### PR DESCRIPTION
**Pull request by tpdorsey**
Corrects references from `flow` to `flow_name` for Python deployments.

See also https://github.com/PrefectHQ/prefect/pull/8233

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

### CODE REVIEW

**Comment by serinamarie** [comment]
The other PR is referring to the `Deployment` class though, right? Not `build_from_flow`.

**Comment by EmilRex** [comment]
> The other PR is referring to the `Deployment` class though, right? Not `build_from_flow`.

@tpdorsey @serinamarie Yep, came here to say exactly this ^^

**Comment by tpdorsey** [comment]
@EmilRex @serinamarie yes that is my understanding

**Comment by tpdorsey** [comment]
Ah I see, you are correct. I'll close this, but I'll need for you to update the other PR to correct the rest of the Deployment docstring examples

**Pull request closed without merging**
