### PR TITLE
surface limit kwarg in `serve`

### PR DESCRIPTION
**Pull request by zzstoatzz**
the ability to set the `limit` in code with `serve` (the general utility, not the `Flow` method) is hard to find as is

### CODE REVIEW

**Comment by desertaxle** [comment]
Could we add `limit` to the docstring without an additional kwarg? You should be able to pass `limit` in with the current signature.

**Comment by zzstoatzz** [comment]
> Could we add `limit` to the docstring without an additional kwarg? You should be able to pass `limit` in with the current signature.

yep! i was just thinking of the IDE, because in community people have not thought this was possible, so i figured the kwarg would make it more obvious but I can just do docstring if you prefer

**Comment by desertaxle** [comment]
> i was just thinking of the IDE

That makes a lot of sense and making it more discoverable is definitely worthwhile. Our current info message, when you hit the flow run limit, directs you to update the `PREFECT_RUNNER_PROCESS_LIMIT` setting. If we explicitly add `limit` to `serve` I think we'd want to update that message and also add a `limit` kwarg to `flow.serve` for consistency.

**Comment by desertaxle** [comment]
Can you add a test for the `limit` kwarg in `flow.serve` since that's introducing new functionality?

**Comment by zzstoatzz** [comment]
> Can you add a test for the `limit` kwarg in `flow.serve` since that's introducing new functionality?

added in [7da9e83](https://github.com/PrefectHQ/prefect/pull/11645/commits/7da9e8390d43efc0309ce9f8cbb852f7f0451b75)

**Review by desertaxle — APPROVED** [review]

**Pull request merged**
