### PR TITLE
Extend GCSUpload task to allow bytes/gzip data

### PR DESCRIPTION
**Pull request by andywaugh**
## Summary
Extend GCSUpload task to allow uploading of bytes/gzip data as per https://github.com/PrefectHQ/prefect/issues/3507

## Changes
Extend GCSUpload task to allow uploading of bytes/gzip data

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [x] adds a change file in the `changes/` directory (if appropriate)
- [x] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Comment by andywaugh** [comment]
sorry, this is my first run at this so I'm not clear why it is failing - any tips?

**Comment by joshmeek** [comment]
@andywaugh Let me pull this branch locally and take a look, the failing test isn't very clear in CircleCI's output 🙂

**Comment by joshmeek** [comment]
@andywaugh Fixed! For the typing of data it wanted `Union[str, bytes]` instead of `Union(str, bytes)` 🙂

**Comment by andywaugh** [comment]
Ah that was silly! Sorry about that, thanks @joshmeek !

**Review by joshmeek — APPROVED** [review]

**Pull request merged**
