### PR TITLE
Fix PagerDuty notification formatting

### LINKED ISSUE #10427: Subject and Body of PagerDuty Automation Appear Concatenated in the Incident Title
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using a PagerDuty block with an automation, the fields for the subject and body of the notification become concatenated and are both present in the title of the incident in PagerDuty. When using the default inputs for an automation (with all flow run metadata) it results in a lengthy incident title, which is difficult to interpret. 

The screenshots below show how the subject and body of the notification is set, and how the information is currently presented in PagerDuty.
automation_screenshot
pagerduty_prefect_1_top
pagerduty_prefect_2_bottom

Ideally, the title should only include the subject provided to the automation. The information in the body would be in the Custom Details section of the incident report. See the examples below for how Datadog notifications are presented in PagerDuty.
pagerduty_datadog_1_top
pagerduty_datadog_2_bottom

 

### Reproduction

```python3
1. Create a PagerDuty notification block
2. Create an automation which, when triggered, fires off a notification using the block. Enter information into the fields for the subject and body of the notification.
3. Once the automation is triggered, preview the resulting incident report in PagerDuty.
```

### Error

```python3
No error provided.
```

### Versions

```Text
2.10.11
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kevingrismore**
Closes #10427

Apprise combines the subject and body together into a single string for PagerDuty, which makes for unsightly incident names. This change empties the notification body into `custom_details` and re-inits the block to rebuild the URL so relevant data from the notification is rendered separately in PagerDuty.

image

### Checklist

- [x] This pull request references any related issue by including "closes `<link to issue>`"
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ ] If this pull request adds functions or classes, it includes helpful docstrings.

### CODE REVIEW

**Comment by kevingrismore** [comment]
Some minor weird things to note:
- apprise won't accept an empty string body, so I opted for a space. Open to suggestions but it doesn't impact PagerDuty rendering at all
- I'm replacing spaces so they don't get mangled as part of the query in the URL. There are other characters that might need to be treated this way too, but I haven't tried that yet

**Comment by kevingrismore** [comment]
If just a `body` is provided, that becomes the title field in PagerDuty. I wanted to preserve that behavior for anyone who's just calling `block.notify("a string")` right now, and still make rendering `body` and `subject` separate for those using both or when the notification automation action fires. Lmk if you think that shouldn't be the case though!

**Review by zzstoatzz — APPROVED** [review]

**Comment by ConstantinoSchillebeeckx** [comment]
Anyway we can get this released to 2.x also? Looks like it made it into [3.x only](https://github.com/PrefectHQ/prefect/releases/tag/3.0.7)?

**Comment by kevingrismore** [comment]
> Anyway we can get this released to 2.x also? Looks like it made it into [3.x only](https://github.com/PrefectHQ/prefect/releases/tag/3.0.7)?

@ConstantinoSchillebeeckx good point! Adding it [here](https://github.com/PrefectHQ/prefect/pull/15659)

**Pull request merged**
