### PR TITLE
[Enhancement] Powershell as shell input to ShellTask

### PR DESCRIPTION
**Pull request by chinmay-bhat**
## Summary

This PR adds Powershell as a valid input shell for ShellTask. https://github.com/PrefectHQ/prefect/issues/3375

## Changes

Powershell is unable to read the temp file while it's open in another process (`with tempfile.NamedTemporaryFile(prefix="prefect-") as tmp:`).
So the solution is to update the file with the helper script and command, add a `ps1` suffix, and close it. 
Only then we run the temp script with powershell, and finally unlink (delete) the file.
For reference, see this [stackoverflow answer](https://stackoverflow.com/a/5344603) 

## Checklist

This PR:

- [x] adds new tests (if appropriate)
- [x] adds a change file in the `changes/` directory (if appropriate)
- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Comment by chinmay-bhat** [comment]
It seems [Powershell](https://github.com/PowerShell/PowerShell) is not installed for tests, so it's throwing errors.

**Comment by madkinsz** [comment]
Hey! Thanks for contributing :) Considering all of the implementation changes necessary for Powershell, should we introduce a separate `PoweshellTask`?

**Comment by chinmay-bhat** [comment]
Hi @madkinsz , yeah that would be a better solution!

**Review by madkinsz — APPROVED** [review]
Great! Thank you :)

**Pull request merged**
