### PR TITLE
Add `timeout` to `QueueService.drain_all` and limit `APILogHandler.flush` time to 5s

### PR DESCRIPTION
**Pull request by madkinsz**
Closes https://github.com/PrefectHQ/prefect/issues/9345

I'd prefer a solution that resolves the deadlock entirely, but let's not wait forever when it occurs as a starting point.

### CODE REVIEW

**Comment by madkinsz** [comment]
@serinamarie fyi I just added some tests and it required some changes

**Comment by serinamarie** [comment]
> @serinamarie fyi I just added some tests and it required some changes

LGTM! 
In the tests, why is the upper bound on the expected time 2 and 1 instead of the same number of secs?

**Comment by madkinsz** [comment]
Great question; debugging weird problems and forgot to change it. I'll make it a couple seconds to satisfy GHA.

**Comment by madkinsz** [comment]
Closing in favor of smaller change in #9399

**Review by desertaxle — APPROVED** [review]

**Pull request merged**
