### PR TITLE
Chore: Remove enhanced scheduling UI flag

### PR DESCRIPTION
**Pull request by bunchesofdonald**
Removes the ENHANCED_SCHEDULING_UI flag and related UI code.

Related to https://github.com/PrefectHQ/nebula/issues/7115

### CODE REVIEW

**Review by znicholasbrown — COMMENTED** [review]
Just double checking - any necessary ui-library updates for this have already been merged, correct?

**Comment by bunchesofdonald** [comment]
I opted to do this in two steps, so I have a ui-library PR (https://github.com/PrefectHQ/prefect-ui-library/pull/2168) to remove the code that _uses_ the flag, and then I'll go back and remove the flag itself after it gets bumped in here / OSS.

**Comment by desertaxle** [comment]
I think this is the first time we've removed a feature flag setting, and I think it will cause users' clients to crash if they have it set in their profile. The number of users with an experimental setting enabled is probably tiny, but it'd be nice if the client didn't crash on unrecognized settings. Do you think it'd be possible to add that to this PR? No worries if not, I can create an issue for it.

**Comment by bunchesofdonald** [comment]
> I think this is the first time we've removed a feature flag setting, and I think it will cause users' clients to crash if they have it set in their profile. The number of users with an experimental setting enabled is probably tiny, but it'd be nice if the client didn't crash on unrecognized settings. Do you think it'd be possible to add that to this PR? No worries if not, I can create an issue for it.

Sure, let me take a look at it. If I decide it's too much for this PR I'll create an issue.

**Comment by bunchesofdonald** [comment]
@desertaxle I added handling for that here: https://github.com/PrefectHQ/prefect/pull/12184/commits/93f9a1203451902655d2b596da9874842af64ba2

**Review by desertaxle — APPROVED** [review]
LGTM!

**Review by znicholasbrown — APPROVED** [review]

**Review by abrookins — APPROVED** [review]

**Pull request merged**
