### PR TITLE
Bump hasura image version to 2.1.1 to fix M1 support

### PR DESCRIPTION
**Pull request by treuherz**
## Summary

Proper Apple Silicon support was added to `hasura/graphql` engine in [v2.1.0](https://github.com/hasura/graphql-engine/releases/tag/v2.1.0). This brings it into the Server.

## Changes

Just the version of the `hasura/graphql` image in the server's composefile from 2.0.9 to 2.1.1

## Importance

This should mean the prefect server can start up on M1 Macs without them needing [8GB of RAM](https://github.com/hasura/graphql-engine/issues/6337#issuecomment-969300069)!

## Checklist

This PR:

- ~~adds new tests (if appropriate)~~
- [x] adds a change file in the `changes/` directory (if appropriate)
- ~~updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)~~

### CODE REVIEW

**Comment by treuherz** [comment]
Possibly the [advice in the docs](https://github.com/PrefectHQ/prefect/blob/master/docs/orchestration/server/troubleshooting.md#L17) can be removed now as well, but I don't know if there are other circumstances it helps with than just the M1 crash.

**Comment by madkinsz** [comment]
Hey @treuherz would you mind opening a PR to the `prefecthq/server` repository as well? That way we can make sure Server specific tests pass first.

**Comment by treuherz** [comment]
Hadn't caught the repo separation before. [Done!](https://github.com/PrefectHQ/server/pull/337)

**Comment by treuherz** [comment]
I've fixed the problem with CircleCI (and [submitted a docs fix for the problem](https://github.com/PrefectHQ/prefect/pull/5341)) but I don't know how to retrigger the check!

**Comment by madkinsz** [comment]
@treuherz I retriggered the check but the `-` was missing :)

https://github.com/PrefectHQ/server/pull/337 LGTM so I'll merge this after tests pass here.

Thanks again!

**Review by madkinsz — APPROVED** [review]

**Pull request merged**
