### PR TITLE
Issue 5380

### PR DESCRIPTION
**Pull request by heyitskevin**
## Summary
This PR adds additional data to the context object per this issue: https://github.com/PrefectHQ/prefect/issues/5380

## Changes
Small changes to the `get_flow_run_info()` method that hits GQL to pull down additional context data.

## Checklist
Allows for further context introspection by tenant and by group.

This PR:

- [ ] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Comment by kvnkho** [comment]
I am working on QA-ing this now to see if it bloats the context too much, which we have issues with for mapping at scale. Will report back.

**Comment by madkinsz** [comment]
We're hesitant to extend the context with additional data due to performance concerns. We've already had quite a few instances of memory strain due to context copying operations. 

I'm going to consider this a bit further, but now that we're at 1.x I'm worried about introducing performance regressions.

**Comment by discdiver** [comment]
Can we close this @madkinsz ?

**Comment by madkinsz** [comment]
@cicdw had suggested that we should lean towards accepting it in the past which is why I did not close it when cleaning up old changes.

**Pull request closed without merging**
