### PR TITLE
Hide password values

### PR DESCRIPTION
**Pull request by ahuang11**
### Summary

Fixes https://github.com/PrefectHQ/prefect/issues/6102

### Steps Taken to QA Changes

```
export PREFECT_ORION_DATABASE_PASSWORD='postgres_password'
export PREFECT_ORION_DATABASE_CONNECTION_URL='postgresql+asyncpg://postgres:postgres_password@localhost/orion'
prefect orion start
```
image

### Checklist

This pull request is:
- [ x ] A short code fix
	- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. One-line fixes without tests will not be accepted unless it's related to the documentation only.

**Happy engineering!**

### CODE REVIEW

**Comment by abrookins** [comment]
There are deeper problems here @ahuang11, like the fact that we could log your connection URL unmasked. We need to think a bit holistically about how to resolve this, and it may require changes to our Settings interface.

1. We could look for this specific setting anywhere it might get printed to stdout, logged, or displayed in the UI and add special casing for it.
2. We could teach our Settings system what to do with values that the user wants "masked" for display purposes, but wants us to retrieve for its actual purpose.

**Comment by abrookins** [comment]
Short term we may want to do something like this to buy us time depending on how hard changing settings would be though. 😅

**Comment by ahuang11** [comment]
Actually, since I'm literally overwriting the value in the post_root_validators, not sure if this affects downstream, or if post_root_validators simply is for rendering in the UI (which I doubt)

**Comment by ahuang11** [comment]
I think we need a `SecretSetting` class

**Pull request closed without merging**
