### PR TITLE
Allow using `flow` and `flow_run` properties in base job template placeholders

### PR DESCRIPTION
**Pull request by westford14**
Fixes issue #14646 -- this actually ended up being a bit more involved than I initially thought because I wanted to try and have this populate safely.  I try to capture a few edge cases and create tests for them but also want to see how everyone else who is more familiar with the codebase finds these changes 

### Checklist

- [X] This pull request references any related issue by including "closes `<link to issue>`"
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [X] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [X] If this pull request adds functions or classes, it includes helpful docstrings.

### CODE REVIEW

**Comment by westford14** [comment]
looks like the tests are failing for an unrelated issue: https://github.com/PrefectHQ/prefect/actions/runs/10990070650/job/30509530683#step:9:421 -- should i create an issue for this?

**Comment by desertaxle** [comment]
Thanks for the PR @westford14! I have a fix for the CI failures in #15467, so you don't have to worry about them in this PR.

I like your implementation, but I have some concerns about the developer experience.

These are my concerns in no particular order:
The templating for work pool-based job templates is already confusing. This would add an additional layer of templating, which would increase the complexity.
- These new dynamic values can only be used as base job template variable values and not directly in the base job template configuration. 
- The new dynamic values use `{...}` to indicate placeholders instead of `{{...}}` currently used in base job templates.
- Being able to use any field from `flow`, `flow_run`, or `deployment` means that we need to sanitize the name after templating to ensure we don't end up with a name that will be rejected by the underlying infrastructure (e.g. Kubernetes).
- The new templating can only be used for `name` which isn't immediately obvious and will likely need to be extended to include more fields in the future because I think users are going to like this.

I have a suggestion for an alternative approach, which I'd love to hear your thoughts on: Create a new `context` variable (or `ctx` for brevity and coolness) that can be used anywhere in the work pool base job template and contains `flow`, `flow_run`, and `deployment` for a given run. We could advertise the use of this pattern by making the default value for the `{{name}}` placeholder `{{context.flow_run.name}}`, which wouldn't change any functionality but would make it more clear where the name for created infrastructure is coming from.

Let me know what you think and if there's anything I should clarify further. 

I'm also going to tag @cicdw and @zzstoatzz so they can weigh in with their opinions.

**Comment by zzstoatzz** [comment]
> thanks for the really well thought out response here -- I like the idea of a `ctx` variable as, over time, we can start loading more into it and have it start acting like a Go type of `context.Context()`
> 
> barring any updates from @cicdw and @zzstoatzz -- i'll give it a shot and then update this PR when it's ready

context variable sounds good to me! one small request to update the title of this PR accordingly

**Comment by westford14** [comment]
hey @desertaxle -- spent some time thinking about this and playing around with it and I was wondering if this context object is related to the `_related_objects` dictionary that gets set in the `BaseJobConfiguration` https://github.com/PrefectHQ/prefect/blob/main/src/prefect/workers/base.py#L97 

It doesn't seem to be used much anywhere else in the code but is this something that we could convert into the `context` object since adding a new field in `BaseJobConfiguration` causes a huge amount of downstream changes

**Comment by desertaxle** [comment]
@westford14 Yes, I think that the current `_related_objects` could be used as a basis for a new `context` variable. I wouldn't expect `context` to show up as a field in any classes, but instead, it would be an input when templating fields within the base job template. I'm thinking `context` would be a Prefect-supplied value to `apply_values` in addition to the user-supplied values.

**Comment by westford14** [comment]
okay @desertaxle -- took a first cut at creating a `ctx` values and injecting it into `apply_values`, how does this look? what ways should this be extended?

**Review by desertaxle — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
