### PR TITLE
Update KubernetetsRun run config docs

### PR DESCRIPTION
**Pull request by zschumacher**
## Summary

Update the `KubernetesRun` run config docs

## Changes

Adds suggestions for handling custom image tags other than `latest` on custom docker images in the `KubernetetsRun` run config

## Importance

It is likely going to be a common gotcha for anyone running the k8s agent

## Checklist

This PR:

- [x] adds new tests (if appropriate)
- [x] adds a change file in the `changes/` directory (if appropriate)
- [x] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Comment by zschumacher** [comment]
Not sure if I need any changes added for this, but if I missed something please let me know!

**Comment by kvnkho** [comment]
+1 that this is needed. 3 people in support over the last month have had similar issues.

**Review by zangell44 — APPROVED** [review]
Looks good to me, thanks for putting this together @zschumacher !!

**Comment by madkinsz** [comment]
Hey @zschumacher -- I appreciate that you took the time to do this! After taking a look at the example template you added, I think we should probably expose an image pull policy option as a first-class setting on the `KubernetesRun` to help users get past this without having to construct an entire template. I think after we do that we can revisit this doc.

**Comment by zschumacher** [comment]
> Hey @zschumacher -- I appreciate that you took the time to do this! After taking a look at the example template you added, I think we should probably expose an image pull policy option as a first-class setting on the `KubernetesRun` to help users get past this without having to construct an entire template. I think after we do that we can revisit this doc.

@madkinsz agreed, that seems like the better solution.  Do you want me to take a stab at that in this PR?

**Comment by madkinsz** [comment]
@zschumacher go for it, you'll probably get to it before us. We might be picky about the end result since RunConfig changes have to be supported for a long time though.

**Comment by zschumacher** [comment]
@madkinsz @zangell44 @kvnkho new pr here https://github.com/PrefectHQ/prefect/pull/4462.  Feel free to close this one.

**Pull request closed without merging**
