### PR TITLE
`.get_dates()` added to  "prefect.client.schemas.schedules.CronSchedule"

### LINKED ISSUE #9976: Add `get_dates()` method to `prefect.client.schemas.schedules.CronSchedule` so that it's consistent with `prefect.server...CronSchedule`
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

It seems that recently the deployment objects I get from `.read_deployments()` have changed to be `prefect.client.schemas.schedules.CronSchedule` instead of `prefect.server.schemas.schedules.CronSchedule`. This caused a very subtle bug due to those two classes not having the same interface. Namely, the server one has `get_dates()` which I was relying on, but the client one does not.

### Describe the proposed behavior

I would like to propose two possible changes:
- Just have one version of the CronSchedule class -- I think it will lead to lots of confusion and bugs like these that are hard to track down if there are two distinct versions
- Or, if that's not possible, could we just have the `client` version expose the `.get_dates()` method as well? Thanks!

Fwiw, as it is right now, my workaround is to just convert the client CronSchedule to a server CronSchedule so I can use `.get_dates()`, but it took me a while to even figure out that this was the issue because it was pretty unexpected to me that there were two classes named CronSchedule in prefect.

Thanks!

### Example Use

I think the big value of this is avoiding lost time on hard-to-debug errors like the one I described.

### Additional context

none

### PR DESCRIPTION
**Pull request by rkscodes**
### Checklist

- [X] This pull request references any related issue by including "closes #9976"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [ ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed

### CODE REVIEW

**Comment by desertaxle** [comment]
Thanks for the PR @rkscodes! Could you please add some tests covering this new functionality?

**Comment by bunchesofdonald** [comment]
Since there's no linked issue I'm curious what this PR is trying to achieve. The `server.schemas` version of `CronSchedule` has a `get_dates` method that looks very similar to the code in this PR, is there a reason you're unable to use the server schema?

**Comment by rkscodes** [comment]
Sure, I have a question, I can't see any test files for client's `schedule.py`,  should I create a new one ?

**Comment by rkscodes** [comment]
@bunchesofdonald Yes there is a linked issue in the description of the PR, I am sharing it again for easy reference. 

[Linked issue](https://github.com/PrefectHQ/prefect/issues/9976)

**Comment by bunchesofdonald** [comment]
Awesome, thanks for the issue link @rkscodes !

**Comment by bunchesofdonald** [comment]
Also please feel free to create new test files if you don't see one that lines up with what you're testing.

**Comment by zanieb** [comment]
Fwiw I intentionally did not copy `get_dates` from the server schemas to the client ones because the client is just defining the schema and the server is intended to do all the scheduling. If it's useful to a lot of people, we could copy the implementation over for all of the schedules, but then we have to worry about additional implementation maintenance. Why do you need to generate schedule dates manually?

**Comment by rkscodes** [comment]
I agree with Zanieb, I can't see much use to do so at client part, but I am curious how would we resolve the regression which user is facing after this change.

**Comment by rkscodes** [comment]
Sure @desertaxle looking in suggested approach.

**Pull request closed without merging**
