### PR TITLE
Remove image layer caching during builds

### PR DESCRIPTION
**Pull request by jawnsy**
Avoid caching during image builds to ensure freshness at the cost of slower build times.

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.

### CODE REVIEW

**Comment by madkinsz** [comment]
Are we disabling caching for _all_ builds here? Should we just do so for releases and retain the cache for the dev images?

**Comment by jawnsy** [comment]
@madkinsz Yea, I removed it for everything (dev + release builds). I went back and forth on keeping it for dev images, but I think having more consistency between our builds is preferable, unless it becomes a problem otherwise.

I figured that the performance cost wouldn't be too significant, and if I'm wrong, we can always add caching back for dev builds

**Comment by madkinsz** [comment]
I think it _was_ significant in the original testing. We'll know in a second :)

**Review by madkinsz — APPROVED** [review]

**Comment by jawnsy** [comment]
Related to https://github.com/PrefectHQ/prefect/issues/9493 - we seemed to have a caching issue related to the `prefect.db` database file

**Pull request merged**
