### PR TITLE
added task AWSSecretsManager and tests

### LINKED ISSUE #2069: Add new AWS Secrets Manager Task
To add to our non-Prefect Cloud [Secret Task library](https://docs.prefect.io/api/latest/tasks/secrets.html), we should add a new AWS Secrets Manager Task.  This should only involve exposing the following three kwargs at initialization:
- `secret_id`
- `version_id`
- `version_stage`

as described here: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager.html#SecretsManager.Client.get_secret_value

### PR DESCRIPTION
**Pull request by Zaubeerer**
**Thanks for contributing to Prefect!**

Please describe your work and make sure your PR:

- [x] adds new tests (if appropriate)
- [x] add a changelog entry in the `changes/` directory (if appropriate)
- [x] updates docstrings for any new functions or function arguments, 
- [x] including `docs/outline.toml` for API reference docs (not sure whether appropriate)

Note that your PR will not be reviewed unless all three boxes are checked.

## What does this PR change?

Adds a task that enables secrets to be retrieved from AWS secrets manager.

## Why is this PR important?

This feature has been demanded by several users (see [issue 2069](https://github.com/PrefectHQ/prefect/issues/2069)).

closes #2069

### CODE REVIEW

**Comment by jcrist** [comment]
Hmmm, I can see arguments for either. My weakly-held feeling is this should go in the `aws` module, since the `secrets` module is more core secrets things, and this is `aws` specific and requires `aws` specific imports. I also have a weird urge to call this thing `AWSSecretsManagerSecret`, to match our convention of a suffix indicating the class type, but that might be too unwieldly.

**Comment by Zaubeerer** [comment]
> Also looking for an opinion from you or any other contributors: does this task belong better under `prefect.tasks.aws` or `prefect.tasks.secrets` 🤔

Happy to read, that I was not the only one wondering 😄 

As a relatively new user to prefect, I find it more intuitive in `aws.tasks`. 

>Hmmm, I can see arguments for either. My weakly-held feeling is this should go in the aws module, since the secrets module is more core secrets things, and this is aws specific and requires aws specific imports.

This is also why I put it to `aws.tasks` first. 🤷‍♂️

**Comment by Zaubeerer** [comment]
Hmm, for me, locally, only the following test fails:

```Python
    def test_raises_if_secret_not_eventually_provided(self):
        task = AWSSecretsManager(name="test", tags=["AWS"])

        # TODO: I did not understand what this test tests (copied from S3Download)
        with pytest.raises(ValueError, match="name"):
            task.run(name="")
```

**Comment by joshmeek** [comment]
@Zaubeerer Update that test to say `task = AWSSecretsManager(tags=["AWS"])`, leaving out the name. It's a simple ValueError assertion

**Comment by Zaubeerer** [comment]
@joshmeek, I changed the parameter from "name" to "secret" and made some more changes analogue to S3Download.

**Comment by jcrist** [comment]
LGTM, thanks for working on this!

**Comment by Zaubeerer** [comment]
>LGTM, thanks for working on this!

Great, happy to contribute!

**Pull request merged**
