### PR TITLE
Add backwards compatibility integration tests

### PR DESCRIPTION
**Pull request by madkinsz**
- Adds `/flows` for writing flows to use in integration tests
- Extends the `Integration tests` workflow to test client/server compatibility by running flows

Runs all of the flows in `/flows` with the current client and an old server version running in a Docker container.
Runs all of the flows in `/flows` with an old client version running in a Docker container with the current server (flows are mounted into the image).

### Example

Client not compatible with old server https://github.com/PrefectHQ/prefect/actions/runs/3130522985/jobs/5080857103
Server not compatible with old client https://github.com/PrefectHQ/prefect/actions/runs/3130522985/jobs/5080857344
Compatible https://github.com/PrefectHQ/prefect/actions/runs/3130522985/jobs/5080857524

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

### CODE REVIEW

**Comment by madkinsz** [comment]
I've disabled the broken versions now, see #6981 #6978 for tracking re-enabling them.

**Review by abrookins — APPROVED** [review]
Well, I'm not sure what else I can say except... incredible! 😍 👍 LGTM

**Comment by peytonrunyan** [comment]
Looks great to me! Probably for a later PR, but do want to add registering and running deployments to this one too?

**Comment by madkinsz** [comment]
> Looks great to me! Probably for a later PR, but do want to add registering and running deployments for these integration tests?

Probably! I didn't want to deal with additional services yet.

**Pull request merged**
