### PR TITLE
Added Github retry and timeout parameters

### PR DESCRIPTION
**Pull request by britter-mwb**
## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Review by anna-geller — APPROVED** [review]
This LGTM - I haven't tested that with the actual Git repo, but it looks fine based on https://github.com/PyGithub/PyGithub/blob/master/github/MainClass.py#L101

**Review by madkinsz — CHANGES_REQUESTED** [review]
@britter-mwb Thanks for contributing! We'll need tests and a changelog entry before we can accept this.

**Comment by madkinsz** [comment]
@britter-mwb checking in to see if you're interested in finishing this change.

@abrookins this would be a small lift to get across the line if we want to assign an engineer to it. Otherwise, we should close it as stale.

**Comment by britter-mwb** [comment]
> @britter-mwb checking in to see if you're interested in finishing this change.
> 
> @abrookins this would be a small lift to get across the line if we want to assign an engineer to it. Otherwise, we should close it as stale.

Hi Michael, I would still like the changes made, but I am not resourced to make the changes requested at this time. Is this something that someone on the prefect side could take on, or will I need to come back to it once I have more bandwidth?

**Comment by madkinsz** [comment]
@britter-mwb Sorry we don't have the resources to take this on.

Feel free to reopen if you have time to finish it! Thanks for contributing.

**Pull request closed without merging**
