### PR TITLE
Fix `load_flow_argument_from_entrypoint` to work with async flows

### LINKED ISSUE #13765: Async flow deployment regression in 2.19.3
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Async flows cannot be deployed with Prefect 2.19.3. This worked fine with Prefect 2.19.2

### Reproduction

testflow.py:
```python3
from prefect import flow

@flow
async def main():
    pass
```

### Error

```bash
$ prefect deploy testflow.py:main
Could not find flow 'main' in 'testflow.py'
```

Given the above MRE, the `prefect deploy` command errors out with the message "Could not find flow 'main' in 'testflow.py'"

### Versions

```Text
Version:             2.19.3
API version:         0.8.4
Python version:      3.10.12
Git commit:          ce378efe
Built:               Thu, May 30, 2024 11:59 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elisalimli**
Fixes #13765

The `load_flow_argument_from_entrypoint` function in Prefect doesn't support finding async functions (AsyncFunctionDef) decorated with @flow.

What We Expect:
It should be able to find both async functions and regular functions (FunctionDef) decorated with @flow.

### CODE REVIEW

**Comment by serinamarie** [comment]
Hi @elisalimli thanks for opening your first PR to `prefect`! Giving the workflows a run now, and I think @desertaxle would probably be the best one to take a final look at this :)

**Comment by desertaxle** [comment]
Thanks for the PR @elisalimli! Could you please add a test case to cover this case?

**Comment by elisalimli** [comment]
Thanks for the quick response @desertaxle and @serinamarie.

@desertaxle I have added a test case in 60b5602

**Review by zzstoatzz — APPROVED** [review]
lgtm!

cc @desertaxle

**Comment by elisalimli** [comment]
This issue blocks us as a team right now, therefore we would be glad if you could merge within today/tomorrow. Thanks in advance!

cc @zzstoatzz @desertaxle @serinamarie

**Review by desertaxle — APPROVED** [review]
Thanks!

**Pull request merged**
