### PR TITLE
Fix TYPE_CHECKING with MYPY to support python prior 3.5.2

### PR DESCRIPTION
**Pull request by gavincyi**
**Thanks for contributing to Prefect!**

Please describe your work and make sure your PR:

- &#x2611; adds new tests (if appropriate)
- &#x2611; updates `CHANGELOG.md` (if appropriate)
- &#x2611; updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

Note that your PR will not be reviewed unless all three boxes are checked.

## What does this PR change?

As the typing module prior to python version 3.5.2 does not support `TYPE_CHECKING`  (#1247), it is replaced by the constant [MYPY](https://mypy.readthedocs.io/en/latest/common_issues.html#import-cycles).

## Why is this PR important?

The change is to support python 3.5.1.

### CODE REVIEW

**Comment by jlowin** [comment]
I apologize because I'm a little late to this issue but I do have some reservations about this change. 

We are already taking steps to accommodate a `typing` bug in 3.5.2, and the more that we attempt to reconcile some of Prefect's better features (like a fully-typed library) with versions of Python that don't support those features (<3.5.2), the more difficult we make the development experience in the future. 

I want to be absolutely sure that a change like this, which involves syntax that anyone unfamiliar with 3.5.0/1 would never be able to guess, is truly beneficial. For example, any new user coming to Prefect and attempting to follow the "official" guides to writing a typed library will be totally baffled by this (and if they use `TYPE_CHECKING`, they'll break the unit tests that we'll have to add to make sure this is maintained in a non-obvious way). (Aside: we will need to create another set of "import" unit tests for Python 3.5.0 and 3.5.1 to make sure that future users continue to use this syntax.)

A simpler alternative would be to simply say that Prefect relies on features found in Python 3.5.2+. According to PyPi, Python 3.5 makes up less than 1% of all Prefect downloads; of that 1%, it can't be that there are significant numbers of users on 3.5.0 or 3.5.1, as neither is a standard install on any system (to my knowledge). @gavincyi it's actually possible you're the only one -- is it possible for you to upgrade to a more current version of Python, even within the 3.5.X channel?

If we do want to go down this road, then it may be time to introduce a `compatibility.py` file from which we can `from prefect.compatibility import TYPE_CHECKING`. That way it would be appropriately defined (actually `TYPE_CHECKING` in 3.5.2+, `MYPY` in 3.5.0 and 3.5.1) and the syntax would be familiar to anyone looking at mypy's documentation. (note: this might not work if MYPY is only recognizing the variable via literal substitution at check-time.) However, I think for a library that relies on as many "modern" features of Python as Prefect to have a `compatibility` file is perhaps a smell that we are already compromising in an undesirable way.

**Comment by gavincyi** [comment]
Totally understand your rationale and concern.

At the current stage I would prefer to support python 3.5.1 as my use case is mostly for enterprise use (which will not upgrade the python 3 version in production in the near future). My understanding is python 3.5.1 is very likely the python 3.5 version installed as this is the static version provided in [SCL](http://mirror.centos.org/centos/7/sclo/x86_64/rh/rh-python35/) which is dependent by RHEL 6 / 7 (e.g. Centos 6 / 7). 

For me I have no strong preference how it should be implemented, and in my knowledge even wrapping a constant [False](https://github.com/sphinx-doc/sphinx/pull/4735) could resolve the importing cycles. 

Finally, I understand that including python 3.5.1 is not a priority for your team at this moment, so I'm happy to help implement it if you find a way which is comfortable for your team to maintain it.

**Comment by joshmeek** [comment]
Whoa! @cicdw After the tests ran in #1263 they started running here

**Comment by cicdw** [comment]
Hi @gavincyi just wanted to let you know i haven’t forgotten about you! We are considering the trade offs of the change and thinking about a possible way of unifying both typing patterns in a consistent way. I’ll definitely update you shortly

**Comment by cicdw** [comment]
Closing per https://github.com/PrefectHQ/prefect/issues/1247#issuecomment-515544151

**Pull request closed without merging**
