### PR TITLE
Ignore new mypy type error

### PR DESCRIPTION
**Pull request by joshmeek**
This was failing for me locally on the most recent mypy build

### CODE REVIEW

**Comment by jcrist** [comment]
What version of Python? I fixed mypy errors due to 0.790 release in #3470, and things are passing fine for me locally with 0.790.

**Comment by joshmeek** [comment]
@jcrist This is occurring for me on 0.790 🤔

**Comment by jcrist** [comment]
Odd. That's similar to the errors I squashed in #3470. Note that our mypy CI runs on 3.7 and seems to be passing fine pre this change. Are you sure you're picking up the right version of mypy (run `mypy --version`)? Have you tried clearing the mypy cache?

```
(prefect37) ➜  prefect git:(master) ✗ mypy --version
mypy 0.790
(prefect37) ➜  prefect git:(master) ✗ pip show mypy
Name: mypy
Version: 0.790
Summary: Optional static typing for Python
Home-page: http://www.mypy-lang.org/
Author: Jukka Lehtosalo
Author-email: jukka.lehtosalo@iki.fi
License: MIT License
Location: /opt/miniconda3/envs/prefect37/lib/python3.7/site-packages
Requires: typed-ast, typing-extensions, mypy-extensions
Required-by:
(prefect37) ➜  prefect git:(master) ✗ python --version
Python 3.7.9
(prefect37) ➜  prefect git:(master) ✗ rm -r .mypy_cache
(prefect37) ➜  prefect git:(master) ✗ mypy src
Success: no issues found in 232 source files
```

**Comment by joshmeek** [comment]
@jcrist Same issue, not the only difference being that I'm on `3.7.3` and you're on `3.7.9`

```
➜ mypy --version
mypy 0.790
(prefect)
prefect on  master [$]
➜ pip show mypy
Name: mypy
Version: 0.790
Summary: Optional static typing for Python
Home-page: http://www.mypy-lang.org/
Author: Jukka Lehtosalo
Author-email: jukka.lehtosalo@iki.fi
License: MIT License
Location: /Users/josh/miniconda3/envs/prefect/lib/python3.7/site-packages
Requires: typing-extensions, mypy-extensions, typed-ast
Required-by: prefect-cloud
(prefect)
prefect on  master [$] took 2s
➜ python --version
Python 3.7.3
(prefect)
prefect on  master [$]
➜ rm -r .mypy_cache
(prefect)
prefect on  master [$] took 2s
➜ mypy src
src/prefect/schedules/clocks.py:261: error: Value of type variable "_LT" of "max" cannot be "Union[datetime, Any, None]"
Found 1 error in 1 file (checked 232 source files)
```

**Review by jcrist — APPROVED** [review]
Hmmm, that's odd. Perhaps something changed with the type hints in the python stdlib between versions? Merging this shouldn't be harmful, so up to you how to handle this.

**Pull request merged**
