### PR TITLE
Add new auth method (service principal) to `Azure` block

### LINKED ISSUE #6838: Add service principal auth support to `Azure` block
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, two out of three common Azure authentication methods are supported:
- [x] account key
- [x] connection string
- [ ] service principal

### Describe the proposed behavior

`adlfs` supports this already:
```python
from adlfs import AzureBlobFileSystem

fs = AzureBlobFileSystem(
    account_name=storage_account_name,
    tenant_id=tenant_id,
    client_id=client_id,
    client_secret=client_secret,
)
```

### Example Use

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Trymzet**
This adds the possibility to use service principal method of authentication in `Azure` block (using `tenant_id`, `client_id`, `client_secret`, and `account_name` as credentials).

Closes #6838.

### Checklist

- [x] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a `fix`, `feature`, `enhancement`, `docs`, `collections`, or `maintenance` label categorizing the change.

### CODE REVIEW

**Review by tpdorsey — COMMENTED** [review]
The docs portion of this looks great. Thank you for the contribution!

**Comment by madkinsz** [comment]
This needs review from @desertaxle

**Review by desertaxle — APPROVED** [review]
LGTM!

**Comment by madkinsz** [comment]
@desertaxle this does not include any test coverage, can you verify it does not break anything? It might be worth assigning an integrations engineer to add coverage as well.

**Pull request merged**
