### PR TITLE
 CircleCI: Add flake8 tests to find syntax errors and undefined names

### PR DESCRIPTION
**Pull request by cclauss**
**Thanks for contributing to Prefect!**

Please describe your work and make sure your PR:

- [x] adds new tests (if appropriate)
- [x] updates `CHANGELOG.md` (if appropriate)
- [x] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

Note that your PR will not be reviewed unless all three boxes are checked.

## What does this PR change?
CircleCI: Add flake8 tests to find syntax errors and undefined names

## Why is this PR important?
Detects syntax errors and undefined names like it #848

### CODE REVIEW

**Comment by cclauss** [comment]
```
flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

./tests/engine/cloud/test_cloud_flows.py:573:33: F821 undefined name 'post'
    session.return_value.post = post
                                ^
./tests/engine/cloud/test_cloud_flows.py:575:42: F821 undefined name 'post'
    monkeypatch.setattr("requests.post", post)
                                         ^
2     F821 undefined name 'post'
2
Exited with code 1
```

**Comment by cicdw** [comment]
Hi @cclauss - thanks for the PR and the initiative! 

Good catch with that test - because it's in an `xfail`, we weren't seeing it.  We will need to remove that line from the test (which you are welcome to do in this PR!).

Early on we decided to enforce `black` + `mypy` over something like `flake8` for a few reasons:
- `black` enforces all necessary PEPs, with no room for arbitrary decisions (we can't pick and choose which linting rules to enforce, they are all enforced)
- `mypy` enforces type checks on critical files (which finds `NameError`s and similar)
- `flake8` will generally duplicate the checks in the above two, and open the door for discussions about which error codes to enforce / ignore; for this reason I won't be merging a `flake8` job

Given that, I'll leave this PR open for a bit in case you want to repurpose it to close #1200, in which case you should also add your name to the `Contributors` list in the Changelog!

**Comment by cclauss** [comment]
On the flake8 test selection (--select=E9,F63,F7,F82), this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__python/black__](https://github.com/python/black) can autocorrect).  Instead these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and equality in Python.  Use ==/!= to compare str, bytes, and int literals is the classic case.  These are areas where __a == b__ is True but __a is b__ is False (or vice versa).
* F7 tests logic errors and syntax errors in type hints
* F82 tests are almost always _undefined names_ which are usually a sign of a typo, missing imports, or code that has not been ported to Python 3.  These also would be compile-time errors in a compiled language but in Python a __NameError__ is raised which will halt/crash the script on the user.

**Comment by cicdw** [comment]
Agreed; however, E9, F7 and F82 will be caught by `mypy` (and also unit tests).  F63 is something that should properly be caught by code review, and I don't want to open the door to hand-picking flake8 error codes to officially enforce.

**Comment by cclauss** [comment]
I will try offline to see which errors black + mypy catch.

**Comment by cclauss** [comment]
It is clear that __flake8__ catches a bunch of stuff that __black__ + __mypy__ does not catch:
```
12    E203 whitespace before ':'
9     E262 inline comment should start with '# '
126   E266 too many leading '#' for block comment
1     E302 expected 2 blank lines, found 1
1135  E501 line too long (95 > 88 characters)
2     E711 comparison to None should be 'if cond is None:'
7     E712 comparison to True should be 'if cond is True:' or 'if cond:'
3     E713 test for membership should be 'not in'
1     E714 test for object identity should be 'is not'
9     E722 do not use bare 'except'
14    E731 do not assign a lambda expression, use a def
11    E741 ambiguous variable name 'l'
468   F401 'sys' imported but unused
23    F811 redefinition of unused 'queue' from line 3
2     F821 undefined name 'post'
105   F841 local variable 'size' is assigned to but never used
2     W291 trailing whitespace
2     W391 blank line at end of file
6     W605 invalid escape sequence '\ '
1938
```

**Comment by cicdw** [comment]
Yes, it is true that `flake8` has different linting rules from `black`.  However, we have chosen to use `black` as our official linter.  In fact this highlights precisely why we avoided `flake8`: your PR selected a few `flake8` rules to enforce, but as you point out that was an arbitrary choice and there are many other rules that could also be enforced, based purely on personal preference.  We prefer to remove the subjective aspect as much as possible.

**Comment by cclauss** [comment]
I think the way to think about it is that black is a formatter and flake8 and pylint are linters.  I am kinda surprised that black did not limit lines to 88 chars but perhaps these are docstring and/or comments that black is not concerned with.  My sense is that we should just close this PR.

**Comment by cicdw** [comment]
Closing per discussion above

**Pull request closed without merging**
