### PR TITLE
Debugging test_pip.py failures.

### PR DESCRIPTION
**Pull request by bunchesofdonald**
A PR to debug the failures we're seeing with `test_pip.py`.

### CODE REVIEW

**Comment by bunchesofdonald** [comment]
@pleek91 I'm not sure, that npm package commit was just the first one that exhibited this symptom, so I'm just bisecing the changes to see where the issue might be.

**Comment by pleek91** [comment]
Interesting, let me know if there's anything I can help with.

**Comment by rsampaths16** [comment]
Hi @bunchesofdonald could be that the `test actions` won't be applied from the pulling change? The same tests started failing for my PR 2 days ago: https://github.com/PrefectHQ/prefect/actions/runs/4707784684

**Comment by bunchesofdonald** [comment]
Interesting, thanks for the extra information!

**Comment by rsampaths16** [comment]
Can you try this
1. keep this change 4fffef902d4d1d0922d5ff5b10c8097166814bdf
2. invoke the workflow
3. add a dummy change
4. invoke workflow again

**Comment by bunchesofdonald** [comment]
It's a good theory, I'll try that next.

**Comment by rsampaths16** [comment]
the changelog shows `pkg_resources` as affected: https://pip.pypa.io/en/stable/news/#vendored-libraries

https://github.com/PrefectHQ/prefect/blob/854c06f4a2f27d2fe468a03ae87b76d8d61961ba/src/prefect/software/pip.py#L37-L39

**Comment by bunchesofdonald** [comment]
Thanks for that research! We also concluded it was the pip version and have merged a fix that pins the pip version until we can explore the full issue. https://github.com/PrefectHQ/prefect/pull/9241

**Pull request closed without merging**
