### PR TITLE
Pass base url to ui env

### PR DESCRIPTION
**Pull request by znicholasbrown**
## Summary

Passes a base url to the UI container on Server startup, allowing serving the UI from a subdirectory/reverse proxy.

## Changes

Changes the CLI server command UI env vars and injects those env vars to the UI docker container

## Importance

Resolves: https://github.com/PrefectHQ/ui/pull/450 and https://github.com/PrefectHQ/ui/issues/109

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Comment by madkinsz** [comment]
@znicholasbrown What's the status of this?

**Comment by znicholasbrown** [comment]
Ah I need to update tests on this - there's another [issue](https://github.com/PrefectHQ/ui/issues/861) with the UI portion that I haven't had a moment to look into but I'll work on these in concert.

**Comment by madkinsz** [comment]
@znicholasbrown still relevant?

**Comment by znicholasbrown** [comment]
I think worth closing for now, I'll open another PR if we need to reintroduce.

**Pull request closed without merging**
