### PR TITLE
only run datadog tests on merge to `main`, not every PR

### LINKED ISSUE #12513: datadog tests are significantly longer than other tests
### First check

- [X] I am a contributor to the Prefect codebase

### examples
- https://github.com/PrefectHQ/prefect/actions/runs/8499942531
- all recent PRs

image

image

our whole unit tests CI _seems_ like it should be able to run in under 10 minutes, but the datadog unit test job takes ~14 minutes (others take 6mins for pg, ~9 mins for sqlite)

if it takes ~40% longer for these tests on every PR, is it worth it? can we run it only on merge to main instead of every PR?

### Impact

time and money

### Additional context

you _could_ remove the docker build etc but thats only about ~2 minutes of the time, these tests seem fundamentally slower because of whatever DD is doing

image

### PR DESCRIPTION
**Pull request by zzstoatzz**
closes #12513 

this PR skips the datadog unit test for PRs, so it only runs on `push` to `main`. this makes the total test suite take about 10.5 minutes, as opposed to 14

### CODE REVIEW

**Comment by chrisguidry** [comment]
Hmm, not sure how I feel about this, because one of the big values of running DataDog during PRs is to help us cut back on test flakes, which also waste a lot of folks' time.  Can we see how things look with Jake's performance boosting PRs?

**Comment by zzstoatzz** [comment]
> Hmm, not sure how I feel about this, because one of the big values of running DataDog during PRs is to help us cut back on test flakes, which also waste a lot of folks' time. Can we see how things look with Jake's performance boosting PRs?

it [seems](https://github.com/PrefectHQ/prefect/actions/runs/8510999973) that after the changes the datadog are nearly twice as long as all the other tests

**Review by chrisguidry — APPROVED** [review]
I'm coming around to this idea because we're definitely seeing 10-15 minute runtimes for the DD test suite.  Let's go for it!

**Comment by zzstoatzz** [comment]
> I'm coming around to this idea because we're definitely seeing 10-15 minute runtimes for the DD test suite. Let's go for it!

**Pull request merged**
