### PR TITLE
Add Firebolt to task library overview

### PR DESCRIPTION
**Pull request by kevinmarr**
## Summary
Added Firebolt to the table of available tasks in the docs, following https://github.com/PrefectHQ/prefect/pull/5265. Only a docs update.

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Comment by kevinmarr** [comment]
Leaving as a draft until we can confirm that `https://docs.prefect.io/api/latest/tasks/firebolt.html` is up on the site.

fyi @desertaxle

**Review by tpdorsey — COMMENTED** [review]
@kevinmarr this looks good. You should also update the tasks table in README.md. Although the verified badge doesn't render there yet, you can include it. I will fix in an upcoming PR for all the verified tasks in README.md.

**Comment by desertaxle** [comment]
@kevinmarr You can remove the draft status from this PR since these changes won't be live until the next `prefect` release. We can merge this before the release to ensure that all the Firebolt info in the docs is released at the same time.

**Comment by kevinmarr** [comment]
Removed draft status and added Firebolt to the task library table in README.md. Please merge if everything looks good to you.

**Review by tpdorsey — APPROVED** [review]

**Comment by kevinmarr** [comment]
@desertaxle Make sure this gets merged before you cut your next release.

**Comment by desertaxle** [comment]
@madkinsz FYI, we'll want to make sure that we merge this PR before the next release so that these doc updates are released along with the new Firebolt task.

**Comment by tpdorsey** [comment]
Superseded by https://github.com/PrefectHQ/prefect/pull/5311, which includes task table updates for all of the recently added tasks.

**Pull request closed without merging**
