### PR TITLE
fix StartFlowRun doc

### PR DESCRIPTION
**Pull request by hazardsy**
## Summary

API documentation regarding StartFlowRun parameter `project_name` did not match what the code does.

## Changes

Removes any mention of difference between Cloud & Core Server in the documentation of the `project_name` parameter of StartFlowRun (init & run).

## Importance

Doc should match what the code does.

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [x] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

### CODE REVIEW

**Review by madkinsz — APPROVED** [review]
Thanks!

**Comment by hazardsy** [comment]
Thanks for the review !
Style checks look good now but it seems like there are issues with tests from the AzureML tasks. Those look like they are running fine locally so I don't know what I should do with them.

**Review by madkinsz — APPROVED** [review]
Sorry, lost track of this one!

**Comment by hazardsy** [comment]
No problem, thanks for the merge !

**Pull request merged**
