### PR TITLE
Add Coiled to integrations catalog docs page

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR adds [Coiled's Prefect functionality](https://docs.coiled.io/user_guide/labs/prefect.html) to the list of integrations on this page https://docs.prefect.io/latest/integrations/ 

### Checklist

- [ ] ~~This pull request references any related issue by including "closes `<link to issue>`"~~
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `maintenance`, `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [ ] ~~This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed.~~

For new functions or classes in the Python SDK:

- [ ] ~~This pull request includes helpful docstrings.~~
- [ ] ~~If a new Python file was added, this pull request contains a stub page in the Python SDK docs and an entry in `mkdocs.yml` navigation.~~

### CODE REVIEW

**Comment by discdiver** [comment]
Hi @jrbourbeau! Thank you for the PR?

The image isn't rendering from an .svg URL link, so looks like we need to have a .png copy saved locally. I updated the link, but can't upload a png image because I don't have push access to your repo to add a file. 

Can you please add the image found below to the docs/collections/img folder?
coiled

**Comment by jrbourbeau** [comment]
Thanks for updating the link @discdiver -- just added the image file

**Comment by discdiver** [comment]
Screenshot 2024-02-27 at 7 05 53 PM

**Review by discdiver — APPROVED** [review]
Thank you!

**Comment by jrbourbeau** [comment]
Thanks @discdiver! 

When I built the docs locally, everything looked fine. However, when I look at the unreleased version of the docs https://docs.prefect.io/unreleased/integrations/ the Coiled logo image isn't being displayed properly. Any idea what might be going on there?

Screenshot 2024-02-28 at 9 49 02 AM

**Comment by jrbourbeau** [comment]
Ah, it looks like the image links are using `latest` https://docs.prefect.io/latest/img/collections/coiled.png (doesn't exist yet) instead of `unreleased` https://docs.prefect.io/unreleased/img/collections/coiled.png (which does exist at the moment)

**Comment by discdiver** [comment]
We should have a release out tomorrow, so should be good in the latest docs then.

**Comment by jrbourbeau** [comment]
Good to know -- thanks @discdiver

**Comment by scharlottej13** [comment]
@discdiver we were also wondering if you'd be OK w/ a link that contains UTM codes? For example, `https://docs.coiled.io/user_guide/labs/prefect.html?utm_source=prefect-docs&utm_medium=integrations`. If so, I'd be happy to open up a PR.

Thanks!

**Comment by jrbourbeau** [comment]
Fair point @scharlottej13 -- I probably should have just done that originally in this PR. Here's a PR that updates the link https://github.com/PrefectHQ/prefect/pull/12108

**Comment by scharlottej13** [comment]
Thanks @jrbourbeau!

**Pull request merged**
